import { ENGINE_TYPES } from '../core/state.js';

export const ANALYTIC_PRESETS = [
  {
    name: "Leonardo Divina Proportione",
    engine: ENGINE_TYPES.AURIS,
    badge: "Leonardo Canon",
    description: "Authentic Luca Pacioli & Leonardo da Vinci architectural pen-and-ink engraving on warm parchment with directional chiaroscuro hatching.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.22,
      bloomRadius: 0.25,
      bloomThreshold: 0.18,
      autoRotateSpeed: 0.5,
      background: "#161512",
    },
    params: {
      archetype: "geodesic",
      scale: 1.35,
      stellaHeight: 0.38,
      twistAngle: 0.14,
      wireWidth: 1.4,
      wireGlow: 1,
      lightColor: "#fef3c7",
      facetColor: "#d1c4a5",
      wireColor: "#262016",
      shadowColor: "#3a3124",
      lightYaw: 315,
      lightPitch: 45,
      lightIntensity: 1.7,
      hatchDensity: 16,
      hatchStrength: 0.95,
      rotSpeedX: 0.18,
      rotSpeedY: 0.4,
      rotSpeedZ: 0.08,
    },
  },
  {
    name: "Geodesic Stellated Sun",
    engine: ENGINE_TYPES.AURIS,
    badge: "Geodesic Sun",
    description: "Multifaceted geodesic icosidodecahedron with directional golden illumination and architectural pen-and-ink cross-hatching.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.5,
      bloomRadius: 0.35,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.6,
      background: "#000000",
    },
    params: {
      archetype: "geodesic",
      scale: 1.4,
      stellaHeight: 0.45,
      twistAngle: 0.14,
      wireWidth: 1.6,
      wireGlow: 1,
      lightColor: "#ffea79",
      facetColor: "#283142",
      wireColor: "#fde047",
      shadowColor: "#070b14",
      lightYaw: 45,
      lightPitch: 35,
      lightIntensity: 1.8,
      hatchDensity: 18,
      hatchStrength: 0.85,
      rotSpeedX: 0.2,
      rotSpeedY: 0.45,
      rotSpeedZ: 0.1,
    },
  },
  {
    name: "Kepler Cubic Compound",
    engine: ENGINE_TYPES.AURIS,
    badge: "Kepler Star",
    description: "Interlocking orthogonal cubes and stellated pyramidal caps with dramatic architectural chiaroscuro shadows.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.45,
      bloomRadius: 0.3,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.5,
      background: "#020408",
    },
    params: {
      archetype: "cubic_compound",
      scale: 1.35,
      stellaHeight: 0.5,
      twistAngle: 0.14,
      wireWidth: 1.5,
      wireGlow: 1,
      lightColor: "#e2e8f0",
      facetColor: "#1e293b",
      wireColor: "#94a3b8",
      shadowColor: "#050811",
      lightYaw: 135,
      lightPitch: 40,
      lightIntensity: 1.8,
      hatchDensity: 16,
      hatchStrength: 0.88,
      rotSpeedX: 0.25,
      rotSpeedY: 0.5,
      rotSpeedZ: 0.08,
    },
  },
  {
    name: "Chiral Square Vortex",
    engine: ENGINE_TYPES.AURIS,
    badge: "Nested Geometry",
    description: "Mathematically precise nested rotating square wireframes with per-layer angular increment creating clean ruled-surface moiré patterns.",
    global: {
      exposure: 1.12,
      bloomStrength: 0.7,
      bloomRadius: 0.4,
      bloomThreshold: 0.11,
      autoRotateSpeed: 0.7,
      background: "#01050a",
    },
    params: {
      archetype: "nested_square",
      scale: 1.45,
      stellaHeight: 0.4,
      twistAngle: 0.14,
      wireWidth: 2.2,
      wireGlow: 1.4,
      lightColor: "#00f0ff",
      facetColor: "#0284c7",
      wireColor: "#38bdf8",
      shadowColor: "#030712",
      lightYaw: 60,
      lightPitch: 45,
      lightIntensity: 1.6,
      hatchDensity: 20,
      hatchStrength: 0.5,
      rotSpeedX: 0.15,
      rotSpeedY: 0.4,
      rotSpeedZ: 0.2,
    },
  },
  {
    name: "Sacred Hexagonal Rosette",
    engine: ENGINE_TYPES.AURIS,
    badge: "Sacred Geometry",
    description: "Concentric hexagonal rings with progressive rotation creating a precise six-fold mandala pattern in architectural wireframe style.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.75,
      bloomRadius: 0.42,
      bloomThreshold: 0.1,
      autoRotateSpeed: 0.65,
      background: "#050209",
    },
    params: {
      archetype: "nested_hex",
      scale: 1.4,
      stellaHeight: 0.35,
      twistAngle: 0.14,
      wireWidth: 2.4,
      wireGlow: 1.45,
      lightColor: "#c084fc",
      facetColor: "#581c87",
      wireColor: "#f472b6",
      shadowColor: "#020617",
      lightYaw: 90,
      lightPitch: 30,
      lightIntensity: 1.6,
      hatchDensity: 20,
      hatchStrength: 0.45,
      rotSpeedX: 0.2,
      rotSpeedY: 0.45,
      rotSpeedZ: 0.15,
    },
  },
  {
    name: "Canonical Hypercube",
    engine: ENGINE_TYPES.TESSERACT,
    badge: "Sketch Canon",
    description: "The authentic archetypal Schlegel projection matching the hand-drawn sketch: 12 outer edges, 12 inner edges, and 8 direct corner struts in rigid 3D perspective.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.7,
      bloomRadius: 0.4,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.8,
      background: "#000000",
    },
    params: {
      edgeMode: "sketch",
      innerScale: 0.48,
      cubeSize: 1.35,
      edgeWidth: 2.6,
      nodeSize: 0.038,
      cellOpacity: 0,
      color1: "#ffed00",
      color2: "#00f0ff",
      colorStrut: "#ffffff",
      nodeColor: "#ffffff",
      cellColor: "#ffed00",
      edgeGlow: 1.25,
      motionMode: "sketch3d",
      rotSpeedX: 0.25,
      rotSpeedY: 0.5,
      pulseSpeed: 1.2,
      rotSpeedXW: 0.35,
      rotSpeedYW: 0.45,
    },
  },
  {
    name: "Harmonic Hyper-Fold",
    engine: ENGINE_TYPES.TESSERACT,
    badge: "4D Inversion",
    description: "Harmonic 4D inversion fold where the inner and outer cubes smoothly exchange dimensions through the 8 corner conduits without shearing.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.75,
      bloomRadius: 0.42,
      bloomThreshold: 0.1,
      autoRotateSpeed: 0.6,
      background: "#000000",
    },
    params: {
      projection: "cell_first",
      edgeMode: "sketch",
      innerScale: 0.48,
      cubeSize: 1.35,
      edgeWidth: 2.8,
      nodeSize: 0.042,
      cellOpacity: 0,
      color1: "#ffed00",
      color2: "#f59e0b",
      colorStrut: "#ffffff",
      nodeColor: "#ffed00",
      cellColor: "#ffed00",
      edgeGlow: 1.4,
      motionMode: "hyperfold",
      rotSpeedX: 0.2,
      rotSpeedY: 0.4,
      pulseSpeed: 1.4,
      rotSpeedXW: 0.4,
      rotSpeedYW: 0.5,
    },
  },
  {
    name: "Cyber Matrix Tesseract",
    engine: ENGINE_TYPES.TESSERACT,
    badge: "Cyberpunk",
    description: "Neon emerald outer framework with vivid violet inner core and lime quantum photon packets traveling along the 8 corner struts.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.75,
      bloomRadius: 0.42,
      bloomThreshold: 0.1,
      autoRotateSpeed: 1,
      background: "#010906",
    },
    params: {
      projection: "cell_first",
      edgeMode: "sketch",
      innerScale: 0.5,
      cubeSize: 1.35,
      edgeWidth: 2.6,
      nodeSize: 0.04,
      cellOpacity: 0.02,
      color1: "#059669",
      color2: "#c084fc",
      colorStrut: "#10b981",
      nodeColor: "#10b981",
      cellColor: "#06b6d4",
      edgeGlow: 1.35,
      motionMode: "pulse",
      rotSpeedX: 0.3,
      rotSpeedY: 0.6,
      pulseSpeed: 1.5,
      rotSpeedXW: 0.5,
      rotSpeedYW: 0.4,
    },
  },
  {
    name: "Monochrome Architect",
    engine: ENGINE_TYPES.TESSERACT,
    badge: "Swiss Minimal",
    description: "Stark pure white and titanium wireframes with pristine geometric alignment against pure obsidian void.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.55,
      bloomRadius: 0.35,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.6,
      background: "#030303",
    },
    params: {
      edgeMode: "sketch",
      innerScale: 0.46,
      cubeSize: 1.4,
      edgeWidth: 2.2,
      nodeSize: 0.032,
      cellOpacity: 0,
      color1: "#ffffff",
      color2: "#94a3b8",
      colorStrut: "#e2e8f0",
      nodeColor: "#ffffff",
      cellColor: "#ffffff",
      edgeGlow: 1,
      motionMode: "sketch3d",
      rotSpeedX: 0.2,
      rotSpeedY: 0.45,
      pulseSpeed: 1,
      rotSpeedXW: 0.3,
      rotSpeedYW: 0.4,
    },
  },
  {
    name: "Clifford Quantum Vortex",
    engine: ENGINE_TYPES.HOPF,
    badge: "S3 to R3",
    description: "Nested Villarceau circles linked in continuous 4D Clifford translation with streaming photons.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.8,
      bloomRadius: 0.42,
      bloomThreshold: 0.1,
      autoRotateSpeed: 0.8,
      background: "#000000",
    },
    params: {
      color1: "#ffed00",
      color2: "#a855f7",
      accentColor: "#00f2fe",
      glowIntensity: 1.6,
      fiberCount: 32,
      torusRadius: 1.75,
      tubeRadius: 0.85,
      lineWidth: 2.8,
      cliffordSpeed: 0.7,
      flowSpeed: 1.2,
      twistHarmonics: 2,
    },
  },
  {
    name: "Solar Tokamak",
    engine: ENGINE_TYPES.HOPF,
    badge: "Thermonuclear",
    description: "Incandescent magnetic fusion confinement rings with blistering plasma filaments.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.95,
      bloomRadius: 0.46,
      bloomThreshold: 0.08,
      autoRotateSpeed: 1,
      background: "#060101",
    },
    params: {
      color1: "#ff5500",
      color2: "#ff0055",
      accentColor: "#ffed00",
      glowIntensity: 2,
      fiberCount: 32,
      torusRadius: 1.9,
      tubeRadius: 0.95,
      lineWidth: 3.2,
      cliffordSpeed: 0.95,
      flowSpeed: 1.8,
      twistHarmonics: 3,
    },
  },
  {
    name: "Aetheric Torus",
    engine: ENGINE_TYPES.HOPF,
    badge: "Ethereal",
    description: "Harmonic pastel fiber ribbons forming linked sacred Villarceau geodesics.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.65,
      bloomRadius: 0.38,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.6,
      background: "#020208",
    },
    params: {
      color1: "#38bdf8",
      color2: "#ec4899",
      accentColor: "#c084fc",
      glowIntensity: 1.3,
      fiberCount: 24,
      torusRadius: 1.65,
      tubeRadius: 0.75,
      lineWidth: 2.4,
      cliffordSpeed: 0.5,
      flowSpeed: 0.9,
      twistHarmonics: 2,
    },
  },
  {
    name: "Neon Villarceau",
    engine: ENGINE_TYPES.HOPF,
    badge: "Hyper-Fiber",
    description: "Maximum density 48-circle Hopf fibration with high-speed Clifford circulation.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.85,
      bloomRadius: 0.44,
      bloomThreshold: 0.09,
      autoRotateSpeed: 1.1,
      background: "#01050a",
    },
    params: {
      color1: "#00f0ff",
      color2: "#10b981",
      accentColor: "#ffed00",
      glowIntensity: 1.8,
      fiberCount: 48,
      torusRadius: 1.8,
      tubeRadius: 0.9,
      lineWidth: 2.6,
      cliffordSpeed: 1.1,
      flowSpeed: 1.5,
      twistHarmonics: 2,
    },
  },
  {
    name: "Lumaform Gold Merkabah",
    engine: ENGINE_TYPES.POLYTOPE,
    badge: "Stella Octangula",
    description: "Dual counter-rotating star tetrahedra with golden dispersion facets and laser geodesic wireframe.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.8,
      bloomRadius: 0.42,
      bloomThreshold: 0.1,
      autoRotateSpeed: 0.8,
      background: "#000000",
    },
    params: {
      color1: "#ffed00",
      color2: "#ec4899",
      coreColor: "#ffffff",
      wireColor: "#00f0ff",
      wireGlow: 1.8,
      facetDispersion: 0.75,
      polytopeType: "merkabah",
      scale: 1.65,
      coreRadius: 0.45,
      wireThickness: 3,
      rotRateA: 0.6,
      rotRateB: -0.6,
    },
  },
  {
    name: "Stellated Aether Crystal",
    engine: ENGINE_TYPES.POLYTOPE,
    badge: "Kepler-Poinsot",
    description: "Golden ratio Kepler star with 12 stellated pyramids and high-index prismatic light dispersion.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.9,
      bloomRadius: 0.45,
      bloomThreshold: 0.08,
      autoRotateSpeed: 1,
      background: "#020108",
    },
    params: {
      color1: "#a855f7",
      color2: "#00f2fe",
      coreColor: "#ffed00",
      wireColor: "#ffed00",
      wireGlow: 2.2,
      facetDispersion: 1.1,
      polytopeType: "kepler_star",
      scale: 1.7,
      coreRadius: 0.5,
      wireThickness: 3.5,
      rotRateA: 0.5,
      rotRateB: -0.5,
    },
  },
  {
    name: "Prismatic Kepler Star",
    engine: ENGINE_TYPES.POLYTOPE,
    badge: "Solar Geometry",
    description: "Incandescent amber and canary Kepler star with pulsating divine core orb.",
    global: {
      exposure: 1.2,
      bloomStrength: 0.95,
      bloomRadius: 0.46,
      bloomThreshold: 0.09,
      autoRotateSpeed: 0.9,
      background: "#040101",
    },
    params: {
      color1: "#ffed00",
      color2: "#ea580c",
      coreColor: "#ffffff",
      wireColor: "#fde047",
      wireGlow: 2.4,
      facetDispersion: 0.85,
      polytopeType: "kepler_star",
      scale: 1.8,
      coreRadius: 0.55,
      wireThickness: 3.8,
      rotRateA: 0.75,
      rotRateB: -0.75,
    },
  },
  {
    name: "Obsidian Sacred Core",
    engine: ENGINE_TYPES.POLYTOPE,
    badge: "Dark Merkabah",
    description: "Dark obsidian facets reflecting neon cyan wireframes and deep magenta counter-spin.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.7,
      bloomRadius: 0.38,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.7,
      background: "#020004",
    },
    params: {
      color1: "#00f0ff",
      color2: "#7928ca",
      coreColor: "#00f0ff",
      wireColor: "#ffed00",
      wireGlow: 1.6,
      facetDispersion: 0.5,
      polytopeType: "merkabah",
      scale: 1.55,
      coreRadius: 0.4,
      wireThickness: 2.8,
      rotRateA: 0.4,
      rotRateB: -0.4,
    },
  },
  {
    name: "Aurora Core",
    engine: ENGINE_TYPES.NEBULA,
    badge: "Signature",
    description: "The authentic organic volumetric energy sphere: emerald-cyan gyroid folds, electric indigo shading, chromatic aberration, and luminous stardust sparkles.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.65,
      bloomRadius: 0.4,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.6,
      background: "#000000",
    },
    params: {
      color1: "#00ffc8",
      color2: "#4466ff",
      colorShell: "#00f2fe",
      aberration: 0.85,
      glowIntensity: 0.007,
      atmosphereStrength: 0.3,
      sphereRadius: 2.15,
      edgeFade: 0.381,
      fractalScale: 0.7602,
      fractalMult: 2.196,
      particleDensity: 0.014,
      sphereSpinSpeed: -0.65,
      fractalWarpSpeed: 0.0262,
    },
  },
  {
    name: "Ember Flare",
    engine: ENGINE_TYPES.NEBULA,
    badge: "Thermonuclear",
    description: "Blazing volcanic solar plasma with turbulent molten gyroid folds and gold stardust sparks.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.7,
      bloomRadius: 0.42,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.8,
      background: "#040101",
    },
    params: {
      color1: "#ff6600",
      color2: "#ff2244",
      colorShell: "#ffcc00",
      aberration: 0.55,
      glowIntensity: 0.018,
      atmosphereStrength: 0.4,
      sphereRadius: 2.15,
      edgeFade: 0.35,
      fractalScale: 0.7602,
      fractalMult: 2.25,
      particleDensity: 0.026,
      sphereSpinSpeed: -0.75,
      fractalWarpSpeed: 0.032,
    },
  },
  {
    name: "Void Singularity",
    engine: ENGINE_TYPES.NEBULA,
    badge: "Deep Void",
    description: "High-aberration deep violet void with ultraviolet energetic folds and cosmic diamond sparkles.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.65,
      bloomRadius: 0.4,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.5,
      background: "#000000",
    },
    params: {
      color1: "#8844ff",
      color2: "#110033",
      colorShell: "#c084fc",
      aberration: 1.1,
      glowIntensity: 0.012,
      atmosphereStrength: 0.32,
      sphereRadius: 2.15,
      edgeFade: 0.38,
      fractalScale: 0.7602,
      fractalMult: 2.196,
      particleDensity: 0.021,
      sphereSpinSpeed: -0.55,
      fractalWarpSpeed: 0.022,
    },
  },
  {
    name: "Glacial Cryo",
    engine: ENGINE_TYPES.NEBULA,
    badge: "Sub-Zero",
    description: "Crystalline arctic sphere with pure zero-kelvin cyan-blue hues and diamond dust sparkles.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.65,
      bloomRadius: 0.38,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.7,
      background: "#01050a",
    },
    params: {
      color1: "#00f0ff",
      color2: "#38bdf8",
      colorShell: "#e0f2fe",
      aberration: 0.52,
      glowIntensity: 0.014,
      atmosphereStrength: 0.38,
      sphereRadius: 2.15,
      edgeFade: 0.35,
      fractalScale: 0.78,
      fractalMult: 2.2,
      particleDensity: 0.024,
      sphereSpinSpeed: 0.55,
      fractalWarpSpeed: 0.024,
    },
  },
  {
    name: "Cyber Matrix",
    engine: ENGINE_TYPES.QUANTUM,
    badge: "Hyper-Grid",
    description: "Neon phosphor lattice folding through four spatial dimensions with luminous line filaments.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.72,
      bloomRadius: 0.44,
      bloomThreshold: 0.08,
      autoRotateSpeed: 1,
      background: "#010906",
    },
    params: {
      shape: "sphere",
      color1: "#059669",
      color2: "#06b6d4",
      color3: "#10b981",
      edgeGlow: 1.2,
      cubeSize: 1.25,
      scaleFactor: 2.15,
      orbitPathWidth: 4.5,
      orbitPathBrightness: 3.5,
      rotSpeedX: 0.18,
      rotSpeedY: 0.28,
      fractalSpeed: 1.1,
      morphSpeed: 1,
    },
  },
  {
    name: "Quantum Prism",
    engine: ENGINE_TYPES.QUANTUM,
    badge: "Dimensional",
    description: "Multi-spectral refractive hypercube reflecting high-frequency quantum oscillations.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.85,
      bloomRadius: 0.46,
      bloomThreshold: 0.07,
      autoRotateSpeed: 1.2,
      background: "#030208",
    },
    params: {
      shape: "cube",
      color1: "#6366f1",
      color2: "#d946ef",
      color3: "#f59e0b",
      edgeGlow: 1.4,
      cubeSize: 1.15,
      scaleFactor: 2.2,
      orbitPathWidth: 5,
      orbitPathBrightness: 4,
      rotSpeedX: 0.22,
      rotSpeedY: 0.32,
      fractalSpeed: 1.2,
      morphSpeed: 1.1,
    },
  },
  {
    name: "Gargantua Singularity",
    engine: ENGINE_TYPES.SINGULARITY,
    badge: "Supermassive",
    description: "Relativistic Kerr black hole with blinding gold accretion disk and gravitational lensing.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.72,
      bloomRadius: 0.42,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.8,
      background: "#000000",
    },
    params: {
      color1: "#f59e0b",
      color2: "#ef4444",
      color3: "#38bdf8",
      horizonRadius: 1.05,
      diskInner: 1.45,
      diskOuter: 3.5,
      warpStrength: 1.35,
      diskSpeed: 0.85,
      dopplerShift: 0.75,
      accretionDensity: 1.6,
      diskTilt: 0.28,
      spiralArms: 3,
      armContrast: 0.65,
    },
  },
  {
    name: "Cygnus X-1 Abyss",
    engine: ENGINE_TYPES.SINGULARITY,
    badge: "Microquasar",
    description: "High-energy stellar mass black hole venting turquoise relativistic plasma jets.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.85,
      bloomRadius: 0.45,
      bloomThreshold: 0.1,
      autoRotateSpeed: 1.1,
      background: "#01050a",
    },
    params: {
      color1: "#00f2fe",
      color2: "#057eff",
      color3: "#a855f7",
      horizonRadius: 0.95,
      diskInner: 1.35,
      diskOuter: 3.6,
      warpStrength: 1.55,
      diskSpeed: 1.15,
      dopplerShift: 0.9,
      accretionDensity: 1.5,
      diskTilt: -0.32,
    },
  }
];
