import { ENGINE_TYPES } from '../core/state.js';

export const BODIES_PRESETS = [
  {
    name: "Opaline Bloom",
    engine: ENGINE_TYPES.PRISM_BLOOM,
    badge: "Iridescent Flora",
    description: "A composed sphere of opaline petals opening in a slow wave around a warm porcelain core.",
    global: {
      exposure: 1,
      bloomStrength: 0.2,
      bloomRadius: 0.3,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#07030b",
    },
    params: {
      petalCount: 48,
      petalLength: 1.32,
      petalWidth: 0.52,
      coreRadius: 0.83,
      bloom: 0.58,
      fold: 0.78,
      waveStrength: 0.42,
      breatheAmp: 0.14,
      breatheSpeed: 0.72,
      innerColor: "#f8c8ff",
      outerColor: "#58c9ff",
      edgeColor: "#fff4cb",
      iridescence: 0.72,
      glow: 1.28,
    },
  },
  {
    name: "Polar Veil",
    engine: ENGINE_TYPES.CORONA_VEIL,
    badge: "Quiet Aurora",
    description: "Fine teal and violet membranes roll over a near-black core like a contained polar light.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.16,
      bloomRadius: 0.26,
      bloomThreshold: 0.44,
      autoRotateSpeed: 0,
      background: "#010408",
    },
    params: {
      veilCount: 8,
      detail: 80,
      coreRadius: 1.62,
      veilSpread: 0.24,
      twist: 0.68,
      waveAmp: 0.055,
      breatheAmp: 0.025,
      driftSpeed: 0.16,
      waveSpeed: 0.48,
      coreColor: "#02040a",
      veilColor: "#62d8d2",
      accentColor: "#b9a7ff",
      opacity: 0.25,
      edgeGlow: 1.25,
    },
  },
  {
    name: "First Contact",
    engine: ENGINE_TYPES.ECHO_RINGS,
    badge: "Remembered Signal",
    description: "Cold wavefronts cross on tilted planes and retain each pulse long enough to feel acknowledged.",
    global: {
      exposure: 1,
      bloomStrength: 0.22,
      bloomRadius: 0.3,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0,
      background: "#010509",
    },
    params: {
      ringCount: 7,
      segments: 128,
      radius: 1.72,
      lineWidth: 2.4,
      tiltSpread: 0.92,
      ringSpacing: 0.82,
      idleWave: 0.42,
      pulseStrength: 1.35,
      driftSpeed: 0.14,
      propagationSpeed: 1,
      baseColor: "#123039",
      echoColor: "#42d9ff",
      coreColor: "#e8fdff",
      glow: 1.65,
    },
  },
  {
    name: "Polished Mercury",
    engine: ENGINE_TYPES.CHROMASPHERE,
    badge: "Liquid Chrome",
    description: "A heavy mirrored body under four softboxes, its surface folding slowly enough to read as liquid rather than as noise.",
    global: {
      exposure: 1,
      bloomStrength: 0.12,
      bloomRadius: 0.22,
      bloomThreshold: 0.55,
      autoRotateSpeed: 0.25,
      background: "#05070c",
    },
    params: {
      detail: 5,
      rippleOctaves: 3,
      barCount: 4,
      radius: 1.45,
      rippleAmount: 0.14,
      rippleScale: 1.9,
      flowSpeed: 0.3,
      spinSpeed: 0.12,
      breatheSpeed: 0.35,
      breatheAmp: 0.03,
      pulseRipple: 0.3,
      metalTint: "#dfe7ef",
      envTop: "#8ea6c8",
      barColor: "#fff6e0",
      envBottom: "#0a0d14",
      envIntensity: 1.5,
      roughness: 0.14,
      fresnelPower: 3.2,
      fresnelGain: 0.55,
      barWidth: 0.3,
    },
  },
  {
    name: "Vocal Resonator",
    engine: ENGINE_TYPES.VOCALIS,
    badge: "Phonetic Diaphragm",
    description: "Acoustic diaphragm rings dilate in harmonic resonance with voice pulses around a glowing glottal core.",
    global: {
      exposure: 1,
      bloomStrength: 0.22,
      bloomRadius: 0.26,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0.1,
      background: "#02050b",
    },
    params: {
      ringCount: 6,
      baseRadius: 1.45,
      diaphragmDepth: 0.6,
      lineWidth: 2.4,
      apertureSize: 0.35,
      vocalRipple: 0.14,
      formantHarmonics: 3,
      formantGain: 1.2,
      breatheAmp: 0.04,
      articulationRate: 1.2,
      plosiveSurge: 1.4,
      coreColor: "#ffffff",
      diaphragmColor: "#00f2fe",
      formantColor: "#a855f7",
      glowIntensity: 1.8,
      glottisDarkness: 0.8,
    },
  },
  {
    name: "Phonetic Diaphragm",
    engine: ENGINE_TYPES.VOCALIS,
    badge: "Glottal Articulation",
    description: "Deep amber and crimson acoustic ribbons expanding and contracting with rapid vowel articulation.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.25,
      bloomRadius: 0.3,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0.12,
      background: "#080204",
    },
    params: {
      ringCount: 8,
      baseRadius: 1.55,
      diaphragmDepth: 0.75,
      lineWidth: 2.8,
      apertureSize: 0.42,
      vocalRipple: 0.22,
      formantHarmonics: 4,
      formantGain: 1.5,
      breatheAmp: 0.06,
      articulationRate: 1.6,
      plosiveSurge: 1.8,
      coreColor: "#ffed00",
      diaphragmColor: "#ff0055",
      formantColor: "#f59e0b",
      glowIntensity: 2.1,
      glottisDarkness: 0.85,
    },
  },
  {
    name: "Siri Pearl",
    engine: ENGINE_TYPES.AETHERIA,
    badge: "Chromatic Luminescence",
    description: "Silky, translucent fluid sphere with undulating surface wavelets, floating internal silk caustics, and a chromatic dispersion halo.",
    global: {
      exposure: 1,
      bloomStrength: 0.24,
      bloomRadius: 0.28,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0.1,
      background: "#02040a",
    },
    params: {
      sphereRadius: 1.55,
      detail: 64,
      causticRibbons: 3,
      fluidSpeed: 0.45,
      fluidWaveAmp: 0.12,
      breatheAmp: 0.04,
      causticSwirl: 0.6,
      pulseGlow: 1.5,
      color1: "#00f2fe",
      color2: "#a855f7",
      color3: "#ff4fd8",
      rimColor: "#ffed00",
      iridescence: 0.85,
      glowIntensity: 1.8,
    },
  },
  {
    name: "Iridescent Aurora",
    engine: ENGINE_TYPES.AETHERIA,
    badge: "Prismatic Fluid",
    description: "Emerald mint, peach champagne, and celestial azure chromatic fluid breathing gently under soft subsurface diffusion.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.26,
      bloomRadius: 0.3,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0.12,
      background: "#010807",
    },
    params: {
      sphereRadius: 1.6,
      detail: 64,
      causticRibbons: 4,
      fluidSpeed: 0.5,
      fluidWaveAmp: 0.16,
      breatheAmp: 0.05,
      causticSwirl: 0.75,
      pulseGlow: 1.7,
      color1: "#34d399",
      color2: "#38bdf8",
      color3: "#fb923c",
      rimColor: "#fef08a",
      iridescence: 1.1,
      glowIntensity: 2,
    },
  },
  {
    name: "Quantum Superposition",
    engine: ENGINE_TYPES.SUPERPOSITION,
    badge: "D-Orbital Clover",
    description: "Hydrogenic probability density lobes rotate with phase interference, collapsing upon observation.",
    global: {
      exposure: 1,
      bloomStrength: 0.2,
      bloomRadius: 0.26,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0.1,
      background: "#020409",
    },
    params: {
      sampleDensity: 6144,
      orbitalScale: 1.45,
      nucleusRadius: 0.38,
      stateMode: "d_orbital",
      pointSize: 2.8,
      coherence: 0.85,
      waveExcursion: 0.45,
      breatheAmp: 0.04,
      collapseStrength: 1.4,
      phaseRate: 1.1,
      psiColorA: "#38bdf8",
      psiColorB: "#f43f5e",
      nodalColor: "#e0f2fe",
      glowIntensity: 1.8,
    },
  },
  {
    name: "Chiral Wavepacket",
    engine: ENGINE_TYPES.SUPERPOSITION,
    badge: "Vortex Orbital",
    description: "Helical orbital angular momentum rings with spinning phase nodes and high quantum coherence.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.22,
      bloomRadius: 0.3,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0.14,
      background: "#030208",
    },
    params: {
      sampleDensity: 9216,
      orbitalScale: 1.55,
      nucleusRadius: 0.35,
      stateMode: "chiral_vortex",
      pointSize: 2.5,
      coherence: 0.92,
      waveExcursion: 0.6,
      breatheAmp: 0.05,
      collapseStrength: 1.6,
      phaseRate: 1.4,
      psiColorA: "#00f2fe",
      psiColorB: "#a855f7",
      nodalColor: "#ffffff",
      glowIntensity: 2,
    },
  },
  {
    name: "Gemini Harmonic",
    engine: ENGINE_TYPES.SYNTHESIS,
    badge: "4-Color Gravitational Fusion",
    description: "Four harmonious luminous fluid bodies in celestial figure-8 orbit, organically fusing with liquid bridges and stardust.",
    global: {
      exposure: 1,
      bloomStrength: 0.22,
      bloomRadius: 0.26,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0.1,
      background: "#020409",
    },
    params: {
      envelopeRadius: 1.6,
      coreRadius: 0.38,
      filamentCount: 6,
      stardustDensity: 64,
      orbitSpread: 0.75,
      orbitSpeed: 0.55,
      fusionTension: 0.65,
      breatheAmp: 0.035,
      coalesceSurge: 1.4,
      color1: "#4285f4",
      color2: "#ea4335",
      color3: "#fbbc05",
      color4: "#34a853",
      veilColor: "#1e1b4b",
      glowIntensity: 1.8,
    },
  },
  {
    name: "Celestial Symbiosis",
    engine: ENGINE_TYPES.SYNTHESIS,
    badge: "Harmonic Modal Ballet",
    description: "Deep sapphire, lavender, rose, and amber fluid lobes linked by glowing gravitational filaments and orbiting micro-sparkles.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.25,
      bloomRadius: 0.3,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0.12,
      background: "#05020a",
    },
    params: {
      envelopeRadius: 1.65,
      coreRadius: 0.42,
      filamentCount: 6,
      stardustDensity: 128,
      orbitSpread: 0.85,
      orbitSpeed: 0.65,
      fusionTension: 0.8,
      breatheAmp: 0.045,
      coalesceSurge: 1.6,
      color1: "#38bdf8",
      color2: "#c084fc",
      color3: "#f43f5e",
      color4: "#fbbf24",
      veilColor: "#312e81",
      glowIntensity: 2.1,
    },
  },
  {
    name: "Magnetic Nebula Oval",
    engine: ENGINE_TYPES.FERRO_TRAILS,
    badge: "Prolate Magnetic Orb & Trails",
    description: "An elongated prolate oval ferrofluid core pulsating with electric cyan magnetic peaks, enveloped in curving neon azure and violet arc trails.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.24,
      bloomRadius: 0.28,
      bloomThreshold: 0.35,
      autoRotateSpeed: 0.12,
      background: "#020308",
    },
    params: {
      ovalRatio: 1.25,
      coreRadius: 1.35,
      trailCount: 12,
      trailDetail: 90,
      particleMotes: 64,
      arcCurvature: 0.85,
      trailSweepSpeed: 0.65,
      magneticSpikes: 0.16,
      spikeFrequency: 3.2,
      fluidViscosity: 0.9,
      breatheAmp: 0.035,
      pulseSurge: 1.5,
      colorLiquid: "#0b1021",
      colorCrest: "#00f0ff",
      colorTrail1: "#38bdf8",
      colorTrail2: "#a855f7",
      colorCore: "#ffffff",
      glowIntensity: 1.8,
    },
  },
  {
    name: "Obsidian Solar Arc",
    engine: ENGINE_TYPES.FERRO_TRAILS,
    badge: "Spherical Ferrofluid Dynamo",
    description: "A spherical obsidian liquid sphere with molten amber and gold magnetic crests, bound by high-curvature ruby arc trails and dense magnetic motes.",
    global: {
      exposure: 1,
      bloomStrength: 0.26,
      bloomRadius: 0.3,
      bloomThreshold: 0.32,
      autoRotateSpeed: 0.15,
      background: "#080302",
    },
    params: {
      ovalRatio: 1,
      coreRadius: 1.4,
      trailCount: 18,
      trailDetail: 90,
      particleMotes: 128,
      arcCurvature: 1.15,
      trailSweepSpeed: 0.8,
      magneticSpikes: 0.24,
      spikeFrequency: 3.8,
      fluidViscosity: 1.1,
      breatheAmp: 0.045,
      pulseSurge: 1.8,
      colorLiquid: "#180a06",
      colorCrest: "#ff9900",
      colorTrail1: "#ff4400",
      colorTrail2: "#ffcc00",
      colorCore: "#ffffff",
      glowIntensity: 2.1,
    },
  }
];
