import { ENGINE_TYPES } from '../core/state.js';

export const PRESET_LIBRARY = [
  // CHIRAL MOIRÉ PRESETS (3D VOLUMETRIC RULED SURFACES & MOTION)
  {
    name: '1. Chiral Square Vortex',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Hyperboloid Funnel',
    description: '3D hyperbolic trumpet vortex with outer diamond rim at +Z and inner rotated square aperture recessed into -Z.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#fcfbf8',
    },
    params: {
      archetype: 'square_vortex',
      scale: 2.1,
      zDepth: 1.4,
      lineDensity: 28,
      innerScale: 0.26,
      twistAngle: 0.72,
      lineWidth: 2.0,
      lineColor: '#0a0a0d',
      lineGlow: 1.0,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.18,
      rotSpeedY: 0.38,
      rotSpeedZ: 0.10,
      breatheSpeed: 0.60,
      breatheAmp: 0.08,
      waveSpeed: 1.20,
      waveAmp: 0.22,
      twistSpeed: 0.40,
      tiltStrength: 0.35,
    },
  },
  {
    name: '2. Hexagonal Chiral Vortex',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Hex Vortex Tower',
    description: 'Six-fold chiral ruled surface chords twisting along a 3D conical hyperboloid trumpet.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#fcfbf8',
    },
    params: {
      archetype: 'hex_vortex',
      scale: 2.1,
      zDepth: 1.45,
      lineDensity: 26,
      innerScale: 0.24,
      twistAngle: 0.55,
      lineWidth: 2.0,
      lineColor: '#0a0a0d',
      lineGlow: 1.0,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.16,
      rotSpeedY: 0.36,
      rotSpeedZ: 0.08,
      breatheSpeed: 0.55,
      breatheAmp: 0.08,
      waveSpeed: 1.15,
      waveAmp: 0.20,
      twistSpeed: 0.35,
      tiltStrength: 0.35,
    },
  },
  {
    name: '3. Pentagonal String Polygon',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Pentagonal Hypar Dome',
    description: 'Five-fold parabolic curve stitching across non-coplanar 3D edges, forming an architectural hyperbolic paraboloid vault.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#fcfbf8',
    },
    params: {
      archetype: 'pentagon_envelope',
      scale: 2.15,
      zDepth: 1.35,
      lineDensity: 22,
      innerScale: 0.30,
      twistAngle: 0.60,
      lineWidth: 2.0,
      lineColor: '#0a0a0d',
      lineGlow: 1.0,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.20,
      rotSpeedY: 0.40,
      rotSpeedZ: 0.10,
      breatheSpeed: 0.50,
      breatheAmp: 0.07,
      waveSpeed: 1.25,
      waveAmp: 0.24,
      twistSpeed: 0.40,
      tiltStrength: 0.35,
    },
  },
  {
    name: '4. Stellated Moiré Star',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Toroidal Star Cage',
    description: 'Concentric rotating polygon tiers distributed along a 3D spherical shell, forming a hollow star polytope.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#fcfbf8',
    },
    params: {
      archetype: 'stellated_rosette',
      scale: 2.2,
      zDepth: 1.30,
      lineDensity: 24,
      innerScale: 0.35,
      twistAngle: 0.40,
      lineWidth: 2.0,
      lineColor: '#0a0a0d',
      lineGlow: 1.0,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.18,
      rotSpeedY: 0.35,
      rotSpeedZ: 0.12,
      breatheSpeed: 0.50,
      breatheAmp: 0.08,
      waveSpeed: 1.10,
      waveAmp: 0.20,
      twistSpeed: 0.45,
      tiltStrength: 0.35,
    },
  },
  {
    name: '5. Astroid Quadrilateral Frame',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Astroid Saddle Vault',
    description: 'Four-cusp parabolic string envelope bridging non-coplanar alternating 3D corners with double-curved saddle geometry.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#fcfbf8',
    },
    params: {
      archetype: 'astroid_quad',
      scale: 2.1,
      zDepth: 1.40,
      lineDensity: 24,
      innerScale: 0.28,
      twistAngle: 0.50,
      lineWidth: 2.0,
      lineColor: '#0a0a0d',
      lineGlow: 1.0,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.22,
      rotSpeedY: 0.38,
      rotSpeedZ: 0.10,
      breatheSpeed: 0.50,
      breatheAmp: 0.07,
      waveSpeed: 1.20,
      waveAmp: 0.22,
      twistSpeed: 0.40,
      tiltStrength: 0.35,
    },
  },
  {
    name: '6. Guilloché Spirograph Rosette',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Toroidal Spirograph Orb',
    description: 'Harmonic 16-lobed hypotrochoid loops undulating in 3D along a toroidal surface with intersecting lace chords.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#fcfbf8',
    },
    params: {
      archetype: 'guilloche_rosette',
      scale: 2.1,
      zDepth: 1.35,
      lineDensity: 28,
      innerScale: 0.32,
      twistAngle: 0.60,
      lineWidth: 1.8,
      lineColor: '#0a0a0d',
      lineGlow: 1.0,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.18,
      rotSpeedY: 0.35,
      rotSpeedZ: 0.12,
      breatheSpeed: 0.45,
      breatheAmp: 0.06,
      waveSpeed: 1.15,
      waveAmp: 0.20,
      twistSpeed: 0.35,
      tiltStrength: 0.35,
    },
  },
  {
    name: '7. Triangular Chiral Vortex',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Tetrahedral Vortex',
    description: 'Three-fold chiral vortex chords connecting an outer inverted triangle rim to an aperture recessed deeply into 3D space.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#fcfbf8',
    },
    params: {
      archetype: 'triangle_vortex',
      scale: 2.2,
      zDepth: 1.45,
      lineDensity: 26,
      innerScale: 0.26,
      twistAngle: 0.85,
      lineWidth: 2.0,
      lineColor: '#0a0a0d',
      lineGlow: 1.0,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.20,
      rotSpeedY: 0.40,
      rotSpeedZ: 0.10,
      breatheSpeed: 0.55,
      breatheAmp: 0.08,
      waveSpeed: 1.20,
      waveAmp: 0.22,
      twistSpeed: 0.40,
      tiltStrength: 0.35,
    },
  },
  {
    name: '8. Perspective Triangle Tunnel',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Perspective Corridor',
    description: 'Authentic 3D spatial triangular corridor stepping back through Z into infinity with longitudinal depth guide rails.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#fcfbf8',
    },
    params: {
      archetype: 'triangle_tunnel',
      scale: 2.1,
      zDepth: 1.55,
      lineDensity: 24,
      innerScale: 0.25,
      twistAngle: 0.0,
      lineWidth: 2.0,
      lineColor: '#0a0a0d',
      lineGlow: 1.0,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.15,
      rotSpeedY: 0.35,
      rotSpeedZ: 0.08,
      breatheSpeed: 0.45,
      breatheAmp: 0.06,
      waveSpeed: 1.10,
      waveAmp: 0.18,
      twistSpeed: 0.30,
      tiltStrength: 0.35,
    },
  },
  {
    name: '9. Bilateral Winged Moiré',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Bilateral Winged Saddle',
    description: 'Dual symmetric parabolic 3D string fans creating arched wing horns in +Z, a central recessed void, and a curling 3D fringe.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#fcfbf8',
    },
    params: {
      archetype: 'winged_moire',
      scale: 2.1,
      zDepth: 1.45,
      lineDensity: 34,
      innerScale: 0.30,
      twistAngle: 0.0,
      lineWidth: 2.0,
      lineColor: '#0a0a0d',
      lineGlow: 1.0,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.18,
      rotSpeedY: 0.36,
      rotSpeedZ: 0.08,
      breatheSpeed: 0.50,
      breatheAmp: 0.06,
      waveSpeed: 1.15,
      waveAmp: 0.20,
      twistSpeed: 0.35,
      tiltStrength: 0.35,
    },
  },
  {
    name: 'Cyber Gold Chiral Vortex',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Cyber Gold Funnel',
    description: 'Luminescent solar gold 3D hyperboloid vortex with harmonic wave undulation and radiant bloom on void black.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.45,
      bloomRadius: 0.30,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.3,
      background: '#000000',
    },
    params: {
      archetype: 'square_vortex',
      scale: 2.1,
      zDepth: 1.5,
      lineDensity: 30,
      innerScale: 0.26,
      twistAngle: 0.72,
      lineWidth: 2.2,
      lineColor: '#ffed00',
      lineGlow: 1.8,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.20,
      rotSpeedY: 0.45,
      rotSpeedZ: 0.12,
      breatheSpeed: 0.65,
      breatheAmp: 0.10,
      waveSpeed: 1.30,
      waveAmp: 0.25,
      twistSpeed: 0.45,
      tiltStrength: 0.40,
    },
  },
  {
    name: 'Electric Cyan Moiré Rosette',
    engine: ENGINE_TYPES.MOIRE,
    badge: '3D Cyber Cyan Orb',
    description: 'Electric cyan 3D toroidal spirograph lace on pitch black with continuous 3D rotation and volumetric depth.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.45,
      bloomRadius: 0.30,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.3,
      background: '#000000',
    },
    params: {
      archetype: 'guilloche_rosette',
      scale: 2.1,
      zDepth: 1.45,
      lineDensity: 28,
      innerScale: 0.32,
      twistAngle: 0.60,
      lineWidth: 2.2,
      lineColor: '#00f0ff',
      lineGlow: 1.8,
      motionMode: 'orbit_3d',
      rotSpeedX: 0.20,
      rotSpeedY: 0.42,
      rotSpeedZ: 0.12,
      breatheSpeed: 0.50,
      breatheAmp: 0.08,
      waveSpeed: 1.20,
      waveAmp: 0.22,
      twistSpeed: 0.40,
      tiltStrength: 0.40,
    },
  },
  {
    name: 'Leonardo Divina Proportione',
    engine: ENGINE_TYPES.AURIS,
    badge: 'Leonardo Canon',
    description: 'Authentic Luca Pacioli & Leonardo da Vinci architectural pen-and-ink engraving on warm parchment with directional chiaroscuro hatching.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.22,
      bloomRadius: 0.25,
      bloomThreshold: 0.18,
      autoRotateSpeed: 0.5,
      background: '#161512',
    },
    params: {
      archetype: 'geodesic',
      scale: 1.35,
      stellaHeight: 0.38,
      twistAngle: 0.14,
      wireWidth: 1.4,
      wireGlow: 1.0,
      lightColor: '#fef3c7',
      facetColor: '#d1c4a5',
      wireColor: '#262016',
      shadowColor: '#3a3124',
      lightYaw: 315,
      lightPitch: 45,
      lightIntensity: 1.7,
      hatchDensity: 16,
      hatchStrength: 0.95,
      rotSpeedX: 0.18,
      rotSpeedY: 0.40,
      rotSpeedZ: 0.08,
    },
  },
  {
    name: 'Geodesic Stellated Sun',
    engine: ENGINE_TYPES.AURIS,
    badge: 'Geodesic Sun',
    description: 'Multifaceted geodesic icosidodecahedron with directional golden illumination and architectural pen-and-ink cross-hatching.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.50,
      bloomRadius: 0.35,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.6,
      background: '#000000',
    },
    params: {
      archetype: 'geodesic',
      scale: 1.4,
      stellaHeight: 0.45,
      twistAngle: 0.14,
      wireWidth: 1.6,
      wireGlow: 1.0,
      lightColor: '#ffea79',
      facetColor: '#283142',
      wireColor: '#fde047',
      shadowColor: '#070b14',
      lightYaw: 45,
      lightPitch: 35,
      lightIntensity: 1.8,
      hatchDensity: 18,
      hatchStrength: 0.85,
      rotSpeedX: 0.20,
      rotSpeedY: 0.45,
      rotSpeedZ: 0.10,
    },
  },
  {
    name: 'Kepler Cubic Compound',
    engine: ENGINE_TYPES.AURIS,
    badge: 'Kepler Star',
    description: 'Interlocking orthogonal cubes and stellated pyramidal caps with dramatic architectural chiaroscuro shadows.',
    global: {
      exposure: 1.10,
      bloomStrength: 0.45,
      bloomRadius: 0.30,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.5,
      background: '#020408',
    },
    params: {
      archetype: 'cubic_compound',
      scale: 1.35,
      stellaHeight: 0.50,
      twistAngle: 0.14,
      wireWidth: 1.5,
      wireGlow: 1.0,
      lightColor: '#e2e8f0',
      facetColor: '#1e293b',
      wireColor: '#94a3b8',
      shadowColor: '#050811',
      lightYaw: 135,
      lightPitch: 40,
      lightIntensity: 1.8,
      hatchDensity: 16,
      hatchStrength: 0.88,
      rotSpeedX: 0.25,
      rotSpeedY: 0.50,
      rotSpeedZ: 0.08,
    },
  },
  {
    name: 'Chiral Square Vortex',
    engine: ENGINE_TYPES.AURIS,
    badge: 'Nested Geometry',
    description: 'Mathematically precise nested rotating square wireframes with per-layer angular increment creating clean ruled-surface moiré patterns.',
    global: {
      exposure: 1.12,
      bloomStrength: 0.70,
      bloomRadius: 0.40,
      bloomThreshold: 0.11,
      autoRotateSpeed: 0.7,
      background: '#01050a',
    },
    params: {
      archetype: 'nested_square',
      scale: 1.45,
      stellaHeight: 0.40,
      twistAngle: 0.14,
      wireWidth: 2.2,
      wireGlow: 1.4,
      lightColor: '#00f0ff',
      facetColor: '#0284c7',
      wireColor: '#38bdf8',
      shadowColor: '#030712',
      lightYaw: 60,
      lightPitch: 45,
      lightIntensity: 1.6,
      hatchDensity: 20,
      hatchStrength: 0.50,
      rotSpeedX: 0.15,
      rotSpeedY: 0.40,
      rotSpeedZ: 0.20,
    },
  },
  {
    name: 'Sacred Hexagonal Rosette',
    engine: ENGINE_TYPES.AURIS,
    badge: 'Sacred Geometry',
    description: 'Concentric hexagonal rings with progressive rotation creating a precise six-fold mandala pattern in architectural wireframe style.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.75,
      bloomRadius: 0.42,
      bloomThreshold: 0.10,
      autoRotateSpeed: 0.65,
      background: '#050209',
    },
    params: {
      archetype: 'nested_hex',
      scale: 1.4,
      stellaHeight: 0.35,
      twistAngle: 0.14,
      wireWidth: 2.4,
      wireGlow: 1.45,
      lightColor: '#c084fc',
      facetColor: '#581c87',
      wireColor: '#f472b6',
      shadowColor: '#020617',
      lightYaw: 90,
      lightPitch: 30,
      lightIntensity: 1.6,
      hatchDensity: 20,
      hatchStrength: 0.45,
      rotSpeedX: 0.20,
      rotSpeedY: 0.45,
      rotSpeedZ: 0.15,
    },
  },

  // 4D TESSERACT PRESETS
  {
    name: 'Canonical Hypercube',
    engine: ENGINE_TYPES.TESSERACT,
    badge: 'Sketch Canon',
    description: 'The authentic archetypal Schlegel projection matching the hand-drawn sketch: 12 outer edges, 12 inner edges, and 8 direct corner struts in rigid 3D perspective.',
    global: {
      exposure: 1.10,
      bloomStrength: 0.70,
      bloomRadius: 0.40,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.8,
      background: '#000000',
    },
    params: {
      edgeMode: 'sketch',
      innerScale: 0.48,
      cubeSize: 1.35,
      edgeWidth: 2.6,
      nodeSize: 0.038,
      cellOpacity: 0.0,
      color1: '#ffed00',
      color2: '#00f0ff',
      colorStrut: '#ffffff',
      nodeColor: '#ffffff',
      cellColor: '#ffed00',
      edgeGlow: 1.25,
      motionMode: 'sketch3d',
      rotSpeedX: 0.25,
      rotSpeedY: 0.50,
      pulseSpeed: 1.2,
      rotSpeedXW: 0.35,
      rotSpeedYW: 0.45,
    },
  },
  {
    name: 'Harmonic Hyper-Fold',
    engine: ENGINE_TYPES.TESSERACT,
    badge: '4D Inversion',
    description: 'Harmonic 4D inversion fold where the inner and outer cubes smoothly exchange dimensions through the 8 corner conduits without shearing.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.75,
      bloomRadius: 0.42,
      bloomThreshold: 0.10,
      autoRotateSpeed: 0.6,
      background: '#000000',
    },
    params: {
      edgeMode: 'sketch',
      innerScale: 0.48,
      cubeSize: 1.35,
      edgeWidth: 2.8,
      nodeSize: 0.042,
      cellOpacity: 0.0,
      color1: '#ffed00',
      color2: '#f59e0b',
      colorStrut: '#ffffff',
      nodeColor: '#ffed00',
      cellColor: '#ffed00',
      edgeGlow: 1.4,
      motionMode: 'hyperfold',
      rotSpeedX: 0.20,
      rotSpeedY: 0.40,
      pulseSpeed: 1.4,
      rotSpeedXW: 0.4,
      rotSpeedYW: 0.5,
    },
  },
  {
    name: 'Cyber Matrix Tesseract',
    engine: ENGINE_TYPES.TESSERACT,
    badge: 'Cyberpunk',
    description: 'Neon emerald outer framework with vivid violet inner core and lime quantum photon packets traveling along the 8 corner struts.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.75,
      bloomRadius: 0.42,
      bloomThreshold: 0.10,
      autoRotateSpeed: 1.0,
      background: '#010906',
    },
    params: {
      edgeMode: 'sketch',
      innerScale: 0.50,
      cubeSize: 1.35,
      edgeWidth: 2.6,
      nodeSize: 0.04,
      cellOpacity: 0.02,
      color1: '#059669',
      color2: '#c084fc',
      colorStrut: '#10b981',
      nodeColor: '#10b981',
      cellColor: '#06b6d4',
      edgeGlow: 1.35,
      motionMode: 'pulse',
      rotSpeedX: 0.30,
      rotSpeedY: 0.60,
      pulseSpeed: 1.5,
      rotSpeedXW: 0.5,
      rotSpeedYW: 0.4,
    },
  },
  {
    name: 'Monochrome Architect',
    engine: ENGINE_TYPES.TESSERACT,
    badge: 'Swiss Minimal',
    description: 'Stark pure white and titanium wireframes with pristine geometric alignment against pure obsidian void.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.55,
      bloomRadius: 0.35,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.6,
      background: '#030303',
    },
    params: {
      edgeMode: 'sketch',
      innerScale: 0.46,
      cubeSize: 1.4,
      edgeWidth: 2.2,
      nodeSize: 0.032,
      cellOpacity: 0.0,
      color1: '#ffffff',
      color2: '#94a3b8',
      colorStrut: '#e2e8f0',
      nodeColor: '#ffffff',
      cellColor: '#ffffff',
      edgeGlow: 1.0,
      motionMode: 'sketch3d',
      rotSpeedX: 0.20,
      rotSpeedY: 0.45,
      pulseSpeed: 1.0,
      rotSpeedXW: 0.3,
      rotSpeedYW: 0.4,
    },
  },

  // HOPF FIBRATION PRESETS
  {
    name: 'Clifford Quantum Vortex',
    engine: ENGINE_TYPES.HOPF,
    badge: 'S3 to R3',
    description: 'Nested Villarceau circles linked in continuous 4D Clifford translation with streaming photons.',
    global: {
      exposure: 1.1,
      bloomStrength: 0.8,
      bloomRadius: 0.42,
      bloomThreshold: 0.10,
      autoRotateSpeed: 0.8,
      background: '#000000',
    },
    params: {
      color1: '#ffed00',
      color2: '#a855f7',
      accentColor: '#00f2fe',
      glowIntensity: 1.6,
      fiberCount: 32,
      torusRadius: 1.75,
      tubeRadius: 0.85,
      lineWidth: 2.8,
      cliffordSpeed: 0.70,
      flowSpeed: 1.2,
      twistHarmonics: 2.0,
    },
  },
  {
    name: 'Solar Tokamak',
    engine: ENGINE_TYPES.HOPF,
    badge: 'Thermonuclear',
    description: 'Incandescent magnetic fusion confinement rings with blistering plasma filaments.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.95,
      bloomRadius: 0.46,
      bloomThreshold: 0.08,
      autoRotateSpeed: 1.0,
      background: '#060101',
    },
    params: {
      color1: '#ff5500',
      color2: '#ff0055',
      accentColor: '#ffed00',
      glowIntensity: 2.0,
      fiberCount: 32,
      torusRadius: 1.9,
      tubeRadius: 0.95,
      lineWidth: 3.2,
      cliffordSpeed: 0.95,
      flowSpeed: 1.8,
      twistHarmonics: 3.0,
    },
  },
  {
    name: 'Aetheric Torus',
    engine: ENGINE_TYPES.HOPF,
    badge: 'Ethereal',
    description: 'Harmonic pastel fiber ribbons forming linked sacred Villarceau geodesics.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.65,
      bloomRadius: 0.38,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.6,
      background: '#020208',
    },
    params: {
      color1: '#38bdf8',
      color2: '#ec4899',
      accentColor: '#c084fc',
      glowIntensity: 1.3,
      fiberCount: 24,
      torusRadius: 1.65,
      tubeRadius: 0.75,
      lineWidth: 2.4,
      cliffordSpeed: 0.5,
      flowSpeed: 0.9,
      twistHarmonics: 2.0,
    },
  },
  {
    name: 'Neon Villarceau',
    engine: ENGINE_TYPES.HOPF,
    badge: 'Hyper-Fiber',
    description: 'Maximum density 48-circle Hopf fibration with high-speed Clifford circulation.',
    global: {
      exposure: 1.1,
      bloomStrength: 0.85,
      bloomRadius: 0.44,
      bloomThreshold: 0.09,
      autoRotateSpeed: 1.1,
      background: '#01050a',
    },
    params: {
      color1: '#00f0ff',
      color2: '#10b981',
      accentColor: '#ffed00',
      glowIntensity: 1.8,
      fiberCount: 48,
      torusRadius: 1.8,
      tubeRadius: 0.9,
      lineWidth: 2.6,
      cliffordSpeed: 1.1,
      flowSpeed: 1.5,
      twistHarmonics: 2.0,
    },
  },

  // SACRED POLYTOPE PRESETS
  {
    name: 'Lumaform Gold Merkabah',
    engine: ENGINE_TYPES.POLYTOPE,
    badge: 'Stella Octangula',
    description: 'Dual counter-rotating star tetrahedra with golden dispersion facets and laser geodesic wireframe.',
    global: {
      exposure: 1.1,
      bloomStrength: 0.8,
      bloomRadius: 0.42,
      bloomThreshold: 0.10,
      autoRotateSpeed: 0.8,
      background: '#000000',
    },
    params: {
      color1: '#ffed00',
      color2: '#ec4899',
      coreColor: '#ffffff',
      wireColor: '#00f0ff',
      wireGlow: 1.8,
      facetDispersion: 0.75,
      polytopeType: 'merkabah',
      scale: 1.65,
      coreRadius: 0.45,
      wireThickness: 3.0,
      rotRateA: 0.60,
      rotRateB: -0.60,
    },
  },
  {
    name: 'Stellated Aether Crystal',
    engine: ENGINE_TYPES.POLYTOPE,
    badge: 'Kepler-Poinsot',
    description: 'Golden ratio Kepler star with 12 stellated pyramids and high-index prismatic light dispersion.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.9,
      bloomRadius: 0.45,
      bloomThreshold: 0.08,
      autoRotateSpeed: 1.0,
      background: '#020108',
    },
    params: {
      color1: '#a855f7',
      color2: '#00f2fe',
      coreColor: '#ffed00',
      wireColor: '#ffed00',
      wireGlow: 2.2,
      facetDispersion: 1.1,
      polytopeType: 'kepler_star',
      scale: 1.7,
      coreRadius: 0.5,
      wireThickness: 3.5,
      rotRateA: 0.5,
      rotRateB: -0.5,
    },
  },
  {
    name: 'Prismatic Kepler Star',
    engine: ENGINE_TYPES.POLYTOPE,
    badge: 'Solar Geometry',
    description: 'Incandescent amber and canary Kepler star with pulsating divine core orb.',
    global: {
      exposure: 1.2,
      bloomStrength: 0.95,
      bloomRadius: 0.46,
      bloomThreshold: 0.09,
      autoRotateSpeed: 0.9,
      background: '#040101',
    },
    params: {
      color1: '#ffed00',
      color2: '#ea580c',
      coreColor: '#ffffff',
      wireColor: '#fde047',
      wireGlow: 2.4,
      facetDispersion: 0.85,
      polytopeType: 'kepler_star',
      scale: 1.8,
      coreRadius: 0.55,
      wireThickness: 3.8,
      rotRateA: 0.75,
      rotRateB: -0.75,
    },
  },
  {
    name: 'Obsidian Sacred Core',
    engine: ENGINE_TYPES.POLYTOPE,
    badge: 'Dark Merkabah',
    description: 'Dark obsidian facets reflecting neon cyan wireframes and deep magenta counter-spin.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.7,
      bloomRadius: 0.38,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.7,
      background: '#020004',
    },
    params: {
      color1: '#00f0ff',
      color2: '#7928ca',
      coreColor: '#00f0ff',
      wireColor: '#ffed00',
      wireGlow: 1.6,
      facetDispersion: 0.5,
      polytopeType: 'merkabah',
      scale: 1.55,
      coreRadius: 0.4,
      wireThickness: 2.8,
      rotRateA: 0.4,
      rotRateB: -0.4,
    },
  },

  // GYROID NEBULA PRESETS
  {
    name: 'Aurora Core',
    engine: ENGINE_TYPES.NEBULA,
    badge: 'Signature',
    description: 'The authentic organic volumetric energy sphere: emerald-cyan gyroid folds, electric indigo shading, chromatic aberration, and luminous stardust sparkles.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.65,
      bloomRadius: 0.40,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.6,
      background: '#000000',
    },
    params: {
      color1: '#00ffc8',
      color2: '#4466ff',
      colorShell: '#00f2fe',
      aberration: 0.85,
      glowIntensity: 0.007,
      atmosphereStrength: 0.30,
      sphereRadius: 2.15,
      edgeFade: 0.381,
      fractalScale: 0.7602,
      fractalMult: 2.196,
      particleDensity: 0.014,
      sphereSpinSpeed: -0.65,
      fractalWarpSpeed: 0.0262,
    },
  },
  {
    name: 'Ember Flare',
    engine: ENGINE_TYPES.NEBULA,
    badge: 'Thermonuclear',
    description: 'Blazing volcanic solar plasma with turbulent molten gyroid folds and gold stardust sparks.',
    global: {
      exposure: 1.10,
      bloomStrength: 0.70,
      bloomRadius: 0.42,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.8,
      background: '#040101',
    },
    params: {
      color1: '#ff6600',
      color2: '#ff2244',
      colorShell: '#ffcc00',
      aberration: 0.55,
      glowIntensity: 0.018,
      atmosphereStrength: 0.40,
      sphereRadius: 2.15,
      edgeFade: 0.35,
      fractalScale: 0.7602,
      fractalMult: 2.25,
      particleDensity: 0.026,
      sphereSpinSpeed: -0.75,
      fractalWarpSpeed: 0.032,
    },
  },
  {
    name: 'Void Singularity',
    engine: ENGINE_TYPES.NEBULA,
    badge: 'Deep Void',
    description: 'High-aberration deep violet void with ultraviolet energetic folds and cosmic diamond sparkles.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.65,
      bloomRadius: 0.40,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.5,
      background: '#000000',
    },
    params: {
      color1: '#8844ff',
      color2: '#110033',
      colorShell: '#c084fc',
      aberration: 1.10,
      glowIntensity: 0.012,
      atmosphereStrength: 0.32,
      sphereRadius: 2.15,
      edgeFade: 0.38,
      fractalScale: 0.7602,
      fractalMult: 2.196,
      particleDensity: 0.021,
      sphereSpinSpeed: -0.55,
      fractalWarpSpeed: 0.022,
    },
  },
  {
    name: 'Glacial Cryo',
    engine: ENGINE_TYPES.NEBULA,
    badge: 'Sub-Zero',
    description: 'Crystalline arctic sphere with pure zero-kelvin cyan-blue hues and diamond dust sparkles.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.65,
      bloomRadius: 0.38,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.7,
      background: '#01050a',
    },
    params: {
      color1: '#00f0ff',
      color2: '#38bdf8',
      colorShell: '#e0f2fe',
      aberration: 0.52,
      glowIntensity: 0.014,
      atmosphereStrength: 0.38,
      sphereRadius: 2.15,
      edgeFade: 0.35,
      fractalScale: 0.78,
      fractalMult: 2.2,
      particleDensity: 0.024,
      sphereSpinSpeed: 0.55,
      fractalWarpSpeed: 0.024,
    },
  },

  // QUANTUM LATTICE PRESETS
  {
    name: 'Cyber Matrix',
    engine: ENGINE_TYPES.QUANTUM,
    badge: 'Hyper-Grid',
    description: 'Neon phosphor lattice folding through four spatial dimensions with luminous line filaments.',
    global: {
      exposure: 1.1,
      bloomStrength: 0.72,
      bloomRadius: 0.44,
      bloomThreshold: 0.08,
      autoRotateSpeed: 1.0,
      background: '#010906',
    },
    params: {
      shape: 'sphere',
      color1: '#059669',
      color2: '#06b6d4',
      color3: '#10b981',
      edgeGlow: 1.2,
      cubeSize: 1.25,
      scaleFactor: 2.15,
      orbitPathWidth: 4.5,
      orbitPathBrightness: 3.5,
      rotSpeedX: 0.18,
      rotSpeedY: 0.28,
      fractalSpeed: 1.1,
      morphSpeed: 1.0,
    },
  },
  {
    name: 'Quantum Prism',
    engine: ENGINE_TYPES.QUANTUM,
    badge: 'Dimensional',
    description: 'Multi-spectral refractive hypercube reflecting high-frequency quantum oscillations.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.85,
      bloomRadius: 0.46,
      bloomThreshold: 0.07,
      autoRotateSpeed: 1.2,
      background: '#030208',
    },
    params: {
      shape: 'cube',
      color1: '#6366f1',
      color2: '#d946ef',
      color3: '#f59e0b',
      edgeGlow: 1.4,
      cubeSize: 1.15,
      scaleFactor: 2.2,
      orbitPathWidth: 5.0,
      orbitPathBrightness: 4.0,
      rotSpeedX: 0.22,
      rotSpeedY: 0.32,
      fractalSpeed: 1.2,
      morphSpeed: 1.1,
    },
  },

  // CHRONO SINGULARITY PRESETS
  {
    name: 'Gargantua Singularity',
    engine: ENGINE_TYPES.SINGULARITY,
    badge: 'Supermassive',
    description: 'Relativistic Kerr black hole with blinding gold accretion disk and gravitational lensing.',
    global: {
      exposure: 1.1,
      bloomStrength: 0.72,
      bloomRadius: 0.42,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.8,
      background: '#000000',
    },
    params: {
      color1: '#f59e0b',
      color2: '#ef4444',
      color3: '#38bdf8',
      horizonRadius: 1.05,
      diskInner: 1.45,
      diskOuter: 3.5,
      warpStrength: 1.35,
      diskSpeed: 0.85,
      dopplerShift: 0.75,
      accretionDensity: 1.6,
      diskTilt: 0.28,
    },
  },
  {
    name: 'Cygnus X-1 Abyss',
    engine: ENGINE_TYPES.SINGULARITY,
    badge: 'Microquasar',
    description: 'High-energy stellar mass black hole venting turquoise relativistic plasma jets.',
    global: {
      exposure: 1.15,
      bloomStrength: 0.85,
      bloomRadius: 0.45,
      bloomThreshold: 0.10,
      autoRotateSpeed: 1.1,
      background: '#01050a',
    },
    params: {
      color1: '#00f2fe',
      color2: '#057eff',
      color3: '#a855f7',
      horizonRadius: 0.95,
      diskInner: 1.35,
      diskOuter: 3.6,
      warpStrength: 1.55,
      diskSpeed: 1.15,
      dopplerShift: 0.9,
      accretionDensity: 1.5,
      diskTilt: -0.32,
    },
  },

  {
    name: 'Neon Voice Ribbon',
    engine: ENGINE_TYPES.FLUX,
    badge: 'Travelling Wave',
    description: 'A wide band of strands streaming past, fanning apart and converging into bright knots. The voice-assistant waveform read.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.35,
      bloomRadius: 0.35,
      bloomThreshold: 0.30,
      autoRotateSpeed: 0.0,
      background: '#05010c',
    },
    params: {
      layout: 'ribbon',
      strands: 28,
      segments: 160,
      bandSpread: 1.1,
      ribbonWidth: 14,
      sparkleDensity: 0.035,
      amplitude: 0.85,
      wavelength: 0.42,
      phaseSpread: 2.4,
      depth: 2.2,
      turbulence: 0.35,
      flowSpeed: 0.9,
      colorA: '#ff4fd8',
      colorB: '#a86bff',
      colorC: '#4fd0ff',
      glow: 2.1,
      sparkleSize: 2.2,
      sparkleBrightness: 2.4,
    },
  },

  {
    name: 'Filament Sphere',
    engine: ENGINE_TYPES.FLUX,
    badge: 'Wrapped Flow',
    description: 'The same travelling wave wrapped pole to pole, so the strands become a slowly turning ball of streaming threads.',
    global: {
      exposure: 1.0,
      bloomStrength: 0.3,
      bloomRadius: 0.3,
      bloomThreshold: 0.32,
      autoRotateSpeed: 0.0,
      background: '#03040a',
    },
    params: {
      layout: 'orb',
      strands: 34,
      segments: 180,
      twist: 0.9,
      sparkleDensity: 0.05,
      amplitude: 1.1,
      wavelength: 0.55,
      phaseSpread: 1.6,
      turbulence: 0.55,
      flowSpeed: 0.55,
      colorA: '#ff5ec4',
      colorB: '#8f7bff',
      colorC: '#5ff0ff',
      glow: 1.9,
      sparkleSize: 2.6,
      sparkleBrightness: 2.8,
    },
  },

  // SOFT / STATEFUL ENGINE PRESETS
  {
    name: 'Stillwater Listener',
    engine: ENGINE_TYPES.AQUEOUS,
    badge: 'Calm Refractive Body',
    description: 'A weighty teal body with slow migrating contours and a warm light held beneath the surface.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.24,
      bloomRadius: 0.32,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0,
      background: '#01080b',
    },
    params: {
      detail: 5,
      radius: 1.5,
      displaceOctaves: 3,
      displaceAmount: 0.18,
      displaceScale: 1.4,
      breatheSpeed: 0.35,
      breatheAmp: 0.04,
      driftSpeed: 0.25,
      pulseDeform: 0.25,
      bodyColor: '#2dd4bf',
      coreColor: '#ffed00',
      transmission: 0.85,
      thickness: 1.2,
      ior: 1.42,
      roughness: 0.15,
      coreIntensity: 1.6,
      fresnelPower: 2.5,
    },
  },
  {
    name: 'Blue Current',
    engine: ENGINE_TYPES.CURL_DRIFT,
    badge: 'Directed Stream',
    description: 'Clear cyan-to-violet currents braid around a quiet shell with an unmistakable direction of travel.',
    global: {
      exposure: 1,
      bloomStrength: 0.2,
      bloomRadius: 0.25,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: '#01040a',
    },
    params: {
      streamCount: 64,
      trailLength: 48,
      shellRadius: 1.6,
      lineWidth: 1.6,
      fieldScale: 0.9,
      fieldEvolveSpeed: 0.12,
      flowSpeed: 0.8,
      shellBinding: 0.7,
      swirl: 0.3,
      lifetimeJitter: 0.5,
      headColor: '#00f2fe',
      tailColor: '#a855f7',
      glowIntensity: 1.3,
      tailFade: 0.7,
    },
  },
  {
    name: 'Deliberation Cloud',
    engine: ENGINE_TYPES.MURMURATION,
    badge: 'Gathering Thought',
    description: 'A restrained swarm repeatedly gathers and loosens without collapsing into visual noise.',
    global: {
      exposure: 1,
      bloomStrength: 0.18,
      bloomRadius: 0.24,
      bloomThreshold: 0.42,
      autoRotateSpeed: 0,
      background: '#020306',
    },
    params: {
      agentCount: 256,
      shellRadius: 1.7,
      trailLength: 8,
      pointSize: 2,
      cohesion: 0.4,
      separation: 0.55,
      alignment: 0.35,
      neighbourRadius: 0.55,
      attractorPull: 0.5,
      shellBinding: 0.8,
      agentSpeed: 1,
      damping: 0.96,
      coreColor: '#ffed00',
      edgeColor: '#00f2fe',
      glowIntensity: 1.4,
      trailFade: 0.6,
    },
  },
  {
    name: 'Signal Lattice',
    engine: ENGINE_TYPES.FILAMENT,
    badge: 'Elastic Propagation',
    description: 'A dark geodesic web whose warm signal light reveals waves crossing and reflecting through the structure.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.24,
      bloomRadius: 0.28,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0,
      background: '#030306',
    },
    params: {
      subdivision: 2,
      radius: 1.6,
      nodeSize: 0.03,
      lineWidth: 1.8,
      stiffness: 0.35,
      damping: 0.94,
      tether: 0.06,
      pulseStrength: 0.5,
      idleExcitation: 0.05,
      waveSpeed: 0.4,
      displacementGlow: 1.5,
      restColor: '#1e293b',
      activeColor: '#ffed00',
      nodeColor: '#ffffff',
    },
  },

  // ORIGINAL ENGINE PRESETS
  {
    name: 'Opaline Bloom',
    engine: ENGINE_TYPES.PRISM_BLOOM,
    badge: 'Iridescent Flora',
    description: 'A composed sphere of opaline petals opening in a slow wave around a warm porcelain core.',
    global: {
      exposure: 1,
      bloomStrength: 0.2,
      bloomRadius: 0.3,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: '#07030b',
    },
    params: {
      petalCount: 48,
      petalLength: 1.32,
      petalWidth: 0.52,
      coreRadius: 0.83,
      bloom: 0.58,
      fold: 0.78,
      waveStrength: 0.42,
      breatheAmp: 0.14,
      breatheSpeed: 0.72,
      innerColor: '#f8c8ff',
      outerColor: '#58c9ff',
      edgeColor: '#fff4cb',
      iridescence: 0.72,
      glow: 1.28,
    },
  },
  {
    name: 'Polar Veil',
    engine: ENGINE_TYPES.CORONA_VEIL,
    badge: 'Quiet Aurora',
    description: 'Fine teal and violet membranes roll over a near-black core like a contained polar light.',
    global: {
      exposure: 1.05,
      bloomStrength: 0.16,
      bloomRadius: 0.26,
      bloomThreshold: 0.44,
      autoRotateSpeed: 0,
      background: '#010408',
    },
    params: {
      veilCount: 8,
      detail: 80,
      coreRadius: 1.62,
      veilSpread: 0.24,
      twist: 0.68,
      waveAmp: 0.055,
      breatheAmp: 0.025,
      driftSpeed: 0.16,
      waveSpeed: 0.48,
      coreColor: '#02040a',
      veilColor: '#62d8d2',
      accentColor: '#b9a7ff',
      opacity: 0.25,
      edgeGlow: 1.25,
    },
  },
  {
    name: 'First Contact',
    engine: ENGINE_TYPES.ECHO_RINGS,
    badge: 'Remembered Signal',
    description: 'Cold wavefronts cross on tilted planes and retain each pulse long enough to feel acknowledged.',
    global: {
      exposure: 1,
      bloomStrength: 0.22,
      bloomRadius: 0.3,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0,
      background: '#010509',
    },
    params: {
      ringCount: 7,
      segments: 128,
      radius: 1.72,
      lineWidth: 2.4,
      tiltSpread: 0.92,
      ringSpacing: 0.82,
      idleWave: 0.42,
      pulseStrength: 1.35,
      driftSpeed: 0.14,
      propagationSpeed: 1,
      baseColor: '#123039',
      echoColor: '#42d9ff',
      coreColor: '#e8fdff',
      glow: 1.65,
    },
  },
  {
    name: 'Luminous Root',
    engine: ENGINE_TYPES.MYCELIUM,
    badge: 'Living Network',
    description: 'A pale organic network carries warm signals outward through restrained, asymmetric branches.',
    global: {
      exposure: 1,
      bloomStrength: 0.18,
      bloomRadius: 0.28,
      bloomThreshold: 0.42,
      autoRotateSpeed: 0,
      background: '#020806',
    },
    params: {
      branchDepth: 5,
      branching: 2,
      radius: 2.1,
      lineWidth: 1.35,
      curl: 0.42,
      growth: 1,
      reach: 0.45,
      pulseStrength: 0.8,
      crawlSpeed: 0.32,
      pulseSpeed: 1.35,
      rootColor: '#b7ffe1',
      tipColor: '#287d78',
      signalColor: '#f4ffd2',
      glow: 1.55,
      packetSize: 2.4,
    },
  },
];
