import { ENGINE_TYPES } from '../core/state.js';

export const SIMULATION_PRESETS = [
  {
    name: "Neon Voice Ribbon",
    engine: ENGINE_TYPES.FLUX,
    badge: "Travelling Wave",
    description: "A wide band of strands streaming past, fanning apart and converging into bright knots. The voice-assistant waveform read.",
    global: {
      exposure: 1,
      bloomStrength: 0.35,
      bloomRadius: 0.35,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#05010c",
    },
    params: {
      layout: "ribbon",
      strands: 28,
      segments: 160,
      bandSpread: 1.1,
      ribbonWidth: 14,
      sparkleDensity: 0.035,
      amplitude: 0.85,
      wavelength: 0.42,
      phaseSpread: 2.4,
      depth: 2.2,
      turbulence: 0.35,
      flowSpeed: 0.9,
      colorA: "#ff4fd8",
      colorB: "#a86bff",
      colorC: "#4fd0ff",
      glow: 2.1,
      sparkleSize: 2.2,
      sparkleBrightness: 2.4,
    },
  },
  {
    name: "Filament Sphere",
    engine: ENGINE_TYPES.FLUX,
    badge: "Wrapped Flow",
    description: "The same travelling wave wrapped pole to pole, so the strands become a slowly turning ball of streaming threads.",
    global: {
      exposure: 1,
      bloomStrength: 0.3,
      bloomRadius: 0.3,
      bloomThreshold: 0.32,
      autoRotateSpeed: 0,
      background: "#03040a",
    },
    params: {
      layout: "orb",
      strands: 34,
      segments: 180,
      twist: 0.9,
      sparkleDensity: 0.05,
      amplitude: 1.1,
      wavelength: 0.55,
      phaseSpread: 1.6,
      turbulence: 0.55,
      flowSpeed: 0.55,
      colorA: "#ff5ec4",
      colorB: "#8f7bff",
      colorC: "#5ff0ff",
      glow: 1.9,
      sparkleSize: 2.6,
      sparkleBrightness: 2.8,
    },
  },
  {
    name: "Stillwater Listener",
    engine: ENGINE_TYPES.AQUEOUS,
    badge: "Calm Refractive Body",
    description: "A weighty teal body with slow migrating contours and a warm light held beneath the surface.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.24,
      bloomRadius: 0.32,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0,
      background: "#01080b",
    },
    params: {
      detail: 5,
      radius: 1.5,
      displaceOctaves: 3,
      displaceAmount: 0.18,
      displaceScale: 1.4,
      breatheSpeed: 0.35,
      breatheAmp: 0.04,
      driftSpeed: 0.25,
      pulseDeform: 0.25,
      bodyColor: "#2dd4bf",
      coreColor: "#ffed00",
      transmission: 0.85,
      thickness: 1.2,
      ior: 1.42,
      roughness: 0.15,
      coreIntensity: 1.6,
      fresnelPower: 2.5,
    },
  },
  {
    name: "Blue Current",
    engine: ENGINE_TYPES.CURL_DRIFT,
    badge: "Directed Stream",
    description: "Clear cyan-to-violet currents braid around a quiet shell with an unmistakable direction of travel.",
    global: {
      exposure: 1,
      bloomStrength: 0.2,
      bloomRadius: 0.25,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#01040a",
    },
    params: {
      streamCount: 64,
      trailLength: 48,
      shellRadius: 1.6,
      lineWidth: 1.6,
      fieldScale: 0.9,
      fieldEvolveSpeed: 0.12,
      flowSpeed: 0.8,
      shellBinding: 0.7,
      swirl: 0.3,
      lifetimeJitter: 0.5,
      coverage: 1,
      coverageCenter: 0,
      headColor: "#00f2fe",
      midColor: "#4f8cff",
      tailColor: "#a855f7",
      glowIntensity: 1.3,
      tailFade: 0.7,
    },
  },
  {
    name: "Deliberation Cloud",
    engine: ENGINE_TYPES.MURMURATION,
    badge: "Gathering Thought",
    description: "A restrained swarm repeatedly gathers and loosens without collapsing into visual noise.",
    global: {
      exposure: 1,
      bloomStrength: 0.18,
      bloomRadius: 0.24,
      bloomThreshold: 0.42,
      autoRotateSpeed: 0,
      background: "#020306",
    },
    params: {
      agentCount: 256,
      shellRadius: 1.7,
      trailLength: 8,
      pointSize: 2,
      cohesion: 0.4,
      separation: 0.55,
      alignment: 0.35,
      neighbourRadius: 0.55,
      attractorPull: 0.5,
      shellBinding: 0.8,
      agentSpeed: 1,
      damping: 0.96,
      coreColor: "#ffed00",
      edgeColor: "#00f2fe",
      glowIntensity: 1.4,
      trailFade: 0.6,
    },
  },
  {
    name: "Signal Lattice",
    engine: ENGINE_TYPES.FILAMENT,
    badge: "Elastic Propagation",
    description: "A dark geodesic web whose warm signal light reveals waves crossing and reflecting through the structure.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.24,
      bloomRadius: 0.28,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0,
      background: "#030306",
    },
    params: {
      subdivision: 2,
      radius: 1.6,
      nodeSize: 0.03,
      lineWidth: 1.8,
      stiffness: 0.35,
      damping: 0.94,
      tether: 0.06,
      pulseStrength: 0.5,
      idleExcitation: 0.05,
      waveSpeed: 0.4,
      displacementGlow: 1.5,
      restColor: "#1e293b",
      activeColor: "#ffed00",
      nodeColor: "#ffffff",
    },
  }
];
