import { ENGINE_TYPES } from '../core/state.js';

export const BODIES_PRESETS = [
  {
    name: "Opaline Bloom",
    engine: ENGINE_TYPES.PRISM_BLOOM,
    badge: "Iridescent Flora",
    description: "A composed sphere of opaline petals opening in a slow wave around a warm porcelain core.",
    global: {
      exposure: 1,
      bloomStrength: 0.2,
      bloomRadius: 0.3,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#07030b",
    },
    params: {
      petalCount: 48,
      petalLength: 1.32,
      petalWidth: 0.52,
      coreRadius: 0.83,
      bloom: 0.58,
      fold: 0.78,
      waveStrength: 0.42,
      breatheAmp: 0.14,
      breatheSpeed: 0.72,
      innerColor: "#f8c8ff",
      outerColor: "#58c9ff",
      edgeColor: "#fff4cb",
      iridescence: 0.72,
      glow: 1.28,
    },
  },
  {
    name: "Closed Bud",
    engine: ENGINE_TYPES.PRISM_BLOOM,
    badge: "Held Petal",
    description: "A tight rose-gold bud that barely unfurls, with a slow breath instead of a wide opening wave.",
    global: {
      exposure: 1.02,
      bloomStrength: 0.16,
      bloomRadius: 0.26,
      bloomThreshold: 0.44,
      autoRotateSpeed: 0,
      background: "#0a0406",
    },
    params: {
      petalCount: 36,
      petalLength: 1.12,
      petalWidth: 0.46,
      coreRadius: 0.86,
      bloom: 0.22,
      fold: 0.96,
      waveStrength: 0.18,
      breatheAmp: 0.08,
      breatheSpeed: 0.42,
      innerColor: "#ffd0c8",
      outerColor: "#c45c7a",
      edgeColor: "#ffe7b0",
      iridescence: 0.45,
      glow: 1.12,
    },
  },
  {
    name: "Citrine Corona",
    engine: ENGINE_TYPES.PRISM_BLOOM,
    badge: "Open Crystal",
    description: "A wide flare of thin gold petals around a smaller core, opening hard enough to read as a sunburst.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.28,
      bloomRadius: 0.34,
      bloomThreshold: 0.34,
      autoRotateSpeed: 0,
      background: "#0c0702",
    },
    params: {
      petalCount: 72,
      petalLength: 1.4,
      petalWidth: 0.4,
      coreRadius: 0.72,
      bloom: 0.92,
      fold: 0.42,
      waveStrength: 0.58,
      breatheAmp: 0.2,
      breatheSpeed: 0.96,
      innerColor: "#fff4d4",
      outerColor: "#ff9f1c",
      edgeColor: "#fff8e7",
      iridescence: 0.55,
      glow: 1.55,
    },
  },
  {
    name: "Night Iris",
    engine: ENGINE_TYPES.PRISM_BLOOM,
    badge: "Dark Jewel",
    description: "Violet petals with ice-blue edges, high iridescence, and a slower opening that stays nocturnal.",
    global: {
      exposure: 0.98,
      bloomStrength: 0.22,
      bloomRadius: 0.3,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#04020c",
    },
    params: {
      petalCount: 60,
      petalLength: 1.28,
      petalWidth: 0.58,
      coreRadius: 0.8,
      bloom: 0.48,
      fold: 0.82,
      waveStrength: 0.28,
      breatheAmp: 0.1,
      breatheSpeed: 0.38,
      innerColor: "#e0d4ff",
      outerColor: "#6d5efc",
      edgeColor: "#7dd3fc",
      iridescence: 0.92,
      glow: 1.36,
    },
  },
  {
    name: "Polar Veil",
    engine: ENGINE_TYPES.CORONA_VEIL,
    badge: "Quiet Aurora",
    description: "Fine teal and violet membranes roll over a near-black core like a contained polar light.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.16,
      bloomRadius: 0.26,
      bloomThreshold: 0.44,
      autoRotateSpeed: 0,
      background: "#010408",
    },
    params: {
      veilCount: 8,
      detail: 80,
      coreRadius: 1.62,
      veilShape: "bands",
      veilSurface: "aurora",
      veilSpread: 0.24,
      twist: 0.68,
      waveAmp: 0.055,
      breatheAmp: 0.025,
      driftSpeed: 0.16,
      waveSpeed: 0.48,
      coreColor: "#02040a",
      veilColor: "#62d8d2",
      accentColor: "#b9a7ff",
      opacity: 0.25,
      edgeGlow: 1.25,
    },
  },
  {
    name: "Solar Storm",
    engine: ENGINE_TYPES.CORONA_VEIL,
    badge: "Hot Membrane",
    description: "More layers, more twist, and an orange-red veil so the corona reads as weather instead of a quiet light.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.24,
      bloomRadius: 0.32,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0,
      background: "#0a0402",
    },
    params: {
      veilCount: 12,
      detail: 96,
      coreRadius: 1.55,
      veilShape: "loops",
      veilSurface: "aurora",
      veilSpread: 0.29,
      twist: 1.02,
      waveAmp: 0.085,
      breatheAmp: 0.045,
      driftSpeed: 0.26,
      waveSpeed: 0.68,
      coreColor: "#140804",
      veilColor: "#fb923c",
      accentColor: "#fde68a",
      opacity: 0.3,
      edgeGlow: 1.6,
    },
  },
  {
    name: "Quiet Dusk",
    engine: ENGINE_TYPES.CORONA_VEIL,
    badge: "Soft Membrane",
    description: "Fewer rose membranes, slower drift, and a dimmer core so the veil barely announces itself.",
    global: {
      exposure: 0.98,
      bloomStrength: 0.14,
      bloomRadius: 0.24,
      bloomThreshold: 0.48,
      autoRotateSpeed: 0,
      background: "#08040a",
    },
    params: {
      veilCount: 5,
      detail: 64,
      coreRadius: 1.7,
      veilShape: "bands",
      veilSurface: "silk",
      veilSpread: 0.16,
      twist: 0.32,
      waveAmp: 0.025,
      breatheAmp: 0.015,
      driftSpeed: 0.08,
      waveSpeed: 0.28,
      coreColor: "#0a0610",
      veilColor: "#f9a8d4",
      accentColor: "#c4b5fd",
      opacity: 0.18,
      edgeGlow: 0.9,
    },
  },
  {
    name: "Ion Crown",
    engine: ENGINE_TYPES.CORONA_VEIL,
    badge: "Electric Membrane",
    description: "Lime and magenta sheets with a high twist, so the aurora reads as charge rather than mist.",
    global: {
      exposure: 1.06,
      bloomStrength: 0.2,
      bloomRadius: 0.28,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#02080a",
    },
    params: {
      veilCount: 10,
      detail: 80,
      coreRadius: 1.58,
      veilShape: "loops",
      veilSurface: "lace",
      veilSpread: 0.27,
      twist: 1.08,
      waveAmp: 0.07,
      breatheAmp: 0.03,
      driftSpeed: 0.2,
      waveSpeed: 0.58,
      coreColor: "#02080c",
      veilColor: "#86efac",
      accentColor: "#e879f9",
      opacity: 0.28,
      edgeGlow: 1.5,
    },
  },
  {
    name: "First Contact",
    engine: ENGINE_TYPES.ECHO_RINGS,
    badge: "Remembered Signal",
    description: "Cold wavefronts cross on tilted planes and retain each pulse long enough to feel acknowledged.",
    global: {
      exposure: 1,
      bloomStrength: 0.22,
      bloomRadius: 0.3,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0,
      background: "#010509",
    },
    params: {
      ringCount: 7,
      segments: 128,
      radius: 1.72,
      lineWidth: 2.4,
      tiltSpread: 0.92,
      ringSpacing: 0.82,
      idleWave: 0.42,
      pulseStrength: 1.35,
      driftSpeed: 0.14,
      propagationSpeed: 1,
      baseColor: "#123039",
      echoColor: "#42d9ff",
      coreColor: "#e8fdff",
      glow: 1.65,
    },
  },
  {
    name: "Stacked Memory",
    engine: ENGINE_TYPES.ECHO_RINGS,
    badge: "Dense Echo",
    description: "Eleven close gold rings with a slow drift, so each pulse stacks instead of flying off.",
    global: {
      exposure: 1.04,
      bloomStrength: 0.26,
      bloomRadius: 0.32,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0,
      background: "#0a0702",
    },
    params: {
      ringCount: 11,
      segments: 160,
      radius: 1.64,
      lineWidth: 1.8,
      tiltSpread: 0.42,
      ringSpacing: 0.4,
      idleWave: 0.7,
      pulseStrength: 1.7,
      driftSpeed: 0.06,
      propagationSpeed: 0.7,
      baseColor: "#2a2110",
      echoColor: "#fbbf24",
      coreColor: "#fffbeb",
      glow: 1.95,
    },
  },
  {
    name: "Sparse Ping",
    engine: ENGINE_TYPES.ECHO_RINGS,
    badge: "Thin Echo",
    description: "Three wide magenta rings on strongly tilted planes, leaving dark between each remembered pulse.",
    global: {
      exposure: 1,
      bloomStrength: 0.18,
      bloomRadius: 0.26,
      bloomThreshold: 0.44,
      autoRotateSpeed: 0,
      background: "#08020a",
    },
    params: {
      ringCount: 3,
      segments: 96,
      radius: 1.86,
      lineWidth: 3.4,
      tiltSpread: 1.38,
      ringSpacing: 1.2,
      idleWave: 0.18,
      pulseStrength: 1.9,
      driftSpeed: -0.22,
      propagationSpeed: 1.2,
      baseColor: "#1a1024",
      echoColor: "#e879f9",
      coreColor: "#fce7f3",
      glow: 2.2,
    },
  },
  {
    name: "Hot Reply",
    engine: ENGINE_TYPES.ECHO_RINGS,
    badge: "Fast Echo",
    description: "Thick orange wavefronts that propagate quickly and glow hard enough to read as an answer, not a memory.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.3,
      bloomRadius: 0.34,
      bloomThreshold: 0.32,
      autoRotateSpeed: 0,
      background: "#0a0402",
    },
    params: {
      ringCount: 5,
      segments: 128,
      radius: 1.72,
      lineWidth: 4.2,
      tiltSpread: 0.7,
      ringSpacing: 0.95,
      idleWave: 0.55,
      pulseStrength: 2.05,
      driftSpeed: 0.28,
      propagationSpeed: 1.4,
      baseColor: "#3b1c12",
      echoColor: "#fb7185",
      coreColor: "#fff7ed",
      glow: 2.45,
    },
  },
  {
    name: "Polished Mercury",
    engine: ENGINE_TYPES.CHROMASPHERE,
    badge: "Liquid Chrome",
    description: "A heavy mirrored body under four softboxes, its surface folding slowly enough to read as liquid rather than as noise.",
    global: {
      exposure: 1,
      bloomStrength: 0.12,
      bloomRadius: 0.22,
      bloomThreshold: 0.55,
      autoRotateSpeed: 0.25,
      background: "#05070c",
    },
    params: {
      detail: 5,
      rippleOctaves: 3,
      barCount: 4,
      radius: 1.45,
      rippleAmount: 0.14,
      rippleScale: 1.9,
      flowSpeed: 0.3,
      spinSpeed: 0.12,
      breatheSpeed: 0.35,
      breatheAmp: 0.03,
      pulseRipple: 0.3,
      metalTint: "#dfe7ef",
      envTop: "#8ea6c8",
      barColor: "#fff6e0",
      envBottom: "#0a0d14",
      envIntensity: 1.5,
      roughness: 0.14,
      fresnelPower: 3.2,
      fresnelGain: 0.55,
      barWidth: 0.3,
    },
  },
  {
    name: "Luminous Root",
    engine: ENGINE_TYPES.CHROMASPHERE,
    badge: "Warm Chrome",
    description: "A honeyed metal orb under six studio strips, with slower ripples that read as a living root rather than a mirror ball.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.16,
      bloomRadius: 0.26,
      bloomThreshold: 0.48,
      autoRotateSpeed: 0.18,
      background: "#08060c",
    },
    params: {
      detail: 5,
      rippleOctaves: 2,
      barCount: 6,
      radius: 1.55,
      rippleAmount: 0.09,
      rippleScale: 1.35,
      flowSpeed: 0.18,
      spinSpeed: 0.08,
      breatheSpeed: 0.28,
      breatheAmp: 0.045,
      pulseRipple: 0.22,
      metalTint: "#e8d5b5",
      envTop: "#c4a574",
      barColor: "#ffe7a3",
      envBottom: "#120c08",
      envIntensity: 1.85,
      roughness: 0.2,
      fresnelPower: 2.6,
      fresnelGain: 0.7,
      barWidth: 0.22,
    },
  },
  {
    name: "Black Mirror",
    engine: ENGINE_TYPES.CHROMASPHERE,
    badge: "Dark Chrome",
    description: "A darker, quieter metal under two cold strips, with a hard silhouette and almost no ripple.",
    global: {
      exposure: 0.92,
      bloomStrength: 0.08,
      bloomRadius: 0.18,
      bloomThreshold: 0.62,
      autoRotateSpeed: 0.12,
      background: "#020308",
    },
    params: {
      detail: 6,
      rippleOctaves: 1,
      barCount: 2,
      radius: 1.5,
      rippleAmount: 0.04,
      rippleScale: 0.8,
      flowSpeed: 0.08,
      spinSpeed: 0.05,
      breatheSpeed: 0.16,
      breatheAmp: 0.015,
      pulseRipple: 0.12,
      metalTint: "#1e293b",
      envTop: "#64748b",
      barColor: "#e2e8f0",
      envBottom: "#020617",
      envIntensity: 1.15,
      roughness: 0.08,
      fresnelPower: 4.4,
      fresnelGain: 0.9,
      barWidth: 0.14,
    },
  },
  {
    name: "Copper Studio",
    engine: ENGINE_TYPES.CHROMASPHERE,
    badge: "Warm Metal",
    description: "Copper tint, eight warm softboxes, and a livelier surface so the studio lights crawl instead of sitting still.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.18,
      bloomRadius: 0.28,
      bloomThreshold: 0.46,
      autoRotateSpeed: 0.32,
      background: "#0a0504",
    },
    params: {
      detail: 4,
      rippleOctaves: 4,
      barCount: 8,
      radius: 1.4,
      rippleAmount: 0.22,
      rippleScale: 2.8,
      flowSpeed: 0.55,
      spinSpeed: 0.22,
      breatheSpeed: 0.5,
      breatheAmp: 0.06,
      pulseRipple: 0.42,
      metalTint: "#d97706",
      envTop: "#fdba74",
      barColor: "#fff7ed",
      envBottom: "#1c0a06",
      envIntensity: 2.1,
      roughness: 0.28,
      fresnelPower: 2.4,
      fresnelGain: 0.45,
      barWidth: 0.18,
    },
  },
  {
    name: "Vocal Resonator",
    engine: ENGINE_TYPES.VOCALIS,
    badge: "Phonetic Diaphragm",
    description: "Acoustic diaphragm rings dilate in harmonic resonance with voice pulses around a glowing glottal core.",
    global: {
      exposure: 1,
      bloomStrength: 0.22,
      bloomRadius: 0.26,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0.1,
      background: "#02050b",
    },
    params: {
      ringCount: 6,
      ringLayout: "circle",
      baseRadius: 1.45,
      diaphragmDepth: 0.6,
      lineWidth: 2.4,
      apertureSize: 0.35,
      vocalRipple: 0.14,
      formantHarmonics: 3,
      formantGain: 1.2,
      breatheAmp: 0.04,
      articulationRate: 1.2,
      plosiveSurge: 1.4,
      coreColor: "#ffffff",
      diaphragmColor: "#00f2fe",
      formantColor: "#a855f7",
      glowIntensity: 1.8,
      glottisDarkness: 0.8,
      slitAngle: 0,
      slitLength: 0.7,
    },
  },
  {
    name: "Phonetic Diaphragm",
    engine: ENGINE_TYPES.VOCALIS,
    badge: "Glottal Articulation",
    description: "Deep amber and crimson acoustic ribbons expanding and contracting with rapid vowel articulation.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.25,
      bloomRadius: 0.3,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0.12,
      background: "#080204",
    },
    params: {
      ringCount: 8,
      ringLayout: "circle",
      baseRadius: 1.55,
      diaphragmDepth: 0.75,
      lineWidth: 2.8,
      apertureSize: 0.42,
      vocalRipple: 0.22,
      formantHarmonics: 4,
      formantGain: 1.5,
      breatheAmp: 0.06,
      articulationRate: 1.6,
      plosiveSurge: 1.8,
      coreColor: "#ffed00",
      diaphragmColor: "#ff0055",
      formantColor: "#f59e0b",
      glowIntensity: 2.1,
      glottisDarkness: 0.85,
      slitAngle: 0,
      slitLength: 0.75,
    },
  },
  {
    name: "Iris Speaker",
    engine: ENGINE_TYPES.VOCALIS,
    badge: "Bladed Diaphragm",
    description: "Six-blade iris rings around a bright glottis, so the aperture reads as a camera shutter speaking.",
    global: {
      exposure: 1.04,
      bloomStrength: 0.24,
      bloomRadius: 0.28,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0.08,
      background: "#02060c",
    },
    params: {
      ringCount: 8,
      ringLayout: "iris",
      baseRadius: 1.5,
      diaphragmDepth: 0.45,
      lineWidth: 2.2,
      apertureSize: 0.4,
      vocalRipple: 0.12,
      formantHarmonics: 3,
      formantGain: 1.35,
      breatheAmp: 0.035,
      articulationRate: 1.1,
      plosiveSurge: 1.6,
      coreColor: "#e0f2fe",
      diaphragmColor: "#38bdf8",
      formantColor: "#a78bfa",
      glowIntensity: 1.9,
      glottisDarkness: 0.85,
      slitAngle: 0,
      slitLength: 0.6,
    },
  },
  {
    name: "Rounded Vowels",
    engine: ENGINE_TYPES.VOCALIS,
    badge: "Mouth Aperture",
    description: "A short, round opening — the lips of an 'o' — inside flattened elliptical rings, with a slow cadence and a warm formant crest.",
    global: {
      exposure: 1.06,
      bloomStrength: 0.22,
      bloomRadius: 0.3,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0.06,
      background: "#0a0406",
    },
    params: {
      ringCount: 6,
      ringLayout: "ellipse",
      baseRadius: 1.65,
      diaphragmDepth: 0.35,
      lineWidth: 2.6,
      apertureSize: 0.8,
      vocalRipple: 0.08,
      formantHarmonics: 2,
      formantGain: 1.1,
      breatheAmp: 0.05,
      articulationRate: 0.85,
      plosiveSurge: 1.3,
      coreColor: "#fff7ed",
      diaphragmColor: "#fb7185",
      formantColor: "#fbbf24",
      glowIntensity: 1.7,
      glottisDarkness: 0.75,
      slitAngle: 0,
      slitLength: 0.5,
    },
  },
  {
    name: "Orbital Voice",
    engine: ENGINE_TYPES.VOCALIS,
    badge: "Latitudinal Diaphragm",
    description: "Latitudes wrap a leaning globe around upright vocal folds, so speech ripples across a sphere instead of a flat diaphragm.",
    global: {
      exposure: 1.02,
      bloomStrength: 0.2,
      bloomRadius: 0.26,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0.14,
      background: "#030208",
    },
    params: {
      ringCount: 10,
      ringLayout: "globe",
      baseRadius: 1.4,
      diaphragmDepth: 0.6,
      lineWidth: 1.8,
      apertureSize: 0.4,
      vocalRipple: 0.035,
      formantHarmonics: 4,
      formantGain: 1.45,
      breatheAmp: 0.03,
      articulationRate: 1.35,
      plosiveSurge: 1.5,
      coreColor: "#ffffff",
      diaphragmColor: "#67e8f9",
      formantColor: "#c084fc",
      glowIntensity: 1.85,
      glottisDarkness: 0.9,
      slitAngle: 90,
      slitLength: 0.85,
    },
  },
  {
    name: "Siri Pearl",
    engine: ENGINE_TYPES.AETHERIA,
    badge: "Chromatic Luminescence",
    description: "Silky, translucent fluid sphere with undulating surface wavelets, floating internal silk caustics, and a chromatic dispersion halo.",
    global: {
      exposure: 1,
      bloomStrength: 0.24,
      bloomRadius: 0.28,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0.1,
      background: "#02040a",
    },
    params: {
      sphereRadius: 1.55,
      detail: 64,
      causticRibbons: 3,
      fluidSpeed: 0.45,
      fluidWaveAmp: 0.12,
      breatheAmp: 0.04,
      causticSwirl: 0.6,
      pulseGlow: 1.5,
      color1: "#00f2fe",
      color2: "#a855f7",
      color3: "#ff4fd8",
      rimColor: "#ffed00",
      iridescence: 0.85,
      glowIntensity: 1.8,
    },
  },
  {
    name: "Iridescent Aurora",
    engine: ENGINE_TYPES.AETHERIA,
    badge: "Prismatic Fluid",
    description: "Emerald mint, peach champagne, and celestial azure chromatic fluid breathing gently under soft subsurface diffusion.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.26,
      bloomRadius: 0.3,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0.12,
      background: "#010807",
    },
    params: {
      sphereRadius: 1.6,
      detail: 64,
      causticRibbons: 4,
      fluidSpeed: 0.5,
      fluidWaveAmp: 0.16,
      breatheAmp: 0.05,
      causticSwirl: 0.75,
      pulseGlow: 1.7,
      color1: "#34d399",
      color2: "#38bdf8",
      color3: "#fb923c",
      rimColor: "#fef08a",
      iridescence: 1.1,
      glowIntensity: 2,
    },
  },
  {
    name: "Quantum Superposition",
    engine: ENGINE_TYPES.SUPERPOSITION,
    badge: "D-Orbital Clover",
    description: "Hydrogenic probability density lobes rotate with phase interference, collapsing upon observation.",
    global: {
      exposure: 1,
      bloomStrength: 0.2,
      bloomRadius: 0.26,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0.1,
      background: "#020409",
    },
    params: {
      sampleDensity: 6144,
      orbitalScale: 1.45,
      nucleusRadius: 0.38,
      stateMode: "d_orbital",
      pointSize: 2.8,
      coherence: 0.85,
      waveExcursion: 0.45,
      breatheAmp: 0.04,
      collapseStrength: 1.4,
      phaseRate: 1.1,
      psiColorA: "#38bdf8",
      psiColorB: "#f43f5e",
      nodalColor: "#e0f2fe",
      glowIntensity: 1.8,
    },
  },
  {
    name: "Chiral Wavepacket",
    engine: ENGINE_TYPES.SUPERPOSITION,
    badge: "Vortex Orbital",
    description: "Helical orbital angular momentum rings with spinning phase nodes and high quantum coherence.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.22,
      bloomRadius: 0.3,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0.14,
      background: "#030208",
    },
    params: {
      sampleDensity: 9216,
      orbitalScale: 1.55,
      nucleusRadius: 0.35,
      stateMode: "chiral_vortex",
      pointSize: 2.5,
      coherence: 0.92,
      waveExcursion: 0.6,
      breatheAmp: 0.05,
      collapseStrength: 1.6,
      phaseRate: 1.4,
      psiColorA: "#00f2fe",
      psiColorB: "#a855f7",
      nodalColor: "#ffffff",
      glowIntensity: 2,
    },
  },
  {
    name: "Gemini Harmonic",
    engine: ENGINE_TYPES.SYNTHESIS,
    badge: "4-Color Gravitational Fusion",
    description: "Four harmonious luminous fluid bodies in celestial figure-8 orbit, organically fusing with liquid bridges and stardust.",
    global: {
      exposure: 1,
      bloomStrength: 0.22,
      bloomRadius: 0.26,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0.1,
      background: "#020409",
    },
    params: {
      envelopeRadius: 1.6,
      coreRadius: 0.38,
      filamentCount: 6,
      stardustDensity: 64,
      orbitSpread: 0.75,
      orbitSpeed: 0.55,
      fusionTension: 0.65,
      breatheAmp: 0.035,
      coalesceSurge: 1.4,
      color1: "#4285f4",
      color2: "#ea4335",
      color3: "#fbbc05",
      color4: "#34a853",
      veilColor: "#1e1b4b",
      glowIntensity: 1.8,
    },
  },
  {
    name: "Celestial Symbiosis",
    engine: ENGINE_TYPES.SYNTHESIS,
    badge: "Harmonic Modal Ballet",
    description: "Deep sapphire, lavender, rose, and amber fluid lobes linked by glowing gravitational filaments and orbiting micro-sparkles.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.25,
      bloomRadius: 0.3,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0.12,
      background: "#05020a",
    },
    params: {
      envelopeRadius: 1.65,
      coreRadius: 0.42,
      filamentCount: 6,
      stardustDensity: 128,
      orbitSpread: 0.85,
      orbitSpeed: 0.65,
      fusionTension: 0.8,
      breatheAmp: 0.045,
      coalesceSurge: 1.6,
      color1: "#38bdf8",
      color2: "#c084fc",
      color3: "#f43f5e",
      color4: "#fbbf24",
      veilColor: "#312e81",
      glowIntensity: 2.1,
    },
  },
  {
    name: "Magnetic Nebula Oval",
    engine: ENGINE_TYPES.FERRO_TRAILS,
    badge: "Prolate Magnetic Orb & Trails",
    description: "An elongated prolate oval ferrofluid core pulsating with electric cyan magnetic peaks, enveloped in curving neon azure and violet arc trails.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.24,
      bloomRadius: 0.28,
      bloomThreshold: 0.35,
      autoRotateSpeed: 0.12,
      background: "#020308",
    },
    params: {
      ovalRatio: 1.25,
      coreRadius: 1.35,
      trailCount: 12,
      trailDetail: 90,
      particleMotes: 64,
      arcCurvature: 0.85,
      trailSweepSpeed: 0.65,
      magneticSpikes: 0.16,
      spikeFrequency: 3.2,
      fluidViscosity: 0.9,
      breatheAmp: 0.035,
      pulseSurge: 1.5,
      colorLiquid: "#0b1021",
      colorCrest: "#00f0ff",
      colorTrail1: "#38bdf8",
      colorTrail2: "#a855f7",
      colorCore: "#ffffff",
      glowIntensity: 1.8,
    },
  },
  {
    name: "Obsidian Solar Arc",
    engine: ENGINE_TYPES.FERRO_TRAILS,
    badge: "Spherical Ferrofluid Dynamo",
    description: "A spherical obsidian liquid sphere with molten amber and gold magnetic crests, bound by high-curvature ruby arc trails and dense magnetic motes.",
    global: {
      exposure: 1,
      bloomStrength: 0.26,
      bloomRadius: 0.3,
      bloomThreshold: 0.32,
      autoRotateSpeed: 0.15,
      background: "#080302",
    },
    params: {
      ovalRatio: 1,
      coreRadius: 1.4,
      trailCount: 18,
      trailDetail: 90,
      particleMotes: 128,
      arcCurvature: 1.15,
      trailSweepSpeed: 0.8,
      magneticSpikes: 0.24,
      spikeFrequency: 3.8,
      fluidViscosity: 1.1,
      breatheAmp: 0.045,
      pulseSurge: 1.8,
      colorLiquid: "#180a06",
      colorCrest: "#ff9900",
      colorTrail1: "#ff4400",
      colorTrail2: "#ffcc00",
      colorCore: "#ffffff",
      glowIntensity: 2.1,
    },
  }
];
