import { ENGINE_TYPES } from '../core/state.js';

// The dome family: scrollwork, refracted rings, nacre bands, toy bricks,
// quantized plasma, packing beads and the radar mosaic. Grouped here because
// analytic.js is at the file-size limit.

export const DOMES_PRESETS = [
  {
    name: "Gilded Scrollwork",
    engine: ENGINE_TYPES.SCROLLDOME,
    badge: "Ornate Canon",
    description: "Gold filigree inked over midnight blue — the classic engraved-dome look.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.4,
      background: "#050409",
    },
    params: {
      color1: "'#ffd166'",
      color2: "'#0b1026'",
      rimColor: "'#fef3c7'",
      gain: 1.0,
      rim: 0.35,
      light: 0.9,
      haloStrength: 0.15,
      radius: 2.15,
      edgeFade: 0.18,
      patternScale: 5.2,
      patternZoom: 2.4,
      swirlAmp: 2.3,
      warpFreq: 2.1,
      lineClamp: 0.09,
      swell: 0.05,
      swirlRate: 0.16,
      counterSpin: -0.1,
      breatheRate: 0.4,
    },
  },
  {
    name: "Midnight Etching",
    engine: ENGINE_TYPES.SCROLLDOME,
    badge: "Silver Line",
    description: "Silver scrollwork on deep indigo — slower roll, finer lines.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.28,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.3,
      background: "#02030a",
    },
    params: {
      color1: "#dbe4ff",
      color2: "#0a0f2e",
      rimColor: "'#fef3c7'",
      gain: 1.0,
      rim: 0.35,
      light: 0.9,
      haloStrength: 0.15,
      radius: 2.15,
      edgeFade: 0.18,
      patternScale: 5.2,
      patternZoom: 2.4,
      swirlAmp: 2.3,
      warpFreq: 2.1,
      lineClamp: 0.07,
      swell: 0.05,
      swirlRate: 0.1,
      counterSpin: -0.1,
      breatheRate: 0.4,
    },
  },
  {
    name: "Abalone Sheen",
    engine: ENGINE_TYPES.NACRE,
    badge: "Shell Canon",
    description: "Teal-to-cream contour bands boiling gently — the abalone classic.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.35,
      background: "#030711",
    },
    params: {
      colorDeep: "'#0d1430'",
      colorLow: "'#2fb8c6'",
      colorCrest: "'#fff1de'",
      colorSheen: "'#bfe4ff'",
      irid: 0.7,
      irisScale: 0.32,
      split: 0.1,
      gain: 1.1,
      contrast: 1.15,
      light: 0.75,
      rim: 0.5,
      haloStrength: 0.0,
      radius: 2.15,
      edgeFade: 0.18,
      octaves: 4,
      bandScale: 5.5,
      bandWidth: 0.2,
      warpAmp: 1.0,
      beat: 0.0,
      viewShift: 1.34,
      boilRate: 0.25,
      flowRate: 0.3,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Ivory Pearl",
    engine: ENGINE_TYPES.NACRE,
    badge: "Quiet Nacre",
    description: "Crest-white layers over a deep calm body — iridescence dialed to a whisper.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.3,
      background: "#05060c",
    },
    params: {
      colorDeep: "'#0d1430'",
      colorLow: "#7dd3fc",
      colorCrest: "#fffbeb",
      colorSheen: "'#bfe4ff'",
      irid: 0.35,
      irisScale: 0.32,
      split: 0.1,
      gain: 1.1,
      contrast: 1.15,
      light: 0.75,
      rim: 0.5,
      haloStrength: 0.0,
      radius: 2.15,
      edgeFade: 0.18,
      octaves: 4,
      bandScale: 5.5,
      bandWidth: 0.2,
      warpAmp: 0.7,
      beat: 0.0,
      viewShift: 1.34,
      boilRate: 0.25,
      flowRate: 0.2,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Poster Plasma",
    engine: ENGINE_TYPES.QUANTPLASMA,
    badge: "Screen Canon",
    description: "Three-tone plasma on a coarse pixel grid — the retro screen alive.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.28,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.35,
      background: "#02030a",
    },
    params: {
      colorInk: "'#101426'",
      colorPaper: "'#cfe6ff'",
      light: 0.9,
      rim: 0.35,
      gain: 1.0,
      contrast: 1.1,
      haloStrength: 0.0,
      radius: 2.15,
      edgeFade: 0.18,
      cells: 140,
      levels: 3,
      patternScale: 1.5,
      plasmaAmp: 0.9,
      plasmaRate: 0.5,
      spinRate: 0.15,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Ember Dither",
    engine: ENGINE_TYPES.QUANTPLASMA,
    badge: "Chunky Heat",
    description: "Ember-orange ink on black, four tone levels, chunkier cells — a dying ember on an old display.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.3,
      background: "#060301",
    },
    params: {
      colorInk: "#030100",
      colorPaper: "#ffb347",
      light: 0.9,
      rim: 0.35,
      gain: 1.0,
      contrast: 1.1,
      haloStrength: 0.0,
      radius: 2.15,
      edgeFade: 0.18,
      cells: 90,
      levels: 4,
      patternScale: 1.5,
      plasmaAmp: 1.4,
      plasmaRate: 0.35,
      spinRate: 0.15,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Mercury Packing",
    engine: ENGINE_TYPES.BEADS,
    badge: "Bead Canon",
    description: "White beads swelling and shrinking over a near-black body — packed mercury.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.35,
      background: "#010204",
    },
    params: {
      colorDot: "'#ffffff'",
      colorDotAccent: "'#eef5ff'",
      colorBody: "'#05070c'",
      colorSheen: "'#9dbfe4'",
      beadShade: 0.55,
      floorLevel: 0.06,
      gain: 1.0,
      contrast: 1.0,
      light: 0.5,
      rim: 0.35,
      haloStrength: 0.0,
      radius: 2.15,
      edgeFade: 0.18,
      packingScale: 10.0,
      grow: 0.185,
      vary: 0.13,
      skew: 0.62,
      jitter: 0.1,
      edgeHardness: 50,
      pulseRate: 0.5,
      driftSpin: 0.12,
      counterSpin: -0.08,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Caviar Night",
    engine: ENGINE_TYPES.BEADS,
    badge: "Dense Dark",
    description: "Denser packing, faster detune — a night sky of swelling pearls.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.3,
      bloomRadius: 0.3,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.3,
      background: "#000105",
    },
    params: {
      colorDot: "'#ffffff'",
      colorDotAccent: "'#eef5ff'",
      colorBody: "'#05070c'",
      colorSheen: "'#9dbfe4'",
      beadShade: 0.55,
      floorLevel: 0.06,
      gain: 1.0,
      contrast: 1.0,
      light: 0.5,
      rim: 0.35,
      haloStrength: 0.0,
      radius: 2.15,
      edgeFade: 0.18,
      packingScale: 14.0,
      grow: 0.15,
      vary: 0.2,
      skew: 0.9,
      jitter: 0.16,
      edgeHardness: 50,
      pulseRate: 0.7,
      driftSpin: 0.12,
      counterSpin: -0.08,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Storm Watch",
    engine: ENGINE_TYPES.RADAR,
    badge: "Radar Canon",
    description: "The canonical reflectivity palette — fronts of blue, green and red sweeping the ball.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.3,
      bloomRadius: 0.28,
      bloomThreshold: 0.16,
      autoRotateSpeed: 0.35,
      background: "#040403",
    },
    params: {
      colorPaper: "'#efe9dc'",
      colorQuiet: "'#a9a9a6'",
      colorLow: "'#2e5df0'",
      colorMid: "'#22c35c'",
      colorHigh: "'#e8322a'",
      colorPeak: "'#f5d020'",
      grain: 0.1,
      light: 0.18,
      rim: 0.35,
      gain: 1.0,
      contrast: 1.0,
      haloStrength: 0.0,
      radius: 2.15,
      edgeFade: 0.18,
      cells: 34,
      dotSize: 0.36,
      vortex: 0.45,
      warpAmp: 0.3,
      loThresh: 0.12,
      hiThresh: 0.82,
      curve: 1.4,
      sparse: 0.16,
      sweepRate: 0.3,
      spinRate: 0.15,
      twinkleRate: 3.0,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Autumn Fronts",
    engine: ENGINE_TYPES.RADAR,
    badge: "Warm Classes",
    description: "A warm gradient of classes — teal rain giving way to amber and rust fronts.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.32,
      bloomRadius: 0.3,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.3,
      background: "#050402",
    },
    params: {
      colorPaper: "'#efe9dc'",
      colorQuiet: "'#a9a9a6'",
      colorLow: "#0e7490",
      colorMid: "#d97706",
      colorHigh: "#b91c1c",
      colorPeak: "'#f5d020'",
      grain: 0.1,
      light: 0.18,
      rim: 0.35,
      gain: 1.0,
      contrast: 1.0,
      haloStrength: 0.0,
      radius: 2.15,
      edgeFade: 0.18,
      cells: 34,
      dotSize: 0.36,
      vortex: 0.8,
      warpAmp: 0.3,
      loThresh: 0.12,
      hiThresh: 0.82,
      curve: 1.4,
      sparse: 0.24,
      sweepRate: 0.22,
      spinRate: 0.15,
      twinkleRate: 3.0,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
];
