import { ENGINE_TYPES } from '../core/state.js';

// The flow & filigree family: domain-warped flow, fold mandala, iridescent
// film, voronoi glass, escape-time and kaliset fractals. Grouped here because
// analytic.js is at the file-size limit.

export const FLOW_PRESETS = [
  {
    name: "Teal Undertow",
    engine: ENGINE_TYPES.SILKWARP,
    badge: "Liquid Thought",
    description: "Slow silk currents of teal and indigo drifting over a breathing sphere — an orb that reads as deep contemplation.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.4,
      background: "#04070d",
    },
    params: {
      color1: "#5eead4",
      color2: "#818cf8",
      rimColor: "#e0f2fe",
      contrast: 1.15,
      glow: 1.1,
      sheen: 0.35,
      haloStrength: 0.25,
      radius: 2.15,
      edgeFade: 0.18,
      octaves: 5,
      warpDepth: 1.25,
      warpScale: 2.4,
      driftSpin: 0.22,
      counterSpin: -0.13,
      breatheRate: 0.45,
      breatheAmp: 0.08,
    },
  },
  {
    name: "Ember Drift",
    engine: ENGINE_TYPES.SILKWARP,
    badge: "Molten Calm",
    description: "Molten gold and rose currents folding over themselves — a warmer, more deliberate idle.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.45,
      bloomRadius: 0.35,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.5,
      background: "#0c0503",
    },
    params: {
      color1: "#ffb347",
      color2: "#e05263",
      rimColor: "#ffe4b8",
      contrast: 1.35,
      glow: 1.25,
      sheen: 0.22,
      haloStrength: 0.32,
      radius: 2.15,
      edgeFade: 0.24,
      octaves: 5,
      warpDepth: 1.6,
      warpScale: 1.45,
      driftSpin: 0.16,
      counterSpin: -0.2,
      breatheRate: 0.35,
      breatheAmp: 0.11,
    },
  },
  {
    name: "Gilded Rose Window",
    engine: ENGINE_TYPES.KALEIDO,
    badge: "Eight-Fold",
    description: "An eight-fold gilded mandala of glowing contour lines, turning slowly.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.5,
      bloomRadius: 0.32,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.3,
      background: "#0a0603",
    },
    params: {
      color1: "#ffd166",
      color2: "#e879f9",
      rimColor: "#fff7ed",
      edgeGlow: 1.35,
      lineWidth: 1.1,
      grain: 0.035,
      radius: 2.2,
      symmetry: 8,
      iterations: 6,
      contraction: 0.82,
      warpTwist: 0.35,
      spinRate: 0.16,
      counterRate: -0.11,
      seedRadius: 0.62,
      zoomRate: 0.4,
      zoomDepth: 0.05,
    },
  },
  {
    name: "Frost Vault",
    engine: ENGINE_TYPES.KALEIDO,
    badge: "Crystal Cipher",
    description: "A cold twelve-fold lattice of ice-blue filaments — precise, ornate, and unhurried.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.55,
      bloomRadius: 0.3,
      bloomThreshold: 0.1,
      autoRotateSpeed: 0.25,
      background: "#020810",
    },
    params: {
      color1: "#bae6fd",
      color2: "#38bdf8",
      rimColor: "#f0f9ff",
      edgeGlow: 1.6,
      lineWidth: 0.85,
      grain: 0.05,
      radius: 2.2,
      symmetry: 12,
      iterations: 7,
      contraction: 0.74,
      warpTwist: -0.42,
      spinRate: 0.1,
      counterRate: 0.07,
      seedRadius: 0.55,
      zoomRate: 0.3,
      zoomDepth: 0.05,
    },
  },
  {
    name: "Oil Slick Reverie",
    engine: ENGINE_TYPES.VEIL,
    badge: "Iridescent Calm",
    description: "A wet sphere draped in teal-to-violet oil film — spectral colours sliding slowly under a quiet glint.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.4,
      background: "#03070c",
    },
    params: {
      color1: "#2dd4bf",
      color2: "#7c3aed",
      rimColor: "#eef2ff",
      iridStrength: 0.75,
      sheen: 0.6,
      contrast: 1.1,
      glow: 1.0,
      haloStrength: 0.22,
      radius: 2.15,
      edgeFade: 0.18,
      octaves: 5,
      filmThickness: 1.6,
      filmFrequency: 1.0,
      warpDepth: 1.35,
      driftSpin: 0.18,
      counterSpin: -0.11,
      breatheRate: 0.4,
      breatheAmp: 0.07,
    },
  },
  {
    name: "Champagne Film",
    engine: ENGINE_TYPES.VEIL,
    badge: "Gilded Wet Silk",
    description: "Warm champagne and rose interference over polished gold — a celebratory, unhurried shimmer.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.42,
      bloomRadius: 0.32,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.45,
      background: "#0b0602",
    },
    params: {
      color1: "#fbbf24",
      color2: "#fb7185",
      rimColor: "#fffbeb",
      iridStrength: 0.55,
      sheen: 0.85,
      contrast: 1.2,
      glow: 1.1,
      haloStrength: 0.28,
      radius: 2.15,
      edgeFade: 0.2,
      octaves: 5,
      filmThickness: 1.2,
      filmFrequency: 0.8,
      warpDepth: 1.1,
      driftSpin: 0.14,
      counterSpin: -0.08,
      breatheRate: 0.32,
      breatheAmp: 0.08,
    },
  },
  {
    name: "Cathedral Window",
    engine: ENGINE_TYPES.MOSAIC,
    badge: "Stained Glass",
    description: "Deep cobalt and cyan glass cells with warm gold seams — a slow wave of light crossing the window.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.45,
      bloomRadius: 0.32,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.3,
      background: "#020610",
    },
    params: {
      color1: "#1d4ed8",
      color2: "#22d3ee",
      rimColor: "#e0f2fe",
      borderColor: "#ffd166",
      borderGlow: 1.3,
      borderSoft: 0.07,
      glow: 1.0,
      haloStrength: 0.2,
      radius: 2.15,
      edgeFade: 0.18,
      cellScale: 3.2,
      tintSpread: 0.55,
      cellBreath: 0.6,
      driftSpin: 0.14,
      counterSpin: -0.09,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Pond Lattice",
    engine: ENGINE_TYPES.MOSAIC,
    badge: "Lily Glass",
    description: "Soft jade and seafoam cells with pearl seams — a quieter mosaic, like light on a still pond.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.35,
      background: "#020a08",
    },
    params: {
      color1: "#0f766e",
      color2: "#a7f3d0",
      rimColor: "#ecfeff",
      borderColor: "#fef9c3",
      borderGlow: 0.9,
      borderSoft: 0.11,
      glow: 0.95,
      haloStrength: 0.16,
      radius: 2.15,
      edgeFade: 0.22,
      cellScale: 2.4,
      tintSpread: 0.4,
      cellBreath: 0.45,
      driftSpin: 0.1,
      counterSpin: -0.06,
      breatheRate: 0.28,
      breatheAmp: 0.07,
    },
  },
  {
    name: "Gossamer Field",
    engine: ENGINE_TYPES.KALISET,
    badge: "Woven Light",
    description: "Rose threads spun over amber ground — the kaliset orbit weaving lace that renews itself without repeating.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.32,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.35,
      background: "#08030a",
    },
    params: {
      color1: "#f43f5e",
      color2: "#fbbf24",
      rimColor: "#fff1f2",
      laceGlow: 1.15,
      contrast: 1.2,
      glow: 1.0,
      haloStrength: 0.2,
      radius: 2.15,
      edgeFade: 0.18,
      folds: 10,
      threadSharp: 7.0,
      ringRadius: 0.55,
      foldScale: 1.6,
      seedStrength: 0.62,
      driftSpin: 0.12,
      counterSpin: -0.08,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Coral Vein",
    engine: ENGINE_TYPES.KALISET,
    badge: "Deep Reef",
    description: "Coral filaments threading through deep teal water — coarser folds, softer seams, a patient underwater glow.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.42,
      bloomRadius: 0.34,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.3,
      background: "#01080a",
    },
    params: {
      color1: "#fb7185",
      color2: "#0d9488",
      rimColor: "#f0fdfa",
      laceGlow: 0.95,
      contrast: 1.35,
      glow: 1.05,
      haloStrength: 0.18,
      radius: 2.15,
      edgeFade: 0.22,
      folds: 8,
      threadSharp: 5.0,
      ringRadius: 0.7,
      foldScale: 1.15,
      seedStrength: 0.58,
      driftSpin: 0.09,
      counterSpin: -0.06,
      breatheRate: 0.28,
      breatheAmp: 0.08,
    },
  }
];