import { ENGINE_TYPES } from '../core/state.js';

export const MOIRE_PRESETS = [
  {
    name: "1. Chiral Square Vortex",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Hyperboloid Funnel",
    description: "3D hyperbolic trumpet vortex with outer diamond rim at +Z and inner rotated square aperture recessed into -Z.",
    global: {
      exposure: 1,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#fcfbf8",
    },
    params: {
      archetype: "square_vortex",
      scale: 2.1,
      zDepth: 1.4,
      lineDensity: 28,
      innerScale: 0.26,
      twistAngle: 0.72,
      lineWidth: 2,
      lineColor: "#0a0a0d",
      lineGlow: 1,
      motionMode: "orbit_3d",
      rotSpeedX: 0.18,
      rotSpeedY: 0.38,
      rotSpeedZ: 0.1,
      breatheSpeed: 0.6,
      breatheAmp: 0.08,
      waveSpeed: 1.2,
      waveAmp: 0.22,
      twistSpeed: 0.4,
      tiltStrength: 0.35,
    },
  },
  {
    name: "2. Hexagonal Chiral Vortex",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Hex Vortex Tower",
    description: "Six-fold chiral ruled surface chords twisting along a 3D conical hyperboloid trumpet.",
    global: {
      exposure: 1,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#fcfbf8",
    },
    params: {
      archetype: "hex_vortex",
      scale: 2.1,
      zDepth: 1.45,
      lineDensity: 26,
      innerScale: 0.24,
      twistAngle: 0.55,
      lineWidth: 2,
      lineColor: "#0a0a0d",
      lineGlow: 1,
      motionMode: "orbit_3d",
      rotSpeedX: 0.16,
      rotSpeedY: 0.36,
      rotSpeedZ: 0.08,
      breatheSpeed: 0.55,
      breatheAmp: 0.08,
      waveSpeed: 1.15,
      waveAmp: 0.2,
      twistSpeed: 0.35,
      tiltStrength: 0.35,
    },
  },
  {
    name: "3. Pentagonal String Polygon",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Pentagonal Hypar Dome",
    description: "Five-fold parabolic curve stitching across non-coplanar 3D edges, forming an architectural hyperbolic paraboloid vault.",
    global: {
      exposure: 1,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#fcfbf8",
    },
    params: {
      archetype: "pentagon_envelope",
      scale: 2.15,
      zDepth: 1.35,
      lineDensity: 22,
      innerScale: 0.3,
      twistAngle: 0.6,
      lineWidth: 2,
      lineColor: "#0a0a0d",
      lineGlow: 1,
      motionMode: "orbit_3d",
      rotSpeedX: 0.2,
      rotSpeedY: 0.4,
      rotSpeedZ: 0.1,
      breatheSpeed: 0.5,
      breatheAmp: 0.07,
      waveSpeed: 1.25,
      waveAmp: 0.24,
      twistSpeed: 0.4,
      tiltStrength: 0.35,
    },
  },
  {
    name: "4. Stellated Moiré Star",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Toroidal Star Cage",
    description: "Concentric rotating polygon tiers distributed along a 3D spherical shell, forming a hollow star polytope.",
    global: {
      exposure: 1,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#fcfbf8",
    },
    params: {
      archetype: "stellated_rosette",
      scale: 2.2,
      zDepth: 1.3,
      lineDensity: 24,
      innerScale: 0.35,
      twistAngle: 0.4,
      lineWidth: 2,
      lineColor: "#0a0a0d",
      lineGlow: 1,
      motionMode: "orbit_3d",
      rotSpeedX: 0.18,
      rotSpeedY: 0.35,
      rotSpeedZ: 0.12,
      breatheSpeed: 0.5,
      breatheAmp: 0.08,
      waveSpeed: 1.1,
      waveAmp: 0.2,
      twistSpeed: 0.45,
      tiltStrength: 0.35,
    },
  },
  {
    name: "5. Astroid Quadrilateral Frame",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Astroid Saddle Vault",
    description: "Four-cusp parabolic string envelope bridging non-coplanar alternating 3D corners with double-curved saddle geometry.",
    global: {
      exposure: 1,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#fcfbf8",
    },
    params: {
      archetype: "astroid_quad",
      scale: 2.1,
      zDepth: 1.4,
      lineDensity: 24,
      innerScale: 0.28,
      twistAngle: 0.5,
      lineWidth: 2,
      lineColor: "#0a0a0d",
      lineGlow: 1,
      motionMode: "orbit_3d",
      rotSpeedX: 0.22,
      rotSpeedY: 0.38,
      rotSpeedZ: 0.1,
      breatheSpeed: 0.5,
      breatheAmp: 0.07,
      waveSpeed: 1.2,
      waveAmp: 0.22,
      twistSpeed: 0.4,
      tiltStrength: 0.35,
    },
  },
  {
    name: "6. Guilloché Spirograph Rosette",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Toroidal Spirograph Orb",
    description: "Harmonic 16-lobed hypotrochoid loops undulating in 3D along a toroidal surface with intersecting lace chords.",
    global: {
      exposure: 1,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#fcfbf8",
    },
    params: {
      archetype: "guilloche_rosette",
      scale: 2.1,
      zDepth: 1.35,
      lineDensity: 28,
      innerScale: 0.32,
      twistAngle: 0.6,
      lineWidth: 1.8,
      lineColor: "#0a0a0d",
      lineGlow: 1,
      motionMode: "orbit_3d",
      rotSpeedX: 0.18,
      rotSpeedY: 0.35,
      rotSpeedZ: 0.12,
      breatheSpeed: 0.45,
      breatheAmp: 0.06,
      waveSpeed: 1.15,
      waveAmp: 0.2,
      twistSpeed: 0.35,
      tiltStrength: 0.35,
    },
  },
  {
    name: "7. Triangular Chiral Vortex",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Tetrahedral Vortex",
    description: "Three-fold chiral vortex chords connecting an outer inverted triangle rim to an aperture recessed deeply into 3D space.",
    global: {
      exposure: 1,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#fcfbf8",
    },
    params: {
      archetype: "triangle_vortex",
      scale: 2.2,
      zDepth: 1.45,
      lineDensity: 26,
      innerScale: 0.26,
      twistAngle: 0.85,
      lineWidth: 2,
      lineColor: "#0a0a0d",
      lineGlow: 1,
      motionMode: "orbit_3d",
      rotSpeedX: 0.2,
      rotSpeedY: 0.4,
      rotSpeedZ: 0.1,
      breatheSpeed: 0.55,
      breatheAmp: 0.08,
      waveSpeed: 1.2,
      waveAmp: 0.22,
      twistSpeed: 0.4,
      tiltStrength: 0.35,
    },
  },
  {
    name: "8. Perspective Triangle Tunnel",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Perspective Corridor",
    description: "Authentic 3D spatial triangular corridor stepping back through Z into infinity with longitudinal depth guide rails.",
    global: {
      exposure: 1,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#fcfbf8",
    },
    params: {
      archetype: "triangle_tunnel",
      scale: 2.1,
      zDepth: 1.55,
      lineDensity: 24,
      innerScale: 0.25,
      twistAngle: 0,
      lineWidth: 2,
      lineColor: "#0a0a0d",
      lineGlow: 1,
      motionMode: "orbit_3d",
      rotSpeedX: 0.15,
      rotSpeedY: 0.35,
      rotSpeedZ: 0.08,
      breatheSpeed: 0.45,
      breatheAmp: 0.06,
      waveSpeed: 1.1,
      waveAmp: 0.18,
      twistSpeed: 0.3,
      tiltStrength: 0.35,
    },
  },
  {
    name: "9. Bilateral Winged Moiré",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Bilateral Winged Saddle",
    description: "Dual symmetric parabolic 3D string fans creating arched wing horns in +Z, a central recessed void, and a curling 3D fringe.",
    global: {
      exposure: 1,
      bloomStrength: 0.02,
      bloomRadius: 0.15,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#fcfbf8",
    },
    params: {
      archetype: "winged_moire",
      scale: 2.1,
      zDepth: 1.45,
      lineDensity: 34,
      innerScale: 0.3,
      twistAngle: 0,
      lineWidth: 2,
      lineColor: "#0a0a0d",
      lineGlow: 1,
      motionMode: "orbit_3d",
      rotSpeedX: 0.18,
      rotSpeedY: 0.36,
      rotSpeedZ: 0.08,
      breatheSpeed: 0.5,
      breatheAmp: 0.06,
      waveSpeed: 1.15,
      waveAmp: 0.2,
      twistSpeed: 0.35,
      tiltStrength: 0.35,
    },
  },
  {
    name: "Cyber Gold Chiral Vortex",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Cyber Gold Funnel",
    description: "Luminescent solar gold 3D hyperboloid vortex with harmonic wave undulation and radiant bloom on void black.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.45,
      bloomRadius: 0.3,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.3,
      background: "#000000",
    },
    params: {
      archetype: "square_vortex",
      scale: 2.1,
      zDepth: 1.5,
      lineDensity: 30,
      innerScale: 0.26,
      twistAngle: 0.72,
      lineWidth: 2.2,
      lineColor: "#ffed00",
      lineGlow: 1.8,
      motionMode: "orbit_3d",
      rotSpeedX: 0.2,
      rotSpeedY: 0.45,
      rotSpeedZ: 0.12,
      breatheSpeed: 0.65,
      breatheAmp: 0.1,
      waveSpeed: 1.3,
      waveAmp: 0.25,
      twistSpeed: 0.45,
      tiltStrength: 0.4,
    },
  },
  {
    name: "Electric Cyan Moiré Rosette",
    engine: ENGINE_TYPES.MOIRE,
    badge: "3D Cyber Cyan Orb",
    description: "Electric cyan 3D toroidal spirograph lace on pitch black with continuous 3D rotation and volumetric depth.",
    global: {
      exposure: 1.15,
      bloomStrength: 0.45,
      bloomRadius: 0.3,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.3,
      background: "#000000",
    },
    params: {
      archetype: "guilloche_rosette",
      scale: 2.1,
      zDepth: 1.45,
      lineDensity: 28,
      innerScale: 0.32,
      twistAngle: 0.6,
      lineWidth: 2.2,
      lineColor: "#00f0ff",
      lineGlow: 1.8,
      motionMode: "orbit_3d",
      rotSpeedX: 0.2,
      rotSpeedY: 0.42,
      rotSpeedZ: 0.12,
      breatheSpeed: 0.5,
      breatheAmp: 0.08,
      waveSpeed: 1.2,
      waveAmp: 0.22,
      twistSpeed: 0.4,
      tiltStrength: 0.4,
    },
  }
];
