import { ENGINE_TYPES } from '../core/state.js';

// The refined family: ten classical techniques — cymatics, phyllotaxis,
// harmonograph, strange attractor, maurer rose, marbling, metaballs,
// truchet arcs, caustics and the superformula.

export const REFINED_PRESETS = [
  {
    name: "Sand Sequencing",
    engine: ENGINE_TYPES.CHLADNI,
    badge: "Cymatic Canon",
    description: "Warm sand tracing nodal lines over a deep plate — the figure passing through its pure mode forever.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.3,
      background: "#04060b",
    },
    params: {
      plate: "circle",
      colorSand: "#ffe9b8",
      colorPlate: "#101b2e",
      rimColor: "#dbe7ff",
      sandGlow: 1.3,
      plateLight: 0.7,
      gain: 1.0,
      contrast: 1.1,
      radius: 2.2,
      edgeFade: 0.1,
      modeN: 4,
      modeM: 2,
      resonance: 0.7,
      lineWeight: 0.05,
      morphRate: 0.24,
      spinRate: 0.05,
      breatheRate: 0.35,
      breatheAmp: 0.04,
    },
  },
  {
    name: "Ultrasonic Etude",
    engine: ENGINE_TYPES.CHLADNI,
    badge: "High Modes",
    description: "High mode pair, tight lines — a finer, faster etude on the same plate.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.3,
      bloomRadius: 0.28,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.25,
      background: "#02040a",
    },
    params: {
      plate: "circle",
      colorSand: "#a5f3fc",
      colorPlate: "#0b1026",
      rimColor: "#dbe7ff",
      sandGlow: 1.3,
      plateLight: 0.7,
      gain: 1.0,
      contrast: 1.1,
      radius: 2.2,
      edgeFade: 0.1,
      modeN: 6,
      modeM: 5,
      resonance: 0.7,
      lineWeight: 0.03,
      morphRate: 0.24,
      spinRate: 0.05,
      breatheRate: 0.35,
      breatheAmp: 0.04,
    },
  },
  {
    name: "Sunflower Canon",
    engine: ENGINE_TYPES.PHYLLOTAXIS,
    badge: "Golden Canon",
    description: "The canonical golden-angle head — warm seeds blushing violet at the rim.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.3,
      background: "#050408",
    },
    params: {
      colorCore: "#ffd166",
      colorEdge: "#e879f9",
      colorBg: "#0c0a14",
      rimColor: "#fefce8",
      glow: 1.0,
      light: 0.9,
      gain: 1.0,
      contrast: 1.05,
      radius: 2.2,
      edgeFade: 0.1,
      count: 220,
      dotScale: 0.55,
      angleDrift: 0.0,
      dotBreath: 0.55,
      spinRate: 0.08,
      breatheRate: 0.4,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Seafern",
    engine: ENGINE_TYPES.PHYLLOTAXIS,
    badge: "Cool Divergence",
    description: "A nudge off the golden angle and a cool palette — the head re-packs into a seafern whorl.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.25,
      background: "#01080a",
    },
    params: {
      colorCore: "#a7f3d0",
      colorEdge: "#0e7490",
      colorBg: "#02090c",
      rimColor: "#fefce8",
      glow: 1.0,
      light: 0.9,
      gain: 1.0,
      contrast: 1.05,
      radius: 2.2,
      edgeFade: 0.1,
      count: 280,
      dotScale: 0.45,
      angleDrift: 0.012,
      dotBreath: 0.55,
      spinRate: 0.08,
      breatheRate: 0.4,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Ink on Vellum",
    engine: ENGINE_TYPES.HARMONOGRAPH,
    badge: "Victorian Canon",
    description: "Blue ink on warm vellum — the 3:2 figure drawn, damped, and drawn again.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.25,
      bloomRadius: 0.25,
      bloomThreshold: 0.18,
      autoRotateSpeed: 0.25,
      background: "#0a0a08",
    },
    params: {
      colorInk: "#1d4ed8",
      colorPaper: "#f8f5ec",
      rimColor: "#dbeafe",
      inkGlow: 1.2,
      gain: 1.0,
      contrast: 1.0,
      radius: 2.2,
      edgeFade: 0.1,
      freqA: 3.0,
      freqB: 2.0,
      damping: 0.16,
      traceLength: 10.0,
      lineWeight: 1.9,
      driftRate: 0.18,
      spinRate: 0.04,
      breatheRate: 0.3,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Red Chord",
    engine: ENGINE_TYPES.HARMONOGRAPH,
    badge: "Crimson Study",
    description: "A 5:4 figure in crimson on near-black paper — heavier damping, shorter trace.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.25,
      bloomRadius: 0.25,
      bloomThreshold: 0.18,
      autoRotateSpeed: 0.2,
      background: "#070203",
    },
    params: {
      colorInk: "#f43f5e",
      colorPaper: "#0d0508",
      rimColor: "#dbeafe",
      inkGlow: 1.2,
      gain: 1.0,
      contrast: 1.0,
      radius: 2.2,
      edgeFade: 0.1,
      freqA: 5.0,
      freqB: 4.0,
      damping: 0.24,
      traceLength: 8.0,
      lineWeight: 2.6,
      driftRate: 0.18,
      spinRate: 0.04,
      breatheRate: 0.3,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Ember Wisps",
    engine: ENGINE_TYPES.ATTRACTOR,
    badge: "Attractor Canon",
    description: "Indigo wisps condensing around an ember core — the Clifford attractor alive.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.25,
      background: "#030308",
    },
    params: {
      colorEmber: "#fbbf24",
      colorWisp: "#6366f1",
      colorBg: "#07060e",
      rimColor: "#eef2ff",
      densityGain: 1.2,
      gain: 1.0,
      contrast: 1.15,
      radius: 2.2,
      edgeFade: 0.1,
      iterations: 32,
      coefA: 1.7,
      coefB: 1.7,
      coefC: 0.6,
      coefD: 1.2,
      morphAmp: 0.18,
      spinRate: 0.05,
      breatheRate: 0.35,
      breatheAmp: 0.04,
    },
  },
  {
    name: "Deep Current",
    engine: ENGINE_TYPES.ATTRACTOR,
    badge: "Night Sea",
    description: "Cold cyan filaments on black — wider drift, deeper contrast.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.2,
      background: "#010205",
    },
    params: {
      colorEmber: "#e0f2fe",
      colorWisp: "#0e7490",
      colorBg: "#010204",
      rimColor: "#eef2ff",
      densityGain: 1.2,
      gain: 1.0,
      contrast: 1.15,
      radius: 2.2,
      edgeFade: 0.1,
      iterations: 32,
      coefA: 2.05,
      coefB: 1.4,
      coefC: 0.6,
      coefD: 1.2,
      morphAmp: 0.24,
      spinRate: 0.05,
      breatheRate: 0.35,
      breatheAmp: 0.04,
    },
  },
  {
    name: "Rose Web",
    engine: ENGINE_TYPES.MAURER,
    badge: "Maurer Canon",
    description: "Pink chords weaving a five-petal rose — the classic 71-degree web.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.25,
      background: "#06030a",
    },
    params: {
      colorWeb: "#f9a8d4",
      colorHeart: "#170b1e",
      rimColor: "#fdf2f8",
      chordGlow: 1.25,
      coreBloom: 0.5,
      gain: 1.0,
      contrast: 1.05,
      radius: 2.2,
      edgeFade: 0.1,
      petals: 5,
      step: 71,
      lineWeight: 1.4,
      spinRate: 0.06,
      breatheRate: 0.35,
      breatheAmp: 0.04,
    },
  },
  {
    name: "Silver Lattice",
    engine: ENGINE_TYPES.MAURER,
    badge: "Cold Weave",
    description: "Silver chords over a midnight heart — the 129-degree web, finer and colder.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.2,
      background: "#02040a",
    },
    params: {
      colorWeb: "#dbe4ff",
      colorHeart: "#05070f",
      rimColor: "#fdf2f8",
      chordGlow: 1.25,
      coreBloom: 0.5,
      gain: 1.0,
      contrast: 1.05,
      radius: 2.2,
      edgeFade: 0.1,
      petals: 7,
      step: 129,
      lineWeight: 1.0,
      spinRate: 0.06,
      breatheRate: 0.35,
      breatheAmp: 0.04,
    },
  },
  {
    name: "Suminagashi",
    engine: ENGINE_TYPES.INKMARBLE,
    badge: "Marbling Canon",
    description: "Indigo ink on a cream bath — six stylus passes, one gold crease.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.3,
      bloomRadius: 0.28,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.3,
      background: "#08070c",
    },
    params: {
      colorInk: "#1e1b4b",
      colorPaper: "#fdf6e3",
      colorAccent: "#d97706",
      creaseGain: 0.6,
      gain: 1.0,
      contrast: 1.15,
      light: 0.8,
      rim: 0.3,
      haloStrength: 0.18,
      radius: 2.15,
      edgeFade: 0.18,
      stripeDensity: 9.0,
      swirlDepth: 1.7,
      swirlFreq: 1.6,
      driftSpin: 0.1,
      counterSpin: -0.07,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Rose Bath",
    engine: ENGINE_TYPES.INKMARBLE,
    badge: "Warm Float",
    description: "Rose and wine inks on ivory — wider stylus, denser stripes.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.3,
      bloomRadius: 0.28,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.3,
      background: "#0b0508",
    },
    params: {
      colorInk: "#701a3f",
      colorPaper: "#fdeef2",
      colorAccent: "#b45309",
      creaseGain: 0.6,
      gain: 1.0,
      contrast: 1.15,
      light: 0.8,
      rim: 0.3,
      haloStrength: 0.18,
      radius: 2.15,
      edgeFade: 0.18,
      stripeDensity: 12.0,
      swirlDepth: 2.1,
      swirlFreq: 1.6,
      driftSpin: 0.1,
      counterSpin: -0.07,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Pink Goo",
    engine: ENGINE_TYPES.LAVALAMP,
    badge: "Lava Canon",
    description: "Rose gel blobs kissing and parting over a wine-deep field.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.3,
      background: "#070308",
    },
    params: {
      colorGel: "#fb7185",
      colorGelDeep: "#7c2d4e",
      colorSpec: "#ffe4e6",
      light: 0.9,
      rim: 0.3,
      gain: 1.0,
      contrast: 1.05,
      haloStrength: 0.2,
      radius: 2.15,
      edgeFade: 0.18,
      blobCount: 5,
      blobSpread: 0.55,
      blobSize: 0.45,
      fieldSharp: 0.08,
      gooRate: 0.35,
      driftSpin: 0.08,
      counterSpin: -0.06,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Deep Sea Wax",
    engine: ENGINE_TYPES.LAVALAMP,
    badge: "Cold Lamp",
    description: "Cold wax blobs in a deep teal lamp — slower, heavier, patient.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.35,
      bloomRadius: 0.3,
      bloomThreshold: 0.14,
      autoRotateSpeed: 0.25,
      background: "#010507",
    },
    params: {
      colorGel: "#67e8f9",
      colorGelDeep: "#155e75",
      colorSpec: "#ecfeff",
      light: 0.9,
      rim: 0.3,
      gain: 1.0,
      contrast: 1.05,
      haloStrength: 0.2,
      radius: 2.15,
      edgeFade: 0.18,
      blobCount: 4,
      blobSpread: 0.55,
      blobSize: 0.75,
      fieldSharp: 0.16,
      gooRate: 0.22,
      driftSpin: 0.08,
      counterSpin: -0.06,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Copper Circuit",
    engine: ENGINE_TYPES.TRUCHET,
    badge: "Weave Canon",
    description: "Teal arcs on near-black cells with copper flow crests — the board quietly re-threading.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.3,
      background: "#020409",
    },
    params: {
      colorArc: "#5eead4",
      colorCell: "#0b1220",
      colorFlow: "#fde68a",
      arcGlow: 1.3,
      arcWidth: 1.1,
      gain: 1.0,
      contrast: 1.1,
      light: 0.75,
      rim: 0.3,
      haloStrength: 0.18,
      radius: 2.15,
      edgeFade: 0.18,
      cellScale: 9.0,
      flipRate: 0.22,
      flowRate: 0.8,
      driftSpin: 0.1,
      counterSpin: -0.07,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Porcelain Lattice",
    engine: ENGINE_TYPES.TRUCHET,
    badge: "Fine Tile",
    description: "Fine cobalt arcs on porcelain cells — a calmer, denser weave.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.3,
      bloomRadius: 0.28,
      bloomThreshold: 0.15,
      autoRotateSpeed: 0.25,
      background: "#0a0c12",
    },
    params: {
      colorArc: "#3b82f6",
      colorCell: "#eef2ff",
      colorFlow: "#fbbf24",
      arcGlow: 0.9,
      arcWidth: 1.1,
      gain: 1.0,
      contrast: 1.1,
      light: 0.75,
      rim: 0.3,
      haloStrength: 0.18,
      radius: 2.15,
      edgeFade: 0.18,
      cellScale: 5.0,
      flipRate: 0.12,
      flowRate: 0.8,
      driftSpin: 0.1,
      counterSpin: -0.07,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Shallow Water",
    engine: ENGINE_TYPES.CAUSTICS,
    badge: "Pool Canon",
    description: "Cyan light net over deep water — filaments knotting as the surface drifts.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.3,
      background: "#01060a",
    },
    params: {
      colorShallow: "#67e8f9",
      colorDeep: "#0e3a5c",
      colorFilament: "#f0fdfa",
      filamentSharp: 9.0,
      gain: 1.0,
      contrast: 1.1,
      light: 0.85,
      rim: 0.3,
      haloStrength: 0.2,
      radius: 2.15,
      edgeFade: 0.18,
      waterScale: 2.2,
      warpAmp: 0.6,
      flowRate: 0.4,
      driftSpin: 0.1,
      counterSpin: -0.07,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Sunset Lagoon",
    engine: ENGINE_TYPES.CAUSTICS,
    badge: "Warm Pool",
    description: "A warm lagoon — golden filaments over deep teal, slower flow.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.32,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.25,
      background: "#04060a",
    },
    params: {
      colorShallow: "#fde68a",
      colorDeep: "#134e4a",
      colorFilament: "#fffbeb",
      filamentSharp: 9.0,
      gain: 1.0,
      contrast: 1.1,
      light: 0.85,
      rim: 0.3,
      haloStrength: 0.2,
      radius: 2.15,
      edgeFade: 0.18,
      waterScale: 2.2,
      warpAmp: 0.6,
      flowRate: 0.28,
      driftSpin: 0.1,
      counterSpin: -0.07,
      breatheRate: 0.35,
      breatheAmp: 0.06,
    },
  },
  {
    name: "Morphing Peony",
    engine: ENGINE_TYPES.SUPERBLOOM,
    badge: "Bloom Canon",
    description: "Pink petals around a gold heart, morphing through symmetries as the envelope breathes.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.3,
      background: "#070309",
    },
    params: {
      colorPetal: "#f472b6",
      colorHeart: "#fde68a",
      colorEdge: "#4c1d95",
      rimColor: "#fdf2f8",
      edgeGlow: 1.2,
      fillGradient: 0.65,
      gain: 1.0,
      contrast: 1.05,
      radius: 2.2,
      edgeFade: 0.1,
      symmetry: 6,
      pinch: 0.5,
      roundness: 1.3,
      morphRate: 0.16,
      spinRate: 0.06,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
  {
    name: "Night Star",
    engine: ENGINE_TYPES.SUPERBLOOM,
    badge: "Cold Bloom",
    description: "A cold seven-point star — steel petals, white envelope, stately morph.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.25,
      background: "#020409",
    },
    params: {
      colorPetal: "#93c5fd",
      colorHeart: "#e0f2fe",
      colorEdge: "#1e1b4b",
      rimColor: "#fdf2f8",
      edgeGlow: 1.2,
      fillGradient: 0.65,
      gain: 1.0,
      contrast: 1.05,
      radius: 2.2,
      edgeFade: 0.1,
      symmetry: 7,
      pinch: 0.6,
      roundness: 2.2,
      morphRate: 0.1,
      spinRate: 0.06,
      breatheRate: 0.35,
      breatheAmp: 0.05,
    },
  },
];
