import { ENGINE_TYPES } from '../core/state.js';

// Regard's presets are one engine at three points on its attention axis, so
// the rehearsal room can walk between them without a rebuild. Its own file
// because bodies.js is at the size guard.
export const REGARD_PRESETS = [
  {
    name: "Regard Attending",
    engine: ENGINE_TYPES.REGARD,
    badge: "Listening",
    description: "Holds your gaze with small refixations and follows the pointer. Blinks rarely; the light is warm and steady.",
    global: {
      exposure: 1,
      bloomStrength: 0.22,
      bloomRadius: 0.3,
      bloomThreshold: 0.35,
      autoRotateSpeed: 0,
      background: "#05060a",
    },
    params: {
      haloSize: 1.18,
      irisFibres: 23,
      attention: 0.05,
      searchSpread: 0.35,
      dwell: 1.6,
      saccadeSpeed: 0.9,
      jitter: 0.3,
      blinks: 0.3,
      focusSize: 0.4,
      lean: 0.55,
      focusColor: "#ffc978",
      haloColor: "#ff8a4c",
      rimColor: "#4f63ff",
      bodyColor: "#05070c",
      focusGlow: 1.25,
      rimGlow: 0.6,
    },
  },
  {
    name: "Regard Pondering",
    engine: ENGINE_TYPES.REGARD,
    badge: "Thinking",
    description: "Looks up and away and searches in quick, short glances, blinking on the larger ones. The same orb as Attending, further along one axis.",
    global: {
      exposure: 1,
      bloomStrength: 0.22,
      bloomRadius: 0.3,
      bloomThreshold: 0.35,
      autoRotateSpeed: 0,
      background: "#05060a",
    },
    params: {
      haloSize: 1.18,
      irisFibres: 23,
      attention: 0.85,
      searchSpread: 0.75,
      dwell: 0.45,
      saccadeSpeed: 1.3,
      jitter: 0.25,
      blinks: 0.45,
      focusSize: 0.32,
      lean: 0.6,
      focusColor: "#ffc978",
      haloColor: "#ff8a4c",
      rimColor: "#4f63ff",
      bodyColor: "#05070c",
      focusGlow: 1.1,
      rimGlow: 0.6,
    },
  },
  {
    name: "Regard Drowsing",
    engine: ENGINE_TYPES.REGARD,
    badge: "Idle",
    description: "Slow, wide, unhurried glances with long dwells and heavy blinks: present, but not waiting on you.",
    global: {
      exposure: 0.95,
      bloomStrength: 0.18,
      bloomRadius: 0.3,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0,
      background: "#04050a",
    },
    params: {
      haloSize: 1.18,
      irisFibres: 23,
      attention: 0.4,
      searchSpread: 0.9,
      dwell: 2.6,
      saccadeSpeed: 0.45,
      jitter: 0.5,
      blinks: 0.8,
      focusSize: 0.3,
      lean: 0.8,
      focusColor: "#9fd8ff",
      haloColor: "#4c7dff",
      rimColor: "#8a5cff",
      bodyColor: "#05070c",
      focusGlow: 0.8,
      rimGlow: 0.45,
    },
  }
];
