import { ENGINE_TYPES } from '../core/state.js';

// The shape experiments: LED tiles on a rounded cube, quantized plasma on a
// torus — the first engines whose geometry is raymarched SDF rather than an
// analytic sphere.

export const SHAPES_PRESETS = [
  {
    name: "Signal Wall",
    engine: ENGINE_TYPES.LEDBOX,
    badge: "LED Canon",
    description: "Warm white tiles churning over a near-black wall — the departure board, alive.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.13,
      autoRotateSpeed: 0.35,
      background: "#030303",
    },
    params: {
      shape: "box",
      colorLit: "'#fff2dd'",
      colorWall: "'#161616'",
      light: 0.6,
      gain: 1.0,
      contrast: 1.0,
      boxSize: 1.5,
      bevel: 0.12,
      cells: 40,
      blobScale: 1.3,
      coverage: 0.62,
      confetti: 0.22,
      churnRate: 0.5,
      driftRate: 0.45,
      twinkleRate: 2.0,
      spinRate: 0.1,
      breatheRate: 0.35,
      breatheAmp: 0.03,
    },
  },
  {
    name: "Confetti Board",
    engine: ENGINE_TYPES.LEDBOX,
    badge: "Pixel Party",
    description: "Sparse coverage, heavy confetti, fast twinkle — a celebration on a tile wall.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.45,
      bloomRadius: 0.32,
      bloomThreshold: 0.11,
      autoRotateSpeed: 0.4,
      background: "#020204",
    },
    params: {
      shape: "box",
      colorLit: "#a5f3fc",
      colorWall: "'#161616'",
      light: 0.6,
      gain: 1.0,
      contrast: 1.0,
      boxSize: 1.5,
      bevel: 0.12,
      cells: 56,
      blobScale: 1.3,
      coverage: 0.3,
      confetti: 0.8,
      churnRate: 0.5,
      driftRate: 0.45,
      twinkleRate: 5.0,
      spinRate: 0.1,
      breatheRate: 0.35,
      breatheAmp: 0.03,
    },
  },
  {
    name: "Circuit Ring",
    engine: ENGINE_TYPES.QUANTTORUS,
    badge: "Ring Canon",
    description: "Cold blue plasma stepping around the ring in chunky pixel arcs.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.4,
      bloomRadius: 0.3,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.35,
      background: "#02030a",
    },
    params: {
      profile: "round",
      colorInk: "'#101426'",
      colorPaper: "'#cfe6ff'",
      light: 0.9,
      rim: 0.35,
      gain: 1.0,
      contrast: 1.3,
      ringR: 1.35,
      tubeR: 0.65,
      tilt: 1.2,
      cells: 40,
      levels: 3,
      patternScale: 2.0,
      plasmaAmp: 1.0,
      plasmaRate: 0.5,
      spinRate: 0.12,
      breatheRate: 0.35,
      breatheAmp: 0.04,
    },
  },
  {
    name: "Molten Ring",
    engine: ENGINE_TYPES.QUANTTORUS,
    badge: "Ember Loop",
    description: "Ember tones on near-black, four levels, a slower deeper churn — a ring of cooling lava.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.42,
      bloomRadius: 0.32,
      bloomThreshold: 0.12,
      autoRotateSpeed: 0.3,
      background: "#060201",
    },
    params: {
      profile: "round",
      colorInk: "#030100",
      colorPaper: "#ffb347",
      light: 0.9,
      rim: 0.35,
      gain: 1.0,
      contrast: 1.3,
      ringR: 1.35,
      tubeR: 0.65,
      tilt: 1.35,
      cells: 56,
      levels: 4,
      patternScale: 2.0,
      plasmaAmp: 1.6,
      plasmaRate: 0.3,
      spinRate: 0.12,
      breatheRate: 0.35,
      breatheAmp: 0.04,
    },
  },
];
