import { ENGINE_TYPES } from '../core/state.js';

export const SIMULATION_PRESETS = [
  {
    name: "Neon Voice Ribbon",
    engine: ENGINE_TYPES.FLUX,
    badge: "Travelling Wave",
    description: "A wide band of strands streaming past, fanning apart and converging into bright knots. The voice-assistant waveform read.",
    global: {
      exposure: 1,
      bloomStrength: 0.35,
      bloomRadius: 0.35,
      bloomThreshold: 0.3,
      autoRotateSpeed: 0,
      background: "#05010c",
    },
    params: {
      layout: "ribbon",
      strands: 28,
      segments: 160,
      bandSpread: 1.1,
      ribbonWidth: 14,
      sparkleDensity: 0.035,
      amplitude: 0.85,
      wavelength: 0.42,
      phaseSpread: 2.4,
      depth: 2.2,
      turbulence: 0.35,
      flowSpeed: 0.9,
      colorA: "#ff4fd8",
      colorB: "#a86bff",
      colorC: "#4fd0ff",
      glow: 2.1,
      sparkleSize: 2.2,
      sparkleBrightness: 2.4,
    },
  },
  {
    name: "Filament Sphere",
    engine: ENGINE_TYPES.FLUX,
    badge: "Wrapped Flow",
    description: "The same travelling wave wrapped pole to pole, so the strands become a slowly turning ball of streaming threads.",
    global: {
      exposure: 1,
      bloomStrength: 0.3,
      bloomRadius: 0.3,
      bloomThreshold: 0.32,
      autoRotateSpeed: 0,
      background: "#03040a",
    },
    params: {
      layout: "orb",
      strands: 34,
      segments: 180,
      twist: 0.9,
      sparkleDensity: 0.05,
      amplitude: 1.1,
      wavelength: 0.55,
      phaseSpread: 1.6,
      turbulence: 0.55,
      flowSpeed: 0.55,
      colorA: "#ff5ec4",
      colorB: "#8f7bff",
      colorC: "#5ff0ff",
      glow: 1.9,
      sparkleSize: 2.6,
      sparkleBrightness: 2.8,
    },
  },
  {
    name: "Stillwater Listener",
    engine: ENGINE_TYPES.AQUEOUS,
    badge: "Calm Refractive Body",
    description: "A weighty teal body with slow migrating contours and a warm light held beneath the surface.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.24,
      bloomRadius: 0.32,
      bloomThreshold: 0.38,
      autoRotateSpeed: 0,
      background: "#01080b",
    },
    params: {
      detail: 5,
      radius: 1.5,
      displaceOctaves: 3,
      displaceAmount: 0.18,
      displaceScale: 1.4,
      breatheSpeed: 0.35,
      breatheAmp: 0.04,
      driftSpeed: 0.25,
      pulseDeform: 0.25,
      bodyColor: "#2dd4bf",
      coreColor: "#ffed00",
      transmission: 0.85,
      thickness: 1.2,
      ior: 1.42,
      roughness: 0.15,
      coreIntensity: 1.6,
      fresnelPower: 2.5,
    },
  },
  {
    name: "Rose Brine",
    engine: ENGINE_TYPES.AQUEOUS,
    badge: "Warm Refractive Body",
    description: "A rose-tinted volume with slower, heavier contours and a gold core held deeper in the glass.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.28,
      bloomRadius: 0.34,
      bloomThreshold: 0.34,
      autoRotateSpeed: 0,
      background: "#0a0306",
    },
    params: {
      detail: 6,
      radius: 1.6,
      displaceOctaves: 4,
      displaceAmount: 0.28,
      displaceScale: 1.1,
      breatheSpeed: 0.2,
      breatheAmp: 0.07,
      driftSpeed: 0.15,
      pulseDeform: 0.4,
      bodyColor: "#fb7185",
      coreColor: "#ffe08a",
      transmission: 0.78,
      thickness: 1.7,
      ior: 1.52,
      roughness: 0.22,
      coreIntensity: 2.1,
      fresnelPower: 2.1,
    },
  },
  {
    name: "Amber Lens",
    engine: ENGINE_TYPES.AQUEOUS,
    badge: "Dense Glass",
    description: "A compact amber body with higher refraction and a quieter surface, more lens than water.",
    global: {
      exposure: 1.1,
      bloomStrength: 0.22,
      bloomRadius: 0.28,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#0a0702",
    },
    params: {
      detail: 4,
      radius: 1.35,
      displaceOctaves: 2,
      displaceAmount: 0.08,
      displaceScale: 2.2,
      breatheSpeed: 0.25,
      breatheAmp: 0.025,
      driftSpeed: 0.1,
      pulseDeform: 0.18,
      bodyColor: "#f59e0b",
      coreColor: "#fff7ed",
      transmission: 0.62,
      thickness: 2.2,
      ior: 1.85,
      roughness: 0.08,
      coreIntensity: 1.9,
      fresnelPower: 3.6,
    },
  },
  {
    name: "Ink Glass",
    engine: ENGINE_TYPES.AQUEOUS,
    badge: "Dark Volume",
    description: "Near-black indigo glass with a cyan inner light, thicker absorption, and a sharper rim.",
    global: {
      exposure: 0.95,
      bloomStrength: 0.18,
      bloomRadius: 0.26,
      bloomThreshold: 0.46,
      autoRotateSpeed: 0,
      background: "#01020a",
    },
    params: {
      detail: 5,
      radius: 1.55,
      displaceOctaves: 3,
      displaceAmount: 0.14,
      displaceScale: 1.8,
      breatheSpeed: 0.3,
      breatheAmp: 0.035,
      driftSpeed: 0.2,
      pulseDeform: 0.22,
      bodyColor: "#1e1b4b",
      coreColor: "#67e8f9",
      transmission: 0.7,
      thickness: 2.6,
      ior: 1.48,
      roughness: 0.12,
      coreIntensity: 2.4,
      fresnelPower: 1.8,
    },
  },
  {
    name: "Blue Current",
    engine: ENGINE_TYPES.CURL_DRIFT,
    badge: "Directed Stream",
    description: "Clear cyan-to-violet currents braid around a quiet shell with an unmistakable direction of travel.",
    global: {
      exposure: 1,
      bloomStrength: 0.2,
      bloomRadius: 0.25,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#01040a",
    },
    params: {
      streamCount: 64,
      trailLength: 48,
      shellRadius: 1.6,
      lineWidth: 1.6,
      fieldScale: 0.9,
      fieldEvolveSpeed: 0.12,
      flowSpeed: 0.8,
      shellBinding: 0.7,
      swirl: 0.3,
      lifetimeJitter: 0.5,
      coverage: 1,
      coverageCenter: 0,
      headColor: "#00f2fe",
      midColor: "#4f8cff",
      tailColor: "#a855f7",
      glowIntensity: 1.3,
      tailFade: 0.7,
    },
  },
  {
    name: "Equator Band",
    engine: ENGINE_TYPES.CURL_DRIFT,
    badge: "Narrow Belt",
    description: "A gold-to-magenta belt hugging the equator, with tighter swirl and longer trails than a full shell.",
    global: {
      exposure: 1.04,
      bloomStrength: 0.24,
      bloomRadius: 0.28,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0,
      background: "#08020a",
    },
    params: {
      streamCount: 96,
      trailLength: 64,
      shellRadius: 1.7,
      lineWidth: 2.1,
      fieldScale: 1.35,
      fieldEvolveSpeed: 0.08,
      flowSpeed: 0.95,
      shellBinding: 1.15,
      swirl: 0.85,
      lifetimeJitter: 0.25,
      coverage: 0.28,
      coverageCenter: 0,
      headColor: "#ffe08a",
      midColor: "#ff4fd8",
      tailColor: "#7c3aed",
      glowIntensity: 1.7,
      tailFade: 0.55,
    },
  },
  {
    name: "Polar Jet",
    engine: ENGINE_TYPES.CURL_DRIFT,
    badge: "High Latitude",
    description: "Sparse white-cyan streams concentrated near one pole, travelling faster than the rest of the shell.",
    global: {
      exposure: 1,
      bloomStrength: 0.18,
      bloomRadius: 0.22,
      bloomThreshold: 0.42,
      autoRotateSpeed: 0,
      background: "#01060c",
    },
    params: {
      streamCount: 48,
      trailLength: 32,
      shellRadius: 1.85,
      lineWidth: 1.2,
      fieldScale: 0.55,
      fieldEvolveSpeed: 0.22,
      flowSpeed: 1.55,
      shellBinding: 0.9,
      swirl: 0.15,
      lifetimeJitter: 0.7,
      coverage: 0.22,
      coverageCenter: 0.72,
      headColor: "#f8fafc",
      midColor: "#7dd3fc",
      tailColor: "#2563eb",
      glowIntensity: 1.5,
      tailFade: 0.8,
    },
  },
  {
    name: "Ember Drift",
    engine: ENGINE_TYPES.CURL_DRIFT,
    badge: "Hot Current",
    description: "Thick orange-red ribbons with a slow-evolving field, so the heat reads as weight rather than sparkle.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.3,
      bloomRadius: 0.34,
      bloomThreshold: 0.32,
      autoRotateSpeed: 0,
      background: "#0a0402",
    },
    params: {
      streamCount: 64,
      trailLength: 96,
      shellRadius: 1.5,
      lineWidth: 2.8,
      fieldScale: 1.6,
      fieldEvolveSpeed: 0.05,
      flowSpeed: 0.45,
      shellBinding: 0.55,
      swirl: 1.15,
      lifetimeJitter: 0.4,
      coverage: 0.82,
      coverageCenter: -0.2,
      headColor: "#fff7ed",
      midColor: "#fb923c",
      tailColor: "#dc2626",
      glowIntensity: 1.9,
      tailFade: 0.45,
    },
  },
  {
    name: "Deliberation Cloud",
    engine: ENGINE_TYPES.MURMURATION,
    badge: "Gathering Thought",
    description: "A restrained swarm repeatedly gathers and loosens without collapsing into visual noise.",
    global: {
      exposure: 1,
      bloomStrength: 0.18,
      bloomRadius: 0.24,
      bloomThreshold: 0.42,
      autoRotateSpeed: 0,
      background: "#020306",
    },
    params: {
      agentCount: 256,
      shellShape: "sphere",
      shellRadius: 1.7,
      trailLength: 8,
      pointSize: 2,
      cohesion: 0.4,
      separation: 0.55,
      alignment: 0.35,
      neighbourRadius: 0.55,
      attractorPull: 0.5,
      shellBinding: 0.8,
      agentSpeed: 1,
      damping: 0.96,
      coreColor: "#ffed00",
      edgeColor: "#00f2fe",
      glowIntensity: 1.4,
      trailFade: 0.6,
    },
  },
  {
    name: "Ring Council",
    engine: ENGINE_TYPES.MURMURATION,
    badge: "Toroidal Swarm",
    description: "Agents bound to a torus, circulating as a ring of magenta and gold rather than a filled cloud.",
    global: {
      exposure: 1.02,
      bloomStrength: 0.22,
      bloomRadius: 0.26,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#08020a",
    },
    params: {
      agentCount: 384,
      shellShape: "torus",
      shellRadius: 1.85,
      trailLength: 16,
      pointSize: 1.8,
      cohesion: 0.32,
      separation: 0.62,
      alignment: 0.48,
      neighbourRadius: 0.45,
      attractorPull: 0.25,
      shellBinding: 1.35,
      agentSpeed: 1.25,
      damping: 0.95,
      coreColor: "#ffe08a",
      edgeColor: "#ff4fd8",
      glowIntensity: 1.7,
      trailFade: 0.45,
    },
  },
  {
    name: "Cube of Thought",
    engine: ENGINE_TYPES.MURMURATION,
    badge: "Boxed Swarm",
    description: "A slower flock that settles onto the faces of a cube, with mint edges and a warm interior.",
    global: {
      exposure: 1,
      bloomStrength: 0.16,
      bloomRadius: 0.24,
      bloomThreshold: 0.44,
      autoRotateSpeed: 0,
      background: "#020806",
    },
    params: {
      agentCount: 256,
      shellShape: "cube",
      shellRadius: 1.45,
      trailLength: 8,
      pointSize: 2.3,
      cohesion: 0.5,
      separation: 0.45,
      alignment: 0.28,
      neighbourRadius: 0.7,
      attractorPull: 0.35,
      shellBinding: 1.2,
      agentSpeed: 0.7,
      damping: 0.975,
      coreColor: "#fef3c7",
      edgeColor: "#34d399",
      glowIntensity: 1.3,
      trailFade: 0.7,
    },
  },
  {
    name: "Flat Consensus",
    engine: ENGINE_TYPES.MURMURATION,
    badge: "Planar Swarm",
    description: "A disk of coral and violet agents, denser at the rim, with longer ghosts so the flattening reads as motion.",
    global: {
      exposure: 1.04,
      bloomStrength: 0.2,
      bloomRadius: 0.28,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#060218",
    },
    params: {
      agentCount: 384,
      shellShape: "disk",
      shellRadius: 1.9,
      trailLength: 16,
      pointSize: 1.7,
      cohesion: 0.28,
      separation: 0.58,
      alignment: 0.55,
      neighbourRadius: 0.5,
      attractorPull: 0.4,
      shellBinding: 1.5,
      agentSpeed: 1.4,
      damping: 0.945,
      coreColor: "#fda4af",
      edgeColor: "#818cf8",
      glowIntensity: 1.6,
      trailFade: 0.5,
    },
  },
  {
    name: "Signal Lattice",
    engine: ENGINE_TYPES.FILAMENT,
    badge: "Elastic Propagation",
    description: "A dark geodesic web whose warm signal light reveals waves crossing and reflecting through the structure.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.24,
      bloomRadius: 0.28,
      bloomThreshold: 0.36,
      autoRotateSpeed: 0,
      background: "#030306",
    },
    params: {
      subdivision: 2,
      radius: 1.6,
      nodeSize: 0.03,
      lineWidth: 1.8,
      stiffness: 0.35,
      damping: 0.94,
      tether: 0.06,
      pulseStrength: 0.5,
      idleExcitation: 0.05,
      waveSpeed: 0.4,
      displacementGlow: 1.5,
      restColor: "#1e293b",
      activeColor: "#ffed00",
      nodeColor: "#ffffff",
    },
  },
  {
    name: "Slack Current",
    engine: ENGINE_TYPES.FILAMENT,
    badge: "Slow Elasticity",
    description: "A coarse geodesic that sags and rings for a long time, with cyan signal light crawling rather than snapping.",
    global: {
      exposure: 1,
      bloomStrength: 0.2,
      bloomRadius: 0.32,
      bloomThreshold: 0.4,
      autoRotateSpeed: 0,
      background: "#01060c",
    },
    params: {
      subdivision: 1,
      radius: 1.85,
      nodeSize: 0.05,
      lineWidth: 2.6,
      stiffness: 0.12,
      damping: 0.86,
      tether: 0.03,
      pulseStrength: 0.9,
      idleExcitation: 0.08,
      waveSpeed: 0.2,
      displacementGlow: 1.8,
      restColor: "#0f172a",
      activeColor: "#22d3ee",
      nodeColor: "#e0f2fe",
    },
  },
  {
    name: "Nerve Fire",
    engine: ENGINE_TYPES.FILAMENT,
    badge: "Dense Propagation",
    description: "A fine magenta lattice that carries a pulse quickly, with short ring-down and bright interference.",
    global: {
      exposure: 1.05,
      bloomStrength: 0.28,
      bloomRadius: 0.26,
      bloomThreshold: 0.34,
      autoRotateSpeed: 0,
      background: "#0a0310",
    },
    params: {
      subdivision: 3,
      radius: 1.5,
      nodeSize: 0.015,
      lineWidth: 1.1,
      stiffness: 0.82,
      damping: 0.91,
      tether: 0.1,
      pulseStrength: 0.7,
      idleExcitation: 0.12,
      waveSpeed: 1.15,
      displacementGlow: 2.2,
      restColor: "#1a1020",
      activeColor: "#ff4fd8",
      nodeColor: "#ffe8ff",
    },
  },
  {
    name: "Ember Cage",
    engine: ENGINE_TYPES.FILAMENT,
    badge: "Warm Structure",
    description: "Thicker gold-orange filaments hold a heavier cage; pulses glow like heat travelling through wire.",
    global: {
      exposure: 1.08,
      bloomStrength: 0.3,
      bloomRadius: 0.34,
      bloomThreshold: 0.32,
      autoRotateSpeed: 0,
      background: "#0a0402",
    },
    params: {
      subdivision: 2,
      radius: 1.7,
      nodeSize: 0.04,
      lineWidth: 2.8,
      stiffness: 0.48,
      damping: 0.93,
      tether: 0.08,
      pulseStrength: 0.95,
      idleExcitation: 0.07,
      waveSpeed: 0.55,
      displacementGlow: 2.1,
      restColor: "#1c1410",
      activeColor: "#ff7a1a",
      nodeColor: "#ffe8a3",
    },
  }
];
