import { createPrismBloomEngine } from '../../engines/prism-bloom-engine.js';
import { createCoronaVeilEngine } from '../../engines/corona-veil-engine.js';
import { createEchoRingsEngine } from '../../engines/echo-rings-engine.js';
import { createChromasphereEngine } from '../../engines/chromasphere-engine.js';
import { createVocalisEngine } from '../../engines/vocalis-engine.js';
import { createAetheriaEngine } from '../../engines/aetheria-engine.js';
import { createSuperpositionEngine } from '../../engines/superposition-engine.js';
import { createSynthesisEngine } from '../../engines/synthesis-engine.js';
import { createFerroTrailsEngine } from '../../engines/ferro-trails-engine.js';

export const BODIES_ENGINES = [
  {
    key: 'PRISM_BLOOM',
    id: 'prismbloom',
    name: 'Prism Bloom',
    badge: 'Crystalline Flora',
    description: 'Iridescent crystalline petals open in waves around a warm faceted core.',
    defaultPreset: 'Opaline Bloom',
    file: 'prism-bloom-engine.js',
    factoryName: 'createPrismBloomEngine',
    factory: createPrismBloomEngine,
    params: {
      petalCount: { type: 'select', label: 'Petal Count', options: [24, 36, 48, 60, 72], default: 48, section: 'geometry' },
      petalLength: { type: 'number', label: 'Petal Length', min: 1.05, max: 1.42, step: 0.01, default: 1.32, section: 'geometry' },
      petalWidth: { type: 'number', label: 'Petal Width', min: 0.38, max: 0.64, step: 0.01, default: 0.52, section: 'geometry' },
      coreRadius: { type: 'number', label: 'Faceted Core Radius', min: 0.68, max: 0.9, step: 0.01, default: 0.83, section: 'geometry' },
      bloom: { type: 'number', label: 'Bloom Openness', min: 0.12, max: 1, step: 0.01, default: 0.58, section: 'motion' },
      fold: { type: 'number', label: 'Petal Fold', min: 0.35, max: 1, step: 0.01, default: 0.78, section: 'motion' },
      waveStrength: { type: 'number', label: 'Opening Wave', min: 0, max: 0.7, step: 0.01, default: 0.42, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breathing Depth', min: 0, max: 0.25, step: 0.01, default: 0.14, section: 'motion' },
      breatheSpeed: { type: 'number', label: 'Breathing Rate', min: 0.2, max: 1.4, step: 0.02, default: 0.72, section: 'motion' },
      innerColor: { type: 'color', label: 'Inner Petal Colour', default: '#f8c8ff', section: 'colors' },
      outerColor: { type: 'color', label: 'Outer Petal Colour', default: '#58c9ff', section: 'colors' },
      edgeColor: { type: 'color', label: 'Prismatic Edge', default: '#fff4cb', section: 'colors' },
      iridescence: { type: 'number', label: 'Iridescence', min: 0, max: 1, step: 0.01, default: 0.72, section: 'colors' },
      glow: { type: 'number', label: 'Crystal Radiance', min: 0.8, max: 1.8, step: 0.02, default: 1.28, section: 'colors' },
    },
  },
  {
    key: 'CORONA_VEIL',
    id: 'coronaveil',
    name: 'Corona Veil',
    badge: 'Aurora Membrane',
    description: 'Layered aurora membranes roll quietly around a dark solar core.',
    defaultPreset: 'Polar Veil',
    file: 'corona-veil-engine.js',
    factoryName: 'createCoronaVeilEngine',
    factory: createCoronaVeilEngine,
    params: {
      veilCount: { type: 'select', label: 'Veil Count', options: [5, 6, 8, 10, 12], default: 8, section: 'geometry' },
      detail: { type: 'select', label: 'Membrane Detail', options: [48, 64, 80, 96], default: 80, section: 'geometry' },
      coreRadius: { type: 'number', label: 'Dark Core Radius', min: 1.5, max: 1.75, step: 0.01, default: 1.62, section: 'geometry' },
      veilSpread: { type: 'number', label: 'Veil Separation', min: 0.14, max: 0.3, step: 0.01, default: 0.24, section: 'motion' },
      twist: { type: 'number', label: 'Membrane Twist', min: 0.25, max: 1.1, step: 0.01, default: 0.68, section: 'motion' },
      waveAmp: { type: 'number', label: 'Membrane Wave', min: 0.02, max: 0.09, step: 0.005, default: 0.055, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Corona Breath', min: 0, max: 0.055, step: 0.005, default: 0.025, section: 'motion' },
      driftSpeed: { type: 'number', label: 'Veil Drift Speed', min: 0.06, max: 0.28, step: 0.01, default: 0.16, section: 'motion' },
      waveSpeed: { type: 'number', label: 'Membrane Wave Speed', min: 0.24, max: 0.72, step: 0.02, default: 0.48, section: 'motion' },
      coreColor: { type: 'color', label: 'Solar Core', default: '#02040a', section: 'colors', paletteRole: 'fixed' },
      veilColor: { type: 'color', label: 'Aurora Veil', default: '#62d8d2', section: 'colors' },
      accentColor: { type: 'color', label: 'Corona Accent', default: '#b9a7ff', section: 'colors' },
      opacity: { type: 'number', label: 'Veil Opacity', min: 0.16, max: 0.34, step: 0.01, default: 0.25, section: 'colors' },
      edgeGlow: { type: 'number', label: 'Membrane Edge Glow', min: 0.75, max: 1.7, step: 0.05, default: 1.25, section: 'colors' },
    },
  },
  {
    key: 'ECHO_RINGS',
    id: 'echorings',
    name: 'Echo Rings',
    badge: 'Signal Memory',
    description: 'Luminous wavefronts remember each pulse as they propagate and settle around a dark orb.',
    defaultPreset: 'First Contact',
    file: 'echo-rings-engine.js',
    factoryName: 'createEchoRingsEngine',
    factory: createEchoRingsEngine,
    params: {
      ringCount: { type: 'select', label: 'Idle Ring Count', options: [3, 5, 7, 9, 11], default: 7, section: 'geometry' },
      segments: { type: 'select', label: 'Ring Resolution', options: [64, 96, 128, 160, 192], default: 128, section: 'geometry' },
      radius: { type: 'number', label: 'Signal Sphere Radius', min: 1.4, max: 1.9, step: 0.02, default: 1.72, section: 'geometry' },
      lineWidth: { type: 'number', label: 'Signal Width', min: 0.8, max: 5, step: 0.1, default: 2.4, section: 'motion' },
      tiltSpread: { type: 'number', label: 'Ring Plane Spread', min: 0.15, max: 1.45, step: 0.02, default: 0.92, section: 'motion' },
      ringSpacing: { type: 'number', label: 'Wavefront Spacing', min: 0.35, max: 1.3, step: 0.01, default: 0.82, section: 'motion' },
      idleWave: { type: 'number', label: 'Idle Signal', min: 0, max: 1.2, step: 0.02, default: 0.42, section: 'motion' },
      pulseStrength: { type: 'number', label: 'Echo Strength', min: 0.4, max: 2.2, step: 0.05, default: 1.35, section: 'motion' },
      driftSpeed: { type: 'number', label: 'Ring Drift Speed', min: -0.4, max: 0.4, step: 0.01, default: 0.14, section: 'motion' },
      propagationSpeed: { type: 'number', label: 'Propagation Speed', min: 0.55, max: 1.45, step: 0.02, default: 1, section: 'motion' },
      baseColor: { type: 'color', label: 'Resting Rings', default: '#123039', section: 'colors', paletteRole: 'fixed' },
      echoColor: { type: 'color', label: 'Active Echo', default: '#42d9ff', section: 'colors' },
      coreColor: { type: 'color', label: 'Signal Core', default: '#e8fdff', section: 'colors', paletteRole: 'fixed' },
      glow: { type: 'number', label: 'Echo Radiance', min: 0.5, max: 2.8, step: 0.05, default: 1.65, section: 'colors' },
    },
  },
  {
    key: 'CHROMASPHERE',
    id: 'chromasphere',
    name: 'Chromasphere',
    badge: 'Liquid Chrome',
    description: 'A solid, opaque metal orb whose rippling surface reflects an analytic studio environment. The one engine here with a hard silhouette.',
    defaultPreset: 'Luminous Root',
    file: 'chromasphere-engine.js',
    factoryName: 'createChromasphereEngine',
    factory: createChromasphereEngine,
    params: {
      detail: { type: 'select', label: 'Surface Subdivision', options: [3, 4, 5, 6], default: 5, section: 'geometry' },
      rippleOctaves: { type: 'select', label: 'Ripple Detail', options: [1, 2, 3, 4], default: 3, section: 'geometry' },
      barCount: { type: 'select', label: 'Studio Light Count', options: [2, 3, 4, 6, 8], default: 4, section: 'geometry' },
      radius: { type: 'number', label: 'Orb Radius', min: 0.8, max: 2.2, step: 0.05, default: 1.45, section: 'motion' },
      rippleAmount: { type: 'number', label: 'Ripple Depth', min: 0, max: 0.4, step: 0.005, default: 0.14, section: 'motion' },
      rippleScale: { type: 'number', label: 'Ripple Frequency', min: 0.5, max: 5, step: 0.05, default: 1.9, section: 'motion' },
      flowSpeed: { type: 'number', label: 'Surface Flow Rate', min: 0, max: 1.5, step: 0.01, default: 0.3, section: 'motion' },
      spinSpeed: { type: 'number', label: 'Studio Spin Rate', min: -1, max: 1, step: 0.01, default: 0.12, section: 'motion' },
      breatheSpeed: { type: 'number', label: 'Breath Rate', min: 0, max: 1.5, step: 0.01, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Amplitude', min: 0, max: 0.12, step: 0.005, default: 0.03, section: 'motion' },
      pulseRipple: { type: 'number', label: 'Pulse Ripple', min: 0, max: 0.6, step: 0.02, default: 0.3, section: 'motion' },
      metalTint: { type: 'color', label: 'Metal Tint', default: '#dfe7ef', section: 'colors' },
      envTop: { type: 'color', label: 'Studio Key Light', default: '#8ea6c8', section: 'colors' },
      barColor: { type: 'color', label: 'Softbox Strips', default: '#fff6e0', section: 'colors' },
      envBottom: { type: 'color', label: 'Studio Floor', default: '#0a0d14', section: 'colors', paletteRole: 'fixed' },
      envIntensity: { type: 'number', label: 'Reflection Intensity', min: 0.2, max: 3.5, step: 0.05, default: 1.5, section: 'colors' },
      roughness: { type: 'number', label: 'Surface Roughness', min: 0, max: 0.8, step: 0.01, default: 0.14, section: 'colors' },
      fresnelPower: { type: 'number', label: 'Rim Falloff', min: 0.5, max: 6, step: 0.1, default: 3.2, section: 'colors' },
      fresnelGain: { type: 'number', label: 'Rim Brightness', min: 0, max: 1.5, step: 0.05, default: 0.55, section: 'colors' },
      barWidth: { type: 'number', label: 'Softbox Width', min: 0.05, max: 1.2, step: 0.01, default: 0.3, section: 'colors' },
    },
  },
  {
    key: 'VOCALIS',
    id: 'vocalis',
    name: 'Vocalis',
    badge: 'Vocal Diaphragm',
    description: 'Acoustic diaphragm rings articulate around a vocal glottis as circles, an iris, an ellipse, or globe latitudes.',
    defaultPreset: 'Vocal Resonator',
    file: 'vocalis-engine.js',
    factoryName: 'createVocalisEngine',
    factory: createVocalisEngine,
    params: {
      ringCount: { type: 'select', label: 'Diaphragm Rings', options: [4, 6, 8, 10, 12], default: 6, section: 'geometry' },
      ringLayout: { type: 'select', label: 'Ring Layout', options: ['circle', 'iris', 'ellipse', 'globe'], default: 'circle', section: 'geometry' },
      baseRadius: { type: 'number', label: 'Acoustic Radius', min: 0.8, max: 2.2, step: 0.05, default: 1.45, section: 'geometry' },
      diaphragmDepth: { type: 'number', label: 'Diaphragm Curvature', min: 0.2, max: 1.2, step: 0.05, default: 0.6, section: 'geometry' },
      lineWidth: { type: 'number', label: 'Ring Stroke Width', min: 1, max: 5, step: 0.1, default: 2.4, section: 'geometry' },
      apertureSize: { type: 'number', label: 'Glottal Aperture', min: 0.1, max: 0.9, step: 0.02, default: 0.35, section: 'motion' },
      vocalRipple: { type: 'number', label: 'Phonetic Ripple Depth', min: 0, max: 0.45, step: 0.01, default: 0.14, section: 'motion' },
      formantHarmonics: { type: 'select', label: 'Formant Harmonics', options: [2, 3, 4, 5, 6], default: 3, section: 'motion' },
      formantGain: { type: 'number', label: 'Formant Resonance Gain', min: 0.2, max: 2.5, step: 0.05, default: 1.2, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Vocal Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.04, section: 'motion' },
      articulationRate: { type: 'number', label: 'Speech Cadence Rate', min: 0.2, max: 3, step: 0.05, default: 1.2, section: 'motion' },
      plosiveSurge: { type: 'number', label: 'Plosive Burst Surge', min: 0.2, max: 2.5, step: 0.05, default: 1.4, section: 'motion' },
      coreColor: { type: 'color', label: 'Vocal Glottis Spark', default: '#ffffff', section: 'colors', paletteRole: 'fixed' },
      diaphragmColor: { type: 'color', label: 'Diaphragm Ribbons', default: '#00f2fe', section: 'colors' },
      formantColor: { type: 'color', label: 'Formant Crest Wave', default: '#a855f7', section: 'colors' },
      glowIntensity: { type: 'number', label: 'Acoustic Radiance', min: 0.4, max: 3, step: 0.1, default: 1.8, section: 'colors' },
      glottisDarkness: { type: 'number', label: 'Glottal Occlusion', min: 0.2, max: 1, step: 0.05, default: 0.8, section: 'colors' },
    },
  },
  {
    key: 'AETHERIA',
    id: 'aetheria',
    name: 'Aetheria',
    badge: 'Iridescent Luminescence',
    description: 'A tranquil chromatic fluid pearl with domain-warped surface wavelets, spectral chromatic dispersion rim, and submerged silk caustics.',
    defaultPreset: 'Siri Pearl',
    file: 'aetheria-engine.js',
    factoryName: 'createAetheriaEngine',
    factory: createAetheriaEngine,
    params: {
      sphereRadius: { type: 'number', label: 'Fluid Sphere Radius', min: 1, max: 2.2, step: 0.05, default: 1.55, section: 'geometry' },
      detail: { type: 'select', label: 'Mesh Resolution', options: [32, 48, 64, 96], default: 64, section: 'geometry' },
      causticRibbons: { type: 'select', label: 'Silk Caustic Ribbons', options: [1, 2, 3, 4], default: 3, section: 'geometry' },
      fluidSpeed: { type: 'number', label: 'Fluid Drift Rate', min: 0.1, max: 2, step: 0.05, default: 0.45, section: 'motion' },
      fluidWaveAmp: { type: 'number', label: 'Surface Wavelet Depth', min: 0, max: 0.35, step: 0.01, default: 0.12, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Radial Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.04, section: 'motion' },
      causticSwirl: { type: 'number', label: 'Caustic Swirl Dynamics', min: 0.1, max: 2, step: 0.05, default: 0.6, section: 'motion' },
      pulseGlow: { type: 'number', label: 'Radiant Pulse Surge', min: 0.2, max: 2.5, step: 0.05, default: 1.5, section: 'motion' },
      color1: { type: 'color', label: 'Electric Azure Tint', default: '#00f2fe', section: 'colors' },
      color2: { type: 'color', label: 'Secondary Violet Tone', default: '#a855f7', section: 'colors' },
      color3: { type: 'color', label: 'Ambient Magenta Depth', default: '#ff4fd8', section: 'colors' },
      rimColor: { type: 'color', label: 'Prismatic Dispersion Rim', default: '#ffed00', section: 'colors', paletteRole: 'fixed' },
      iridescence: { type: 'number', label: 'Spectral Split Strength', min: 0, max: 1.5, step: 0.05, default: 0.85, section: 'colors' },
      glowIntensity: { type: 'number', label: 'Luminous Bloom Radiance', min: 0.4, max: 3, step: 0.1, default: 1.8, section: 'colors' },
    },
  },
  {
    key: 'SUPERPOSITION',
    id: 'superposition',
    name: 'Superposition',
    badge: 'Quantum Wavepacket',
    description: 'Coherent quantum orbital probability lobes expand and beat with complex phase interference, collapsing on measurement.',
    defaultPreset: 'Quantum Superposition',
    file: 'superposition-engine.js',
    factoryName: 'createSuperpositionEngine',
    factory: createSuperpositionEngine,
    params: {
      sampleDensity: { type: 'select', label: 'Quantum Samples', options: [3072, 6144, 9216, 12288], default: 6144, section: 'geometry' },
      orbitalScale: { type: 'number', label: 'Orbital Envelope', min: 0.8, max: 2.2, step: 0.05, default: 1.45, section: 'geometry' },
      nucleusRadius: { type: 'number', label: 'Nucleus Radius', min: 0.15, max: 0.8, step: 0.02, default: 0.38, section: 'geometry' },
      stateMode: { type: 'select', label: 'Orbital Eigenstate', options: ['hybrid_sp', 'd_orbital', 'f_orbital', 'chiral_vortex'], default: 'd_orbital', section: 'geometry' },
      pointSize: { type: 'number', label: 'Sample Point Size', min: 1, max: 6, step: 0.1, default: 2.8, section: 'motion' },
      coherence: { type: 'number', label: 'Phase Coherence', min: 0, max: 1, step: 0.02, default: 0.85, section: 'motion' },
      waveExcursion: { type: 'number', label: 'Lobe Excursion Depth', min: 0.1, max: 1.2, step: 0.05, default: 0.45, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Probability Breath', min: 0, max: 0.12, step: 0.005, default: 0.04, section: 'motion' },
      collapseStrength: { type: 'number', label: 'Measurement Collapse', min: 0.2, max: 2.5, step: 0.05, default: 1.4, section: 'motion' },
      phaseRate: { type: 'number', label: 'Precession Velocity', min: 0.2, max: 3, step: 0.05, default: 1.1, section: 'motion' },
      psiColorA: { type: 'color', label: 'Phase Real (+)', default: '#38bdf8', section: 'colors' },
      psiColorB: { type: 'color', label: 'Phase Imaginary (-)', default: '#f43f5e', section: 'colors' },
      nodalColor: { type: 'color', label: 'Nodal Surface Spark', default: '#e0f2fe', section: 'colors' },
      glowIntensity: { type: 'number', label: 'Wavepacket Radiance', min: 0.4, max: 3, step: 0.1, default: 1.8, section: 'colors' },
    },
  },
  {
    key: 'SYNTHESIS',
    id: 'synthesis',
    name: 'Synthesis',
    badge: 'Harmonic Fluid Fusion',
    description: 'Four luminous fluid bodies orbit in celestial figure-8 choreography, organically fusing with liquid bridges, gravitational filaments, and stardust.',
    defaultPreset: 'Gemini Harmonic',
    file: 'synthesis-engine.js',
    factoryName: 'createSynthesisEngine',
    factory: createSynthesisEngine,
    params: {
      envelopeRadius: { type: 'number', label: 'Celestial Sphere Bounds', min: 1, max: 2.2, step: 0.05, default: 1.6, section: 'geometry' },
      coreRadius: { type: 'number', label: 'Fluid Core Size', min: 0.2, max: 0.65, step: 0.02, default: 0.38, section: 'geometry' },
      filamentCount: { type: 'select', label: 'Gravitational Filaments', options: [0, 4, 6, 8], default: 6, section: 'geometry' },
      stardustDensity: { type: 'select', label: 'Ambient Stardust Motes', options: [32, 64, 128, 256], default: 64, section: 'geometry' },
      orbitSpread: { type: 'number', label: 'Orbital Chord Separation', min: 0.2, max: 1.2, step: 0.02, default: 0.75, section: 'motion' },
      orbitSpeed: { type: 'number', label: 'Choreography Velocity', min: 0.1, max: 2.5, step: 0.05, default: 0.55, section: 'motion' },
      fusionTension: { type: 'number', label: 'Liquid Bridge Attraction', min: 0.1, max: 1.5, step: 0.05, default: 0.65, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Harmonic Breath Depth', min: 0, max: 0.1, step: 0.005, default: 0.035, section: 'motion' },
      coalesceSurge: { type: 'number', label: 'Unified Synthesis Pulse', min: 0.2, max: 2.5, step: 0.05, default: 1.4, section: 'motion' },
      color1: { type: 'color', label: 'Modality Azure (Core A)', default: '#4285f4', section: 'colors' },
      color2: { type: 'color', label: 'Modality Coral (Core B)', default: '#ea4335', section: 'colors' },
      color3: { type: 'color', label: 'Modality Amber (Core C)', default: '#fbbc05', section: 'colors' },
      color4: { type: 'color', label: 'Modality Mint (Core D)', default: '#34a853', section: 'colors' },
      veilColor: { type: 'color', label: 'Celestial Veil Glow', default: '#1e1b4b', section: 'colors', paletteRole: 'fixed' },
      glowIntensity: { type: 'number', label: 'Volumetric Radiance', min: 0.4, max: 3, step: 0.1, default: 1.8, section: 'colors' },
    },
  },
  {
    key: 'FERRO_TRAILS',
    id: 'ferrotrails',
    name: 'Ferro Trails',
    badge: 'Magnetic Fluid & Arc Trails',
    description: 'An oval ferrofluid core pulsating with organic magnetic crests, wrapped in sweeping luminous ribbon trails and glowing velocity arcs.',
    defaultPreset: 'Magnetic Nebula Oval',
    file: 'ferro-trails-engine.js',
    factoryName: 'createFerroTrailsEngine',
    factory: createFerroTrailsEngine,
    params: {
      ovalRatio: { type: 'number', label: 'Orb Oval Aspect Ratio', min: 0.8, max: 1.6, step: 0.02, default: 1.25, section: 'geometry' },
      coreRadius: { type: 'number', label: 'Ferrofluid Core Radius', min: 0.8, max: 2, step: 0.05, default: 1.35, section: 'geometry' },
      trailCount: { type: 'select', label: 'Sweeping Arc Trails', options: [6, 12, 18, 24], default: 12, section: 'geometry' },
      trailDetail: { type: 'select', label: 'Trail Arc Resolution', options: [60, 90, 120], default: 90, section: 'geometry' },
      particleMotes: { type: 'select', label: 'Magnetic Mote Swarm', options: [32, 64, 128], default: 64, section: 'geometry' },
      arcCurvature: { type: 'number', label: 'Arc Curvature Bend', min: 0.2, max: 2, step: 0.05, default: 0.85, section: 'motion' },
      trailSweepSpeed: { type: 'number', label: 'Trail Orbital Velocity', min: 0.1, max: 2.5, step: 0.05, default: 0.65, section: 'motion' },
      magneticSpikes: { type: 'number', label: 'Magnetic Crest Excursion', min: 0, max: 0.45, step: 0.01, default: 0.16, section: 'motion' },
      spikeFrequency: { type: 'number', label: 'Ferro Spike Density', min: 1, max: 6, step: 0.1, default: 3.2, section: 'motion' },
      fluidViscosity: { type: 'number', label: 'Fluid Viscous Tension', min: 0.2, max: 2.5, step: 0.05, default: 0.9, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Magnetic Breathing Depth', min: 0, max: 0.12, step: 0.005, default: 0.035, section: 'motion' },
      pulseSurge: { type: 'number', label: 'Speech Pulse Surge', min: 0.2, max: 2.5, step: 0.05, default: 1.5, section: 'motion' },
      colorLiquid: { type: 'color', label: 'Ferrofluid Liquid Body', default: '#0b1021', section: 'colors' },
      colorCrest: { type: 'color', label: 'Magnetic Crest Radiance', default: '#00f0ff', section: 'colors' },
      colorTrail1: { type: 'color', label: 'Trail Head Azure Neon', default: '#38bdf8', section: 'colors' },
      colorTrail2: { type: 'color', label: 'Trail Tail Violet Neon', default: '#a855f7', section: 'colors' },
      colorCore: { type: 'color', label: 'Magnetic Spark Core', default: '#ffffff', section: 'colors', paletteRole: 'fixed' },
      glowIntensity: { type: 'number', label: 'Volumetric Arc Radiance', min: 0.4, max: 3, step: 0.1, default: 1.8, section: 'colors' },
    },
  },
];
