import { createFluxEngine } from '../../engines/flux-engine.js';
import { createAqueousEngine } from '../../engines/aqueous-engine.js';
import { createCurlDriftEngine } from '../../engines/curl-drift-engine.js';
import { createMurmurationEngine } from '../../engines/murmuration-engine.js';
import { createFilamentEngine } from '../../engines/filament-engine.js';

export const SIMULATION_ENGINES = [
  {
    key: 'FLUX',
    id: 'flux',
    name: 'Flux Ribbon',
    badge: 'Travelling Wave',
    description: 'A bundle of glowing strands streaming in a travelling wave, fanning apart and converging into bright knots. Renders as a wide ribbon or wrapped onto an orb.',
    defaultPreset: 'Neon Voice Ribbon',
    file: 'flux-engine.js',
    factoryName: 'createFluxEngine',
    factory: createFluxEngine,
    params: {
      layout: { type: 'select', label: 'Layout', options: ['ribbon', 'orb'], default: 'ribbon', section: 'geometry' },
      strands: { type: 'number', label: 'Strand Count', min: 6, max: 64, step: 1, default: 28, section: 'geometry' },
      segments: { type: 'number', label: 'Strand Resolution', min: 40, max: 300, step: 10, default: 160, section: 'geometry' },
      bandSpread: { type: 'number', label: 'Band Spread', min: 0, max: 3, step: 0.05, default: 1.1, section: 'geometry' },
      ribbonWidth: { type: 'number', label: 'Ribbon Width', min: 4, max: 24, step: 0.5, default: 14, section: 'geometry' },
      twist: { type: 'number', label: 'Orb Twist', min: -2, max: 2, step: 0.05, default: 0.6, section: 'geometry' },
      sparkleDensity: { type: 'number', label: 'Sparkle Density', min: 0, max: 0.2, step: 0.005, default: 0.03, section: 'geometry' },
      amplitude: { type: 'number', label: 'Wave Amplitude', min: 0, max: 2.5, step: 0.05, default: 0.85, section: 'motion' },
      wavelength: { type: 'number', label: 'Wavelength', min: 0.1, max: 1.5, step: 0.02, default: 0.42, section: 'motion' },
      phaseSpread: { type: 'number', label: 'Strand Phase Spread', min: 0, max: 8, step: 0.1, default: 2.4, section: 'motion' },
      depth: { type: 'number', label: 'Depth Separation', min: 0, max: 5, step: 0.1, default: 2.2, section: 'motion' },
      turbulence: { type: 'number', label: 'Turbulence', min: 0, max: 1.5, step: 0.05, default: 0.35, section: 'motion' },
      flowSpeed: { type: 'number', label: 'Flow Speed', min: -3, max: 3, step: 0.05, default: 0.9, section: 'motion' },
      colorA: { type: 'color', label: 'Leading Colour', default: '#ff4fd8', section: 'colors' },
      colorB: { type: 'color', label: 'Mid Colour', default: '#a86bff', section: 'colors' },
      colorC: { type: 'color', label: 'Trailing Colour', default: '#4fd0ff', section: 'colors' },
      glow: { type: 'number', label: 'Strand Glow', min: 0.2, max: 3, step: 0.05, default: 2.1, section: 'colors' },
      sparkleSize: { type: 'number', label: 'Sparkle Size', min: 0.5, max: 8, step: 0.1, default: 2.2, section: 'colors' },
      sparkleBrightness: { type: 'number', label: 'Sparkle Brightness', min: 0, max: 5, step: 0.1, default: 2.4, section: 'colors' },
    },
  },
  {
    key: 'AQUEOUS',
    id: 'aqueous',
    name: 'Aqueous',
    badge: 'Refractive Body',
    description: 'A soft, luminous body with migrating liquid contours, glassy depth, and a calm physical presence.',
    defaultPreset: 'Stillwater Listener',
    file: 'aqueous-engine.js',
    factoryName: 'createAqueousEngine',
    factory: createAqueousEngine,
    params: {
      detail: { type: 'select', label: 'Surface Detail', options: [3, 4, 5, 6], default: 5, section: 'geometry' },
      radius: { type: 'number', label: 'Body Radius', min: 0.8, max: 2.2, step: 0.05, default: 1.5, section: 'geometry' },
      displaceOctaves: { type: 'select', label: 'Surface Layers', options: [1, 2, 3, 4], default: 3, section: 'geometry' },
      displaceAmount: { type: 'number', label: 'Liquid Displacement', min: 0, max: 0.5, step: 0.01, default: 0.18, section: 'motion' },
      displaceScale: { type: 'number', label: 'Surface Character', min: 0.3, max: 4, step: 0.05, default: 1.4, section: 'motion' },
      breatheSpeed: { type: 'number', label: 'Breathing Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breathing Depth', min: 0, max: 0.15, step: 0.005, default: 0.04, section: 'motion' },
      driftSpeed: { type: 'number', label: 'Surface Drift Speed', min: 0, max: 1.5, step: 0.05, default: 0.25, section: 'motion' },
      pulseDeform: { type: 'number', label: 'Pulse Deformation', min: 0, max: 0.6, step: 0.02, default: 0.25, section: 'motion' },
      bodyColor: { type: 'color', label: 'Body Tint', default: '#2dd4bf', section: 'colors' },
      coreColor: { type: 'color', label: 'Inner Light', default: '#ffed00', section: 'colors' },
      transmission: { type: 'number', label: 'Glassy Transmission', min: 0, max: 1, step: 0.01, default: 0.85, section: 'colors' },
      thickness: { type: 'number', label: 'Optical Thickness', min: 0, max: 3, step: 0.05, default: 1.2, section: 'colors' },
      ior: { type: 'number', label: 'Refraction Index', min: 1, max: 2.4, step: 0.01, default: 1.42, section: 'colors' },
      roughness: { type: 'number', label: 'Surface Roughness', min: 0, max: 1, step: 0.01, default: 0.15, section: 'colors' },
      coreIntensity: { type: 'number', label: 'Inner Light Strength', min: 0, max: 4, step: 0.1, default: 1.6, section: 'colors' },
      fresnelPower: { type: 'number', label: 'Rim Falloff', min: 0.5, max: 6, step: 0.1, default: 2.5, section: 'colors' },
    },
  },
  {
    key: 'CURL_DRIFT',
    id: 'curldrift',
    name: 'Curl Drift',
    badge: 'Advected Flow',
    description: 'Directional light ribbons braid around a spherical shell inside a deterministic curl field.',
    defaultPreset: 'Blue Current',
    file: 'curl-drift-engine.js',
    factoryName: 'createCurlDriftEngine',
    factory: createCurlDriftEngine,
    params: {
      streamCount: { type: 'select', label: 'Stream Count', options: [32, 48, 64, 96, 128], default: 64, section: 'geometry' },
      trailLength: { type: 'select', label: 'Trail Length', options: [16, 32, 48, 64, 96], default: 48, section: 'geometry' },
      shellRadius: { type: 'number', label: 'Flow Shell Radius', min: 0.8, max: 2.4, step: 0.05, default: 1.6, section: 'geometry' },
      lineWidth: { type: 'number', label: 'Stream Width', min: 0.5, max: 5, step: 0.1, default: 1.6, section: 'motion' },
      fieldScale: { type: 'number', label: 'Curl Field Scale', min: 0.2, max: 3, step: 0.05, default: 0.9, section: 'motion' },
      fieldEvolveSpeed: { type: 'number', label: 'Field Evolution Speed', min: 0, max: 1, step: 0.01, default: 0.12, section: 'motion' },
      flowSpeed: { type: 'number', label: 'Stream Flow Speed', min: 0.1, max: 3, step: 0.05, default: 0.8, section: 'motion' },
      shellBinding: { type: 'number', label: 'Shell Binding', min: 0, max: 2, step: 0.05, default: 0.7, section: 'motion' },
      swirl: { type: 'number', label: 'Directional Swirl', min: 0, max: 1.5, step: 0.05, default: 0.3, section: 'motion' },
      lifetimeJitter: { type: 'number', label: 'Lifetime Variation', min: 0, max: 1, step: 0.05, default: 0.5, section: 'motion' },
      coverage: { type: 'number', label: 'Shell Coverage', min: 0.05, max: 1, step: 0.01, default: 1, section: 'motion' },
      coverageCenter: { type: 'number', label: 'Coverage Latitude', min: -1, max: 1, step: 0.02, default: 0, section: 'motion' },
      headColor: { type: 'color', label: 'Leading Light', default: '#00f2fe', section: 'colors' },
      midColor: { type: 'color', label: 'Mid-Trail Light', default: '#4f8cff', section: 'colors' },
      tailColor: { type: 'color', label: 'Trailing Light', default: '#a855f7', section: 'colors' },
      glowIntensity: { type: 'number', label: 'Flow Radiance', min: 0.4, max: 3, step: 0.1, default: 1.3, section: 'colors' },
      tailFade: { type: 'number', label: 'Trail Fade', min: 0, max: 1, step: 0.05, default: 0.7, section: 'colors' },
    },
  },
  {
    key: 'MURMURATION',
    id: 'murmuration',
    name: 'Murmuration',
    badge: 'Emergent Swarm',
    description: 'A living cloud of agents gathers, separates, and regroups as if weighing several possibilities.',
    defaultPreset: 'Deliberation Cloud',
    file: 'murmuration-engine.js',
    factoryName: 'createMurmurationEngine',
    factory: createMurmurationEngine,
    params: {
      agentCount: { type: 'select', label: 'Agent Count', options: [128, 256, 384, 512], default: 256, section: 'geometry' },
      shellRadius: { type: 'number', label: 'Swarm Shell Radius', min: 0.8, max: 2.6, step: 0.05, default: 1.7, section: 'geometry' },
      trailLength: { type: 'select', label: 'Ghost Trail Length', options: [0, 4, 8, 16], default: 8, section: 'geometry' },
      pointSize: { type: 'number', label: 'Agent Size', min: 0.5, max: 6, step: 0.1, default: 2, section: 'motion' },
      cohesion: { type: 'number', label: 'Cohesion', min: 0, max: 1, step: 0.01, default: 0.4, section: 'motion' },
      separation: { type: 'number', label: 'Separation', min: 0, max: 1, step: 0.01, default: 0.55, section: 'motion' },
      alignment: { type: 'number', label: 'Alignment', min: 0, max: 1, step: 0.01, default: 0.35, section: 'motion' },
      neighbourRadius: { type: 'number', label: 'Neighbour Radius', min: 0.1, max: 1.5, step: 0.05, default: 0.55, section: 'motion' },
      attractorPull: { type: 'number', label: 'Attractor Pull', min: 0, max: 2, step: 0.05, default: 0.5, section: 'motion' },
      shellBinding: { type: 'number', label: 'Shell Binding', min: 0, max: 2, step: 0.05, default: 0.8, section: 'motion' },
      agentSpeed: { type: 'number', label: 'Agent Speed', min: 0.1, max: 3, step: 0.05, default: 1, section: 'motion' },
      damping: { type: 'number', label: 'Collective Damping', min: 0.8, max: 0.995, step: 0.005, default: 0.96, section: 'motion' },
      coreColor: { type: 'color', label: 'Core Agent Colour', default: '#ffed00', section: 'colors' },
      edgeColor: { type: 'color', label: 'Shell Agent Colour', default: '#00f2fe', section: 'colors' },
      glowIntensity: { type: 'number', label: 'Swarm Radiance', min: 0.4, max: 3, step: 0.1, default: 1.4, section: 'colors' },
      trailFade: { type: 'number', label: 'Ghost Trail Fade', min: 0, max: 1, step: 0.05, default: 0.6, section: 'colors' },
    },
  },
  {
    key: 'FILAMENT',
    id: 'filament',
    name: 'Filament Lattice',
    badge: 'Spring Network',
    description: 'Signals travel through an elastic geodesic network, reflect, interfere, and ring down.',
    defaultPreset: 'Signal Lattice',
    file: 'filament-engine.js',
    factoryName: 'createFilamentEngine',
    factory: createFilamentEngine,
    params: {
      subdivision: { type: 'select', label: 'Lattice Subdivision', options: [1, 2, 3], default: 2, section: 'geometry' },
      radius: { type: 'number', label: 'Rest Sphere Radius', min: 0.8, max: 2.4, step: 0.05, default: 1.6, section: 'geometry' },
      nodeSize: { type: 'number', label: 'Node Size', min: 0, max: 0.1, step: 0.005, default: 0.03, section: 'motion' },
      lineWidth: { type: 'number', label: 'Filament Width', min: 0.5, max: 5, step: 0.1, default: 1.8, section: 'motion' },
      stiffness: { type: 'number', label: 'Spring Stiffness', min: 0.05, max: 1, step: 0.01, default: 0.35, section: 'motion' },
      damping: { type: 'number', label: 'Ring-down Damping', min: 0.8, max: 0.995, step: 0.005, default: 0.94, section: 'motion' },
      tether: { type: 'number', label: 'Rest Tether', min: 0, max: 0.5, step: 0.01, default: 0.06, section: 'motion' },
      pulseStrength: { type: 'number', label: 'Pulse Impulse', min: 0, max: 1.5, step: 0.05, default: 0.5, section: 'motion' },
      idleExcitation: { type: 'number', label: 'Idle Excitation', min: 0, max: 0.3, step: 0.01, default: 0.05, section: 'motion' },
      waveSpeed: { type: 'number', label: 'Wave Speed', min: 0, max: 2, step: 0.05, default: 0.4, section: 'motion' },
      displacementGlow: { type: 'number', label: 'Displacement Radiance', min: 0, max: 3, step: 0.1, default: 1.5, section: 'colors' },
      restColor: { type: 'color', label: 'Resting Filaments', default: '#1e293b', section: 'colors', paletteRole: 'fixed' },
      activeColor: { type: 'color', label: 'Active Signal', default: '#ffed00', section: 'colors' },
      nodeColor: { type: 'color', label: 'Node Light', default: '#ffffff', section: 'colors', paletteRole: 'fixed' },
    },
  },
];
