
export const ANALYTIC_ENGINES = [
  {
    key: 'TESSERACT',
    id: 'tesseract',
    name: 'Tesseract',
    badge: 'Hypercube Projection',
    description: 'A four-dimensional cube projected into 3D. The inner and outer cubes trade places as it turns through the fourth dimension.',
    defaultPreset: 'Canonical Hypercube',
    file: 'tesseract-engine.js',
    factoryName: 'createTesseractEngine',
    params: {
      color1: { type: 'color', label: 'Outer Cube Edges', default: '#ffed00', section: 'colors' },
      color2: { type: 'color', label: 'Inner Cube Edges', default: '#00f0ff', section: 'colors' },
      colorStrut: { type: 'color', label: 'Corner Struts', default: '#ffffff', section: 'colors', paletteRole: 'fixed' },
      nodeColor: { type: 'color', label: 'Corner Vertex Nodes', default: '#ffffff', section: 'colors', paletteRole: 'fixed' },
      cellColor: { type: 'color', label: 'Glass Facet Tint', default: '#ffed00', section: 'colors' },
      edgeGlow: { type: 'number', label: 'Edge Radiance', min: 0.5, max: 3.5, step: 0.1, default: 1.2, section: 'colors' },
      projection: { type: 'select', label: '4D Viewing Axis', options: ['cell_first', 'face_first', 'edge_first', 'vertex_first'], default: 'cell_first', section: 'geometry' },
      edgeMode: { type: 'select', label: 'Edge Architecture', options: ['sketch', 'cubes', 'outer_struts', 'inner_struts', 'struts'], default: 'sketch', section: 'geometry' },
      innerScale: { type: 'number', label: 'Inner Cube Ratio', min: 0.25, max: 0.75, step: 0.01, default: 0.48, section: 'geometry' },
      cubeSize: { type: 'number', label: 'Hypercube Scale', min: 0.6, max: 2.5, step: 0.05, default: 1.35, section: 'geometry' },
      edgeWidth: { type: 'number', label: 'Edge Line Width', min: 1, max: 6, step: 0.2, default: 2.6, section: 'geometry' },
      nodeSize: { type: 'number', label: 'Corner Vertex Nodes', min: 0, max: 0.12, step: 0.005, default: 0.038, section: 'geometry' },
      cellOpacity: { type: 'number', label: 'Glass Facet Opacity', min: 0, max: 0.4, step: 0.01, default: 0, section: 'geometry' },
      motionMode: { type: 'select', label: 'Motion Dynamic', options: ['sketch3d', 'hyperfold', 'pulse', 'true4d'], default: 'sketch3d', section: 'motion' },
      rotSpeedX: { type: 'number', label: '3D Rotation Pitch', min: -2, max: 2, step: 0.05, default: 0.25, section: 'motion' },
      rotSpeedY: { type: 'number', label: '3D Rotation Yaw', min: -2, max: 2, step: 0.05, default: 0.5, section: 'motion' },
      pulseSpeed: { type: 'number', label: 'Fold / Pulse Speed', min: 0.2, max: 3, step: 0.1, default: 1.2, section: 'motion' },
      rotSpeedXW: { type: 'number', label: '4D Rotation XW', min: -2, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      rotSpeedYW: { type: 'number', label: '4D Rotation YW', min: -2, max: 2, step: 0.05, default: 0.45, section: 'motion' },
    },
  },
  {
    key: 'MOIRE',
    id: 'moire',
    name: 'Chiral Moiré',
    badge: 'Optical String Art',
    description: 'String art in three dimensions: straight lines strung between two rings and twisted until their crossings make moiré. Nine shapes, from funnels to saddles.',
    defaultPreset: '1. Chiral Square Vortex',
    file: 'moire-engine.js',
    factoryName: 'createMoireEngine',
    params: {
      archetype: { type: 'select', label: 'Grid Archetype', options: ['meridian_beat', 'lattice_beat', 'helix_beat'], default: 'meridian_beat', section: 'geometry' },
      scale: { type: 'number', label: 'Orb Scale', min: 0.8, max: 3, step: 0.05, default: 2.2, section: 'geometry' },
      lineDensity: { type: 'number', label: 'Meridians', min: 8, max: 60, step: 1, default: 28, section: 'geometry' },
      beatOffset: { type: 'number', label: 'Beat Offset', min: -8, max: 8, step: 1, default: 2, section: 'geometry' },
      latBands: { type: 'number', label: 'Latitude Rings', min: 0, max: 24, step: 1, default: 8, section: 'geometry' },
      twistAngle: { type: 'number', label: 'Chiral Twist Angle', min: -1.5, max: 1.5, step: 0.02, default: 0.72, section: 'geometry' },
      shellGap: { type: 'number', label: 'Shell Gap', min: 0.55, max: 0.99, step: 0.01, default: 0.9, section: 'motion' },
      lineWidth: { type: 'number', label: 'Line Stroke Thickness', min: 0.5, max: 6, step: 0.1, default: 1.6, section: 'geometry' },
      lineColor: { type: 'color', label: 'Line Color', default: '#7fe9ff', section: 'colors' },
      lineGlow: { type: 'number', label: 'Line Glow / Radiance', min: 0.5, max: 3, step: 0.1, default: 1, section: 'colors' },
      motionMode: { type: 'select', label: 'Motion Dynamic', options: ['counter_spin', 'orbit_3d', 'wave_pulse', 'interactive_tilt'], default: 'counter_spin', section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Spin Rate', min: -2, max: 2, step: 0.05, default: 0.55, section: 'motion' },
      rotSpeedX: { type: 'number', label: '3D Pitch Rotation', min: -2, max: 2, step: 0.02, default: 0.06, section: 'motion' },
      rotSpeedY: { type: 'number', label: '3D Yaw Rotation', min: -2, max: 2, step: 0.02, default: 0.18, section: 'motion' },
      rotSpeedZ: { type: 'number', label: '3D Roll Rotation', min: -2, max: 2, step: 0.02, default: 0, section: 'motion' },
      breatheSpeed: { type: 'number', label: 'Shell Breath Rate', min: 0, max: 2.5, step: 0.05, default: 0.6, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breathing Amplitude', min: 0, max: 0.25, step: 0.01, default: 0.05, section: 'motion' },
      twistSpeed: { type: 'number', label: 'Chiral Winding Speed', min: 0, max: 2, step: 0.05, default: 0.15, section: 'motion' },
      tiltStrength: { type: 'number', label: 'Mouse Parallax Depth', min: 0, max: 1, step: 0.05, default: 0.35, section: 'motion' },
    },
  },
  {
    key: 'AURIS',
    id: 'auris',
    name: 'Auris',
    badge: 'Lit Polyhedra',
    description: 'Geodesic polyhedra and Kepler compounds in wireframe and facet, lit from one side with line hatching.',
    defaultPreset: 'Geodesic Stellated Sun',
    file: 'auris-engine.js',
    factoryName: 'createAurisEngine',
    params: {
      archetype: { type: 'select', label: 'Crystalline Archetype', options: ['geodesic', 'cubic_compound', 'nested_square', 'nested_hex', 'nested_pentagon', 'nested_triangle'], default: 'geodesic', section: 'geometry' },
      scale: { type: 'number', label: 'Polyhedron Scale', min: 0.8, max: 2.5, step: 0.05, default: 1.4, section: 'geometry' },
      stellaHeight: { type: 'number', label: 'Stellation / 3D Depth', min: 0, max: 1.2, step: 0.02, default: 0.45, section: 'geometry' },
      twistAngle: { type: 'number', label: 'Per-Layer Rotation', min: 0.02, max: 0.35, step: 0.01, default: 0.14, section: 'geometry' },
      wireWidth: { type: 'number', label: 'Contour Line Width', min: 1, max: 5, step: 0.2, default: 2.4, section: 'geometry' },
      lightColor: { type: 'color', label: 'Directional Light Tint', default: '#ffea79', section: 'colors' },
      facetColor: { type: 'color', label: 'Facet Base Shading', default: '#1e293b', section: 'colors', paletteRole: 'fixed' },
      wireColor: { type: 'color', label: 'Glowing Edge Contours', default: '#fef08a', section: 'colors' },
      shadowColor: { type: 'color', label: 'Shadow Ambient Tone', default: '#090d16', section: 'colors', paletteRole: 'fixed' },
      wireGlow: { type: 'number', label: 'Wire Radiance', min: 0.5, max: 3.5, step: 0.1, default: 1.3, section: 'colors' },
      hatchStrength: { type: 'number', label: 'Architectural Hatching', min: 0, max: 1, step: 0.05, default: 0.85, section: 'colors' },
      lightYaw: { type: 'number', label: 'Light Direction (Azimuth)', min: 0, max: 360, step: 5, default: 45, section: 'motion' },
      lightPitch: { type: 'number', label: 'Light Elevation (Altitude)', min: -85, max: 85, step: 5, default: 35, section: 'motion' },
      lightIntensity: { type: 'number', label: 'Illumination Power', min: 0.4, max: 3.5, step: 0.1, default: 1.6, section: 'motion' },
      hatchDensity: { type: 'number', label: 'Hatching Frequency', min: 6, max: 50, step: 1, default: 18, section: 'motion' },
      rotSpeedX: { type: 'number', label: '3D Rotation Pitch', min: -2, max: 2, step: 0.05, default: 0.2, section: 'motion' },
      rotSpeedY: { type: 'number', label: '3D Rotation Yaw', min: -2, max: 2, step: 0.05, default: 0.45, section: 'motion' },
      rotSpeedZ: { type: 'number', label: '3D Rotation Roll', min: -2, max: 2, step: 0.05, default: 0.1, section: 'motion' },
    },
  },
  {
    key: 'HOPF',
    id: 'hopf',
    name: 'Hopf Fibration',
    badge: 'Clifford Torus',
    description: 'Stereographic projection of the 3-sphere S³ to R³ generating nested Villarceau circle fibers and Clifford toroidal inversions.',
    defaultPreset: 'Clifford Vortex',
    file: 'hopf-engine.js',
    factoryName: 'createHopfEngine',
    params: {
      color1: { type: 'color', label: 'Core Villarceau Ring', default: '#ffed00', section: 'colors' },
      color2: { type: 'color', label: 'Outer Toroidal Shell', default: '#a855f7', section: 'colors' },
      accentColor: { type: 'color', label: 'Streamline Sparkles', default: '#00f2fe', section: 'colors' },
      glowIntensity: { type: 'number', label: 'Fiber Radiance', min: 0.4, max: 3.5, step: 0.1, default: 1.5, section: 'colors' },
      fiberCount: { type: 'select', label: 'Fiber Circle Count', options: [16, 24, 32, 48], default: 32, section: 'geometry' },
      torusRadius: { type: 'number', label: 'Major Torus Radius (R)', min: 0.8, max: 2.8, step: 0.05, default: 1.75, section: 'geometry' },
      tubeRadius: { type: 'number', label: 'Minor Torus Radius (r)', min: 0.3, max: 1.6, step: 0.05, default: 0.85, section: 'geometry' },
      lineWidth: { type: 'number', label: 'Fiber Ribbon Width', min: 1, max: 6, step: 0.5, default: 2.8, section: 'geometry' },
      cliffordSpeed: { type: 'number', label: 'Clifford 4D Inversion Rate', min: 0, max: 2.5, step: 0.05, default: 0.7, section: 'motion' },
      flowSpeed: { type: 'number', label: 'Stream Flow Velocity', min: 0.1, max: 3, step: 0.1, default: 1.2, section: 'motion' },
      twistHarmonics: { type: 'number', label: 'Winding Harmonics', min: 1, max: 5, step: 1, default: 2, section: 'motion' },
    },
  },
  {
    key: 'POLYTOPE',
    id: 'polytope',
    name: 'Star Polytope',
    badge: 'Star Tetrahedron',
    description: 'Two interlocked tetrahedra turning against each other around a Kepler–Poinsot star, with dispersion on the facets.',
    defaultPreset: 'Gold Star Tetrahedron',
    file: 'polytope-engine.js',
    factoryName: 'createPolytopeEngine',
    params: {
      color1: { type: 'color', label: 'Primary Star (Yang)', default: '#ffed00', section: 'colors' },
      color2: { type: 'color', label: 'Counter Star (Yin)', default: '#ec4899', section: 'colors' },
      coreColor: { type: 'color', label: 'Divine Core Spark', default: '#ffffff', section: 'colors', paletteRole: 'fixed' },
      wireColor: { type: 'color', label: 'Geodesic Wireframe', default: '#00f0ff', section: 'colors' },
      wireGlow: { type: 'number', label: 'Wireframe Luma', min: 0.5, max: 3.5, step: 0.1, default: 1.8, section: 'colors' },
      facetDispersion: { type: 'number', label: 'Prismatic Dispersion', min: 0, max: 1.5, step: 0.05, default: 0.75, section: 'colors' },
      polytopeType: { type: 'select', label: 'Shape', options: ['merkabah', 'kepler_star', 'icosa_stellation'], optionLabels: { merkabah: 'Star tetrahedron', kepler_star: 'Kepler star', icosa_stellation: 'Stellated icosahedron' }, default: 'merkabah', section: 'geometry' },
      scale: { type: 'number', label: 'Polytope Outer Radius', min: 0.8, max: 2.6, step: 0.05, default: 1.65, section: 'geometry' },
      coreRadius: { type: 'number', label: 'Divine Core Radius', min: 0.15, max: 0.9, step: 0.05, default: 0.45, section: 'geometry' },
      wireThickness: { type: 'number', label: 'Geodesic Line Width', min: 1, max: 6, step: 0.5, default: 3, section: 'geometry' },
      rotRateA: { type: 'number', label: 'Star A Spin Velocity', min: -2, max: 2, step: 0.05, default: 0.6, section: 'motion' },
      rotRateB: { type: 'number', label: 'Star B Counter-Spin', min: -2, max: 2, step: 0.05, default: -0.6, section: 'motion' },
    },
  },
  {
    key: 'NEBULA',
    id: 'nebula',
    name: 'Gyroid Nebula',
    badge: 'Volumetric Raymarching',
    description: 'A gyroid surface raymarched as a glowing volume inside a soft atmospheric shell, with chromatic aberration and fine sparkle.',
    defaultPreset: 'Aurora Core',
    file: 'nebula-engine.js',
    factoryName: 'createNebulaEngine',
    params: {
      color1: { type: 'color', label: 'Primary Gradient', default: '#00ffc8', section: 'colors' },
      color2: { type: 'color', label: 'Secondary Colour', default: '#4466ff', section: 'colors' },
      colorShell: { type: 'color', label: 'Atmosphere Shell', default: '#00ffc8', section: 'colors' },
      aberration: { type: 'number', label: 'Chromatic Aberration', min: 0, max: 2, step: 0.01, default: 0.85, section: 'colors' },
      glowIntensity: { type: 'number', label: 'Internal Glow', min: 0.002, max: 0.03, step: 0.001, default: 0.007, section: 'colors' },
      atmosphereStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.3, section: 'colors' },
      sphereRadius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 3.5, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.1, max: 1.2, step: 0.01, default: 0.381, section: 'geometry' },
      fractalScale: { type: 'number', label: 'Domain Scale', min: 0.2, max: 1.4, step: 0.01, default: 0.7602, section: 'geometry' },
      fractalMult: { type: 'number', label: 'Fractal Multiplier', min: 1.2, max: 3.8, step: 0.05, default: 2.196, section: 'geometry' },
      particleDensity: { type: 'number', label: 'Stardust Density', min: 0, max: 0.05, step: 0.001, default: 0.014, section: 'geometry' },
      sphereSpinSpeed: { type: 'number', label: 'Fractal Spin', min: -3, max: 3, step: 0.05, default: -0.65, section: 'motion' },
      fractalWarpSpeed: { type: 'number', label: 'Warp Speed', min: 0.005, max: 0.08, step: 0.001, default: 0.0262, section: 'motion' },
    },
  },
  {
    key: 'QUANTUM',
    id: 'quantum',
    name: 'Fractal Lattice',
    badge: 'IFS Fractal',
    description: 'A recursive iterated-function lattice folded through four dimensions and traced with glowing orbit lines.',
    defaultPreset: 'Phosphor Lattice',
    file: 'quantum-engine.js',
    factoryName: 'createQuantumEngine',
    params: {
      color1: { type: 'color', label: 'Primary Colour', default: '#0066ff', section: 'colors' },
      color2: { type: 'color', label: 'Secondary Colour', default: '#a855f7', section: 'colors' },
      color3: { type: 'color', label: 'Core Colour', default: '#00f2fe', section: 'colors' },
      edgeGlow: { type: 'number', label: 'Edge Luma', min: 0, max: 3, step: 0.05, default: 1.2, section: 'colors' },
      shape: { type: 'select', label: 'Lattice Geometry', options: ['sphere', 'cube', 'octahedron'], default: 'sphere', section: 'geometry' },
      cubeSize: { type: 'number', label: 'Structure Size', min: 0.6, max: 2.2, step: 0.05, default: 1.25, section: 'geometry' },
      scaleFactor: { type: 'number', label: 'Recursion Scale', min: 1.4, max: 3.2, step: 0.01, default: 2.15, section: 'geometry' },
      orbitPathWidth: { type: 'number', label: 'Orbital Line Width', min: 1, max: 8, step: 0.5, default: 4, section: 'geometry' },
      orbitPathBrightness: { type: 'number', label: 'Orbital Brightness', min: 0.5, max: 6, step: 0.1, default: 3.5, section: 'geometry' },
      rotSpeedX: { type: 'number', label: 'Rotation Pitch', min: 0, max: 0.8, step: 0.02, default: 0.18, section: 'motion' },
      rotSpeedY: { type: 'number', label: 'Rotation Yaw', min: 0, max: 0.8, step: 0.02, default: 0.28, section: 'motion' },
      fractalSpeed: { type: 'number', label: 'Fractal Oscillation', min: 0.2, max: 2.5, step: 0.05, default: 1, section: 'motion' },
      morphSpeed: { type: 'number', label: 'Morph Speed', min: 0.2, max: 2.5, step: 0.05, default: 1, section: 'motion' },
    },
  },
  {
    key: 'SINGULARITY',
    id: 'singularity',
    name: 'Black Hole',
    badge: 'Accretion Disk',
    description: 'Event horizon with gravitational light bending, Doppler-beamed accretion disk, and relativistic photon sphere.',
    defaultPreset: 'Gargantua Singularity',
    file: 'singularity-engine.js',
    factoryName: 'createSingularityEngine',
    params: {
      color1: { type: 'color', label: 'Accretion Core Flame', default: '#f59e0b', section: 'colors' },
      color2: { type: 'color', label: 'Outer Collapsar Halo', default: '#ef4444', section: 'colors' },
      color3: { type: 'color', label: 'Relativistic Doppler Blue', default: '#38bdf8', section: 'colors' },
      horizonRadius: { type: 'number', label: 'Event Horizon Radius', min: 0.5, max: 1.6, step: 0.05, default: 1.05, section: 'geometry' },
      diskInner: { type: 'number', label: 'Accretion Inner Ring', min: 0.8, max: 2.2, step: 0.05, default: 1.45, section: 'geometry' },
      diskOuter: { type: 'number', label: 'Accretion Outer Edge', min: 2.2, max: 5, step: 0.1, default: 3.5, section: 'geometry' },
      accretionDensity: { type: 'number', label: 'Disk Density', min: 0.4, max: 3, step: 0.05, default: 1.6, section: 'geometry' },
      warpStrength: { type: 'number', label: 'Gravitational Lensing', min: 0.2, max: 2.5, step: 0.05, default: 1.35, section: 'motion' },
      diskSpeed: { type: 'number', label: 'Vortex Orbital Velocity', min: 0.2, max: 2.5, step: 0.05, default: 0.85, section: 'motion' },
      dopplerShift: { type: 'number', label: 'Relativistic Beaming', min: 0, max: 1.5, step: 0.05, default: 0.75, section: 'motion' },
      diskTilt: { type: 'number', label: 'Accretion Plane Tilt', min: -1, max: 1, step: 0.02, default: 0.28, section: 'motion' },
      spiralArms: { type: 'select', label: 'Spiral Density Arms', options: [2, 3, 4, 5, 6], default: 3, section: 'geometry' },
      armContrast: { type: 'number', label: 'Arm Definition', min: 0, max: 1, step: 0.01, default: 0.65, section: 'motion' },
    },
  },
  {
    key: 'SILKWARP',
    id: 'silkwarp',
    name: 'Silk Warp',
    badge: 'Domain-Warped Flow',
    description: 'Layered warped-noise currents flowing over a shaded sphere, blended in perceptual colour space so every mid-tone keeps its hue.',
    defaultPreset: 'Teal Undertow',
    file: 'silkwarp-engine.js',
    factoryName: 'createSilkWarpEngine',
    params: {
      color1: { type: 'color', label: 'Current Tint', default: '#5eead4', section: 'colors' },
      color2: { type: 'color', label: 'Undertow Tint', default: '#818cf8', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#e0f2fe', section: 'colors' },
      contrast: { type: 'number', label: 'Silk Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.15, section: 'colors' },
      glow: { type: 'number', label: 'Current Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.1, section: 'colors' },
      sheen: { type: 'number', label: 'Iridescent Sheen', min: 0, max: 1, step: 0.01, default: 0.35, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.25, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 3, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      octaves: { type: 'select', label: 'Detail Octaves', options: [3, 4, 5, 6], default: 5, section: 'geometry' },
      warpDepth: { type: 'number', label: 'Warp Intensity', min: 0, max: 2.5, step: 0.05, default: 1.25, section: 'motion' },
      warpScale: { type: 'number', label: 'Warp Grain', min: 0.5, max: 4, step: 0.05, default: 2.4, section: 'motion' },
      driftSpin: { type: 'number', label: 'Current Drift', min: -1, max: 1, step: 0.01, default: 0.22, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Drift', min: -1, max: 1, step: 0.01, default: -0.13, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.45, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.3, step: 0.01, default: 0.08, section: 'motion' },
    },
  },
  {
    key: 'KALEIDO',
    id: 'kaleido',
    name: 'Kaleido Sigil',
    badge: 'Fold-Fractural Mandala',
    description: 'A kaleidoscopic fold fractal — mirrored wedges of an orbit-trapped similarity iteration, drawn as glowing contour filaments on a shaded disc.',
    defaultPreset: 'Gilded Rose Window',
    file: 'kaleido-engine.js',
    factoryName: 'createKaleidoEngine',
    params: {
      color1: { type: 'color', label: 'Petal Tint', default: '#ffd166', section: 'colors' },
      color2: { type: 'color', label: 'Vortex Tint', default: '#e879f9', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Halo', default: '#fff7ed', section: 'colors' },
      edgeGlow: { type: 'number', label: 'Line Radiance', min: 0.3, max: 3, step: 0.05, default: 1.35, section: 'colors' },
      lineWidth: { type: 'number', label: 'Contour Weight', min: 0.3, max: 2.5, step: 0.05, default: 1.1, section: 'colors' },
      grain: { type: 'number', label: 'Film Grain', min: 0, max: 0.2, step: 0.005, default: 0.035, section: 'colors' },
      radius: { type: 'number', label: 'Sigil Bounds', min: 1, max: 2.25, step: 0.05, default: 2.2, section: 'geometry' },
      symmetry: { type: 'select', label: 'Fold Symmetry', options: [5, 6, 7, 8, 9, 10, 12, 16], default: 8, section: 'geometry' },
      iterations: { type: 'select', label: 'Fold Depth', options: [4, 5, 6, 7, 8], default: 6, section: 'geometry' },
      contraction: { type: 'number', label: 'Fold Contraction', min: 0.55, max: 1.1, step: 0.01, default: 0.82, section: 'geometry' },
      warpTwist: { type: 'number', label: 'Petal Twist', min: -1.5, max: 1.5, step: 0.02, default: 0.35, section: 'motion' },
      spinRate: { type: 'number', label: 'Sigil Spin', min: -1, max: 1, step: 0.01, default: 0.16, section: 'motion' },
      counterRate: { type: 'number', label: 'Seed Orbit Rate', min: -1, max: 1, step: 0.01, default: -0.11, section: 'motion' },
      seedRadius: { type: 'number', label: 'Seed Radius', min: 0.2, max: 1.2, step: 0.01, default: 0.62, section: 'motion' },
      zoomRate: { type: 'number', label: 'Zoom Breath Rate', min: 0, max: 2, step: 0.05, default: 0.4, section: 'motion' },
      zoomDepth: { type: 'number', label: 'Zoom Depth', min: 0, max: 0.08, step: 0.005, default: 0.05, section: 'motion' },
    },
  },
  {
    key: 'VEIL',
    id: 'veil',
    name: 'Prism Veil',
    badge: 'Thin-Film Iridescence',
    description: 'An oil-film of warped noise over a wet sphere — spectral interference colours sliding across the surface with a moving specular glint.',
    defaultPreset: 'Oil Slick Reverie',
    file: 'prism-veil-engine.js',
    factoryName: 'createPrismVeilEngine',
    params: {
      color1: { type: 'color', label: 'Base Tint', default: '#2dd4bf', section: 'colors' },
      color2: { type: 'color', label: 'Undertow Tint', default: '#7c3aed', section: 'colors' },
      iridStrength: { type: 'number', label: 'Iridescence', min: 0, max: 1, step: 0.01, default: 0.75, section: 'colors' },
      sheen: { type: 'number', label: 'Wet Glint', min: 0, max: 1.5, step: 0.01, default: 0.6, section: 'colors' },
      contrast: { type: 'number', label: 'Film Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.1, section: 'colors' },
      glow: { type: 'number', label: 'Film Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.22, section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#eef2ff', section: 'colors', paletteRole: 'fixed' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      octaves: { type: 'select', label: 'Detail Octaves', options: [3, 4, 5, 6], default: 5, section: 'geometry' },
      filmThickness: { type: 'number', label: 'Film Thickness', min: 0.5, max: 3, step: 0.05, default: 1.6, section: 'motion' },
      filmFrequency: { type: 'number', label: 'Spectral Banding', min: 0.3, max: 2, step: 0.01, default: 1.0, section: 'motion' },
      warpDepth: { type: 'number', label: 'Warp Intensity', min: 0, max: 2.5, step: 0.05, default: 1.35, section: 'motion' },
      driftSpin: { type: 'number', label: 'Current Drift', min: -1, max: 1, step: 0.01, default: 0.18, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Drift', min: -1, max: 1, step: 0.01, default: -0.11, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.4, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.07, section: 'motion' },
    },
  },
  {
    key: 'MOSAIC',
    id: 'mosaic',
    name: 'Luminous Mosaic',
    badge: 'Voronoi Glass',
    description: 'A drifting tessellation of stained-glass cells with luminous seams — light breathes across the orb one cell at a time.',
    defaultPreset: 'Cathedral Window',
    file: 'luminous-mosaic-engine.js',
    factoryName: 'createLuminousMosaicEngine',
    params: {
      color1: { type: 'color', label: 'Glass Base', default: '#1d4ed8', section: 'colors' },
      color2: { type: 'color', label: 'Glass Accent', default: '#22d3ee', section: 'colors' },
      borderColor: { type: 'color', label: 'Seam Light', default: '#ffd166', section: 'colors' },
      borderGlow: { type: 'number', label: 'Seam Radiance', min: 0, max: 3, step: 0.05, default: 1.3, section: 'colors' },
      borderSoft: { type: 'number', label: 'Seam Width', min: 0.01, max: 0.2, step: 0.005, default: 0.07, section: 'colors' },
      glow: { type: 'number', label: 'Glass Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.2, section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#e0f2fe', section: 'colors', paletteRole: 'fixed' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      cellScale: { type: 'number', label: 'Cell Density', min: 1.5, max: 6, step: 0.05, default: 3.2, section: 'motion' },
      tintSpread: { type: 'number', label: 'Tint Variance', min: 0, max: 1, step: 0.01, default: 0.55, section: 'motion' },
      cellBreath: { type: 'number', label: 'Cell Breath', min: 0, max: 1, step: 0.01, default: 0.6, section: 'motion' },
      driftSpin: { type: 'number', label: 'Lattice Drift', min: -1, max: 1, step: 0.01, default: 0.14, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Drift', min: -1, max: 1, step: 0.01, default: -0.09, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.06, section: 'motion' },
    },
  },
  {
    key: 'KALISET',
    id: 'kaliset',
    name: 'Kaliset Lace',
    badge: 'Orbit-Trap Threads',
    description: 'Lace drawn by the Kaliset fold: points folded and inverted again and again, lit where their orbit passes near a ring.',
    defaultPreset: 'Gossamer Field',
    file: 'kaliset-lace-engine.js',
    factoryName: 'createKalisetLaceEngine',
    params: {
      color1: { type: 'color', label: 'Thread Tint', default: '#f43f5e', section: 'colors' },
      color2: { type: 'color', label: 'Ground Tint', default: '#fbbf24', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#fff1f2', section: 'colors', paletteRole: 'fixed' },
      laceGlow: { type: 'number', label: 'Lace Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.15, section: 'colors' },
      contrast: { type: 'number', label: 'Lace Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.2, section: 'colors' },
      glow: { type: 'number', label: 'Field Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.2, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      folds: { type: 'select', label: 'Fold Count', options: [6, 8, 10, 12, 14], default: 12, section: 'geometry' },
      threadSharp: { type: 'number', label: 'Thread Sharpness', min: 2, max: 16, step: 0.1, default: 7, section: 'motion' },
      ringRadius: { type: 'number', label: 'Trap Ring Radius', min: 0.2, max: 1.2, step: 0.01, default: 0.55, section: 'motion' },
      foldScale: { type: 'number', label: 'Lace Grain', min: 0.6, max: 3, step: 0.05, default: 1.6, section: 'motion' },
      seedStrength: { type: 'number', label: 'Seed Strength', min: 0.3, max: 0.9, step: 0.005, default: 0.62, section: 'motion' },
      driftSpin: { type: 'number', label: 'Lace Drift', min: -1, max: 1, step: 0.01, default: 0.12, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Drift', min: -1, max: 1, step: 0.01, default: -0.08, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.06, section: 'motion' },
    },
  },
];
