import { createTesseractEngine } from '../engines/tesseract-engine.js';
import { createMoireEngine } from '../engines/moire-engine.js';
import { createAurisEngine } from '../engines/auris-engine.js';
import { createHopfEngine } from '../engines/hopf-engine.js';
import { createPolytopeEngine } from '../engines/polytope-engine.js';
import { createNebulaEngine } from '../engines/nebula-engine.js';
import { createQuantumEngine } from '../engines/quantum-engine.js';
import { createSingularityEngine } from '../engines/singularity-engine.js';

export const ANALYTIC_ENGINES = [
  {
    key: 'TESSERACT',
    id: 'tesseract',
    name: '4D Tesseract',
    badge: 'Hypercube Projection',
    description: 'Canonical 4-dimensional hypercube projected into 3D space with rigid 3D perspective and harmonic 4D inversion.',
    defaultPreset: 'Canonical Hypercube',
    file: 'tesseract-engine.js',
    factoryName: 'createTesseractEngine',
    factory: createTesseractEngine,
    params: {
      color1: { type: 'color', label: 'Outer Cube Edges', default: '#ffed00', section: 'colors' },
      color2: { type: 'color', label: 'Inner Cube Edges', default: '#00f0ff', section: 'colors' },
      colorStrut: { type: 'color', label: 'Corner Struts', default: '#ffffff', section: 'colors', paletteRole: 'fixed' },
      nodeColor: { type: 'color', label: 'Corner Vertex Nodes', default: '#ffffff', section: 'colors', paletteRole: 'fixed' },
      cellColor: { type: 'color', label: 'Glass Facet Tint', default: '#ffed00', section: 'colors' },
      edgeGlow: { type: 'number', label: 'Edge Radiance', min: 0.5, max: 3.5, step: 0.1, default: 1.2, section: 'colors' },
      projection: { type: 'select', label: '4D Viewing Axis', options: ['cell_first', 'face_first', 'edge_first', 'vertex_first'], default: 'cell_first', section: 'geometry' },
      edgeMode: { type: 'select', label: 'Edge Architecture', options: ['sketch', 'cubes', 'outer_struts', 'inner_struts', 'struts'], default: 'sketch', section: 'geometry' },
      innerScale: { type: 'number', label: 'Inner Cube Ratio', min: 0.25, max: 0.75, step: 0.01, default: 0.48, section: 'geometry' },
      cubeSize: { type: 'number', label: 'Hypercube Scale', min: 0.6, max: 2.5, step: 0.05, default: 1.35, section: 'geometry' },
      edgeWidth: { type: 'number', label: 'Edge Line Width', min: 1, max: 6, step: 0.2, default: 2.6, section: 'geometry' },
      nodeSize: { type: 'number', label: 'Corner Vertex Nodes', min: 0, max: 0.12, step: 0.005, default: 0.038, section: 'geometry' },
      cellOpacity: { type: 'number', label: 'Glass Facet Opacity', min: 0, max: 0.4, step: 0.01, default: 0, section: 'geometry' },
      motionMode: { type: 'select', label: 'Motion Dynamic', options: ['sketch3d', 'hyperfold', 'pulse', 'true4d'], default: 'sketch3d', section: 'motion' },
      rotSpeedX: { type: 'number', label: '3D Rotation Pitch', min: -2, max: 2, step: 0.05, default: 0.25, section: 'motion' },
      rotSpeedY: { type: 'number', label: '3D Rotation Yaw', min: -2, max: 2, step: 0.05, default: 0.5, section: 'motion' },
      pulseSpeed: { type: 'number', label: 'Fold / Pulse Speed', min: 0.2, max: 3, step: 0.1, default: 1.2, section: 'motion' },
      rotSpeedXW: { type: 'number', label: '4D Hyperspace XW', min: -2, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      rotSpeedYW: { type: 'number', label: '4D Hyperspace YW', min: -2, max: 2, step: 0.05, default: 0.45, section: 'motion' },
    },
  },
  {
    key: 'MOIRE',
    id: 'moire',
    name: 'Chiral Moiré',
    badge: 'Optical String Art',
    description: 'Nine sacred geometric ruled-surface wireframes, chiral vortexes, and interference moiré patterns with harmonic breathing apertures.',
    defaultPreset: '1. Chiral Square Vortex',
    file: 'moire-engine.js',
    factoryName: 'createMoireEngine',
    factory: createMoireEngine,
    params: {
      archetype: { type: 'select', label: 'Grid Archetype', options: ['meridian_beat', 'lattice_beat', 'helix_beat'], default: 'meridian_beat', section: 'geometry' },
      scale: { type: 'number', label: 'Orb Scale', min: 0.8, max: 3, step: 0.05, default: 2.2, section: 'geometry' },
      lineDensity: { type: 'number', label: 'Meridians', min: 8, max: 60, step: 1, default: 28, section: 'geometry' },
      beatOffset: { type: 'number', label: 'Beat Offset', min: -8, max: 8, step: 1, default: 2, section: 'geometry' },
      latBands: { type: 'number', label: 'Latitude Rings', min: 0, max: 24, step: 1, default: 8, section: 'geometry' },
      twistAngle: { type: 'number', label: 'Chiral Twist Angle', min: -1.5, max: 1.5, step: 0.02, default: 0.72, section: 'geometry' },
      shellGap: { type: 'number', label: 'Shell Gap', min: 0.55, max: 0.99, step: 0.01, default: 0.9, section: 'motion' },
      lineWidth: { type: 'number', label: 'Line Stroke Thickness', min: 0.5, max: 6, step: 0.1, default: 1.6, section: 'geometry' },
      lineColor: { type: 'color', label: 'Line Color', default: '#7fe9ff', section: 'colors' },
      lineGlow: { type: 'number', label: 'Line Glow / Radiance', min: 0.5, max: 3, step: 0.1, default: 1, section: 'colors' },
      motionMode: { type: 'select', label: 'Motion Dynamic', options: ['counter_spin', 'orbit_3d', 'wave_pulse', 'interactive_tilt'], default: 'counter_spin', section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Spin Rate', min: -2, max: 2, step: 0.05, default: 0.55, section: 'motion' },
      rotSpeedX: { type: 'number', label: '3D Pitch Rotation', min: -2, max: 2, step: 0.02, default: 0.06, section: 'motion' },
      rotSpeedY: { type: 'number', label: '3D Yaw Rotation', min: -2, max: 2, step: 0.02, default: 0.18, section: 'motion' },
      rotSpeedZ: { type: 'number', label: '3D Roll Rotation', min: -2, max: 2, step: 0.02, default: 0, section: 'motion' },
      breatheSpeed: { type: 'number', label: 'Shell Breath Rate', min: 0, max: 2.5, step: 0.05, default: 0.6, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breathing Amplitude', min: 0, max: 0.25, step: 0.01, default: 0.05, section: 'motion' },
      twistSpeed: { type: 'number', label: 'Chiral Winding Speed', min: 0, max: 2, step: 0.05, default: 0.15, section: 'motion' },
      tiltStrength: { type: 'number', label: 'Mouse Parallax Depth', min: 0, max: 1, step: 0.05, default: 0.35, section: 'motion' },
    },
  },
  {
    key: 'AURIS',
    id: 'auris',
    name: 'Auris Light',
    badge: 'Sacred Crystallography',
    description: 'Multifaceted geodesic polyhedra, Kepler cubic compounds, and chiral wireframe vortexes illuminated with directional light and architectural hatching.',
    defaultPreset: 'Geodesic Stellated Sun',
    file: 'auris-engine.js',
    factoryName: 'createAurisEngine',
    factory: createAurisEngine,
    params: {
      archetype: { type: 'select', label: 'Crystalline Archetype', options: ['geodesic', 'cubic_compound', 'nested_square', 'nested_hex', 'nested_pentagon', 'nested_triangle'], default: 'geodesic', section: 'geometry' },
      scale: { type: 'number', label: 'Polyhedron Scale', min: 0.8, max: 2.5, step: 0.05, default: 1.4, section: 'geometry' },
      stellaHeight: { type: 'number', label: 'Stellation / 3D Depth', min: 0, max: 1.2, step: 0.02, default: 0.45, section: 'geometry' },
      twistAngle: { type: 'number', label: 'Per-Layer Rotation', min: 0.02, max: 0.35, step: 0.01, default: 0.14, section: 'geometry' },
      wireWidth: { type: 'number', label: 'Contour Line Width', min: 1, max: 5, step: 0.2, default: 2.4, section: 'geometry' },
      lightColor: { type: 'color', label: 'Directional Light Tint', default: '#ffea79', section: 'colors' },
      facetColor: { type: 'color', label: 'Facet Base Shading', default: '#1e293b', section: 'colors', paletteRole: 'fixed' },
      wireColor: { type: 'color', label: 'Glowing Edge Contours', default: '#fef08a', section: 'colors' },
      shadowColor: { type: 'color', label: 'Shadow Ambient Tone', default: '#090d16', section: 'colors', paletteRole: 'fixed' },
      wireGlow: { type: 'number', label: 'Wire Radiance', min: 0.5, max: 3.5, step: 0.1, default: 1.3, section: 'colors' },
      hatchStrength: { type: 'number', label: 'Architectural Hatching', min: 0, max: 1, step: 0.05, default: 0.85, section: 'colors' },
      lightYaw: { type: 'number', label: 'Light Direction (Azimuth)', min: 0, max: 360, step: 5, default: 45, section: 'motion' },
      lightPitch: { type: 'number', label: 'Light Elevation (Altitude)', min: -85, max: 85, step: 5, default: 35, section: 'motion' },
      lightIntensity: { type: 'number', label: 'Illumination Power', min: 0.4, max: 3.5, step: 0.1, default: 1.6, section: 'motion' },
      hatchDensity: { type: 'number', label: 'Hatching Frequency', min: 6, max: 50, step: 1, default: 18, section: 'motion' },
      rotSpeedX: { type: 'number', label: '3D Rotation Pitch', min: -2, max: 2, step: 0.05, default: 0.2, section: 'motion' },
      rotSpeedY: { type: 'number', label: '3D Rotation Yaw', min: -2, max: 2, step: 0.05, default: 0.45, section: 'motion' },
      rotSpeedZ: { type: 'number', label: '3D Rotation Roll', min: -2, max: 2, step: 0.05, default: 0.1, section: 'motion' },
    },
  },
  {
    key: 'HOPF',
    id: 'hopf',
    name: 'Hopf Fibration',
    badge: 'Clifford Torus',
    description: 'Stereographic projection of the 3-sphere S³ to R³ generating nested Villarceau circle fibers and Clifford toroidal inversions.',
    defaultPreset: 'Clifford Quantum Vortex',
    file: 'hopf-engine.js',
    factoryName: 'createHopfEngine',
    factory: createHopfEngine,
    params: {
      color1: { type: 'color', label: 'Core Villarceau Ring', default: '#ffed00', section: 'colors' },
      color2: { type: 'color', label: 'Outer Toroidal Shell', default: '#a855f7', section: 'colors' },
      accentColor: { type: 'color', label: 'Streamline Sparkles', default: '#00f2fe', section: 'colors' },
      glowIntensity: { type: 'number', label: 'Fiber Radiance', min: 0.4, max: 3.5, step: 0.1, default: 1.5, section: 'colors' },
      fiberCount: { type: 'select', label: 'Fiber Circle Count', options: [16, 24, 32, 48], default: 32, section: 'geometry' },
      torusRadius: { type: 'number', label: 'Major Torus Radius (R)', min: 0.8, max: 2.8, step: 0.05, default: 1.75, section: 'geometry' },
      tubeRadius: { type: 'number', label: 'Minor Torus Radius (r)', min: 0.3, max: 1.6, step: 0.05, default: 0.85, section: 'geometry' },
      lineWidth: { type: 'number', label: 'Fiber Ribbon Width', min: 1, max: 6, step: 0.5, default: 2.8, section: 'geometry' },
      cliffordSpeed: { type: 'number', label: 'Clifford 4D Inversion Rate', min: 0, max: 2.5, step: 0.05, default: 0.7, section: 'motion' },
      flowSpeed: { type: 'number', label: 'Stream Flow Velocity', min: 0.1, max: 3, step: 0.1, default: 1.2, section: 'motion' },
      twistHarmonics: { type: 'number', label: 'Winding Harmonics', min: 1, max: 5, step: 1, default: 2, section: 'motion' },
    },
  },
  {
    key: 'POLYTOPE',
    id: 'polytope',
    name: 'Sacred Polytope',
    badge: 'Merkabah & Kepler Star',
    description: 'Dual counter-rotating Stella Octangula with nested Kepler-Poinsot star, geodesic wireframes, and chromatic dispersion facets.',
    defaultPreset: 'Lumaform Gold Merkabah',
    file: 'polytope-engine.js',
    factoryName: 'createPolytopeEngine',
    factory: createPolytopeEngine,
    params: {
      color1: { type: 'color', label: 'Primary Star (Yang)', default: '#ffed00', section: 'colors' },
      color2: { type: 'color', label: 'Counter Star (Yin)', default: '#ec4899', section: 'colors' },
      coreColor: { type: 'color', label: 'Divine Core Spark', default: '#ffffff', section: 'colors', paletteRole: 'fixed' },
      wireColor: { type: 'color', label: 'Geodesic Wireframe', default: '#00f0ff', section: 'colors' },
      wireGlow: { type: 'number', label: 'Wireframe Luma', min: 0.5, max: 3.5, step: 0.1, default: 1.8, section: 'colors' },
      facetDispersion: { type: 'number', label: 'Prismatic Dispersion', min: 0, max: 1.5, step: 0.05, default: 0.75, section: 'colors' },
      polytopeType: { type: 'select', label: 'Sacred Archetype', options: ['merkabah', 'kepler_star', 'icosa_stellation'], default: 'merkabah', section: 'geometry' },
      scale: { type: 'number', label: 'Polytope Outer Radius', min: 0.8, max: 2.6, step: 0.05, default: 1.65, section: 'geometry' },
      coreRadius: { type: 'number', label: 'Divine Core Radius', min: 0.15, max: 0.9, step: 0.05, default: 0.45, section: 'geometry' },
      wireThickness: { type: 'number', label: 'Geodesic Line Width', min: 1, max: 6, step: 0.5, default: 3, section: 'geometry' },
      rotRateA: { type: 'number', label: 'Star A Spin Velocity', min: -2, max: 2, step: 0.05, default: 0.6, section: 'motion' },
      rotRateB: { type: 'number', label: 'Star B Counter-Spin', min: -2, max: 2, step: 0.05, default: -0.6, section: 'motion' },
    },
  },
  {
    key: 'NEBULA',
    id: 'nebula',
    name: 'Gyroid Nebula',
    badge: 'Volumetric Raymarching',
    description: 'Organic, volumetric gyroid SDF folded within a glowing atmospheric forcefield with chromatic aberration and cosmic stardust.',
    defaultPreset: 'Aurora Core',
    file: 'nebula-engine.js',
    factoryName: 'createNebulaEngine',
    factory: createNebulaEngine,
    params: {
      color1: { type: 'color', label: 'Primary Gradient', default: '#00ffc8', section: 'colors' },
      color2: { type: 'color', label: 'Secondary Field', default: '#4466ff', section: 'colors' },
      colorShell: { type: 'color', label: 'Atmosphere Shell', default: '#00ffc8', section: 'colors' },
      aberration: { type: 'number', label: 'Chromatic Aberration', min: 0, max: 2, step: 0.01, default: 0.85, section: 'colors' },
      glowIntensity: { type: 'number', label: 'Internal Glow', min: 0.002, max: 0.03, step: 0.001, default: 0.007, section: 'colors' },
      atmosphereStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.3, section: 'colors' },
      sphereRadius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 3.5, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.1, max: 1.2, step: 0.01, default: 0.381, section: 'geometry' },
      fractalScale: { type: 'number', label: 'Domain Scale', min: 0.2, max: 1.4, step: 0.01, default: 0.7602, section: 'geometry' },
      fractalMult: { type: 'number', label: 'Fractal Multiplier', min: 1.2, max: 3.8, step: 0.05, default: 2.196, section: 'geometry' },
      particleDensity: { type: 'number', label: 'Stardust Density', min: 0, max: 0.05, step: 0.001, default: 0.014, section: 'geometry' },
      sphereSpinSpeed: { type: 'number', label: 'Fractal Spin', min: -3, max: 3, step: 0.05, default: -0.65, section: 'motion' },
      fractalWarpSpeed: { type: 'number', label: 'Warp Speed', min: 0.005, max: 0.08, step: 0.001, default: 0.0262, section: 'motion' },
    },
  },
  {
    key: 'QUANTUM',
    id: 'quantum',
    name: 'Quantum Lattice',
    badge: '4D Hyper-Fractal',
    description: 'Hyper-dimensional recursive IFS fractal lattice with glowing quantum orbital filaments and geometric symmetries.',
    defaultPreset: 'Cyber Matrix',
    file: 'quantum-engine.js',
    factoryName: 'createQuantumEngine',
    factory: createQuantumEngine,
    params: {
      color1: { type: 'color', label: 'Primary Energy', default: '#0066ff', section: 'colors' },
      color2: { type: 'color', label: 'Secondary Field', default: '#a855f7', section: 'colors' },
      color3: { type: 'color', label: 'Quantum Core', default: '#00f2fe', section: 'colors' },
      edgeGlow: { type: 'number', label: 'Edge Luma', min: 0, max: 3, step: 0.05, default: 1.2, section: 'colors' },
      shape: { type: 'select', label: 'Lattice Geometry', options: ['sphere', 'cube', 'octahedron'], default: 'sphere', section: 'geometry' },
      cubeSize: { type: 'number', label: 'Structure Size', min: 0.6, max: 2.2, step: 0.05, default: 1.25, section: 'geometry' },
      scaleFactor: { type: 'number', label: 'Recursion Scale', min: 1.4, max: 3.2, step: 0.01, default: 2.15, section: 'geometry' },
      orbitPathWidth: { type: 'number', label: 'Orbital Line Width', min: 1, max: 8, step: 0.5, default: 4, section: 'geometry' },
      orbitPathBrightness: { type: 'number', label: 'Orbital Brightness', min: 0.5, max: 6, step: 0.1, default: 3.5, section: 'geometry' },
      rotSpeedX: { type: 'number', label: 'Rotation Pitch', min: 0, max: 0.8, step: 0.02, default: 0.18, section: 'motion' },
      rotSpeedY: { type: 'number', label: 'Rotation Yaw', min: 0, max: 0.8, step: 0.02, default: 0.28, section: 'motion' },
      fractalSpeed: { type: 'number', label: 'Fractal Oscillation', min: 0.2, max: 2.5, step: 0.05, default: 1, section: 'motion' },
      morphSpeed: { type: 'number', label: 'Dimensional Morph', min: 0.2, max: 2.5, step: 0.05, default: 1, section: 'motion' },
    },
  },
  {
    key: 'SINGULARITY',
    id: 'singularity',
    name: 'Chrono Singularity',
    badge: 'Relativistic Black Hole',
    description: 'Event horizon with gravitational light bending, Doppler-beamed accretion disk, and relativistic photon sphere.',
    defaultPreset: 'Gargantua Singularity',
    file: 'singularity-engine.js',
    factoryName: 'createSingularityEngine',
    factory: createSingularityEngine,
    params: {
      color1: { type: 'color', label: 'Accretion Core Flame', default: '#f59e0b', section: 'colors' },
      color2: { type: 'color', label: 'Outer Collapsar Halo', default: '#ef4444', section: 'colors' },
      color3: { type: 'color', label: 'Relativistic Doppler Blue', default: '#38bdf8', section: 'colors' },
      horizonRadius: { type: 'number', label: 'Event Horizon Radius', min: 0.5, max: 1.6, step: 0.05, default: 1.05, section: 'geometry' },
      diskInner: { type: 'number', label: 'Accretion Inner Ring', min: 0.8, max: 2.2, step: 0.05, default: 1.45, section: 'geometry' },
      diskOuter: { type: 'number', label: 'Accretion Outer Edge', min: 2.2, max: 5, step: 0.1, default: 3.5, section: 'geometry' },
      accretionDensity: { type: 'number', label: 'Disk Density', min: 0.4, max: 3, step: 0.05, default: 1.6, section: 'geometry' },
      warpStrength: { type: 'number', label: 'Gravitational Lensing', min: 0.2, max: 2.5, step: 0.05, default: 1.35, section: 'motion' },
      diskSpeed: { type: 'number', label: 'Vortex Orbital Velocity', min: 0.2, max: 2.5, step: 0.05, default: 0.85, section: 'motion' },
      dopplerShift: { type: 'number', label: 'Relativistic Beaming', min: 0, max: 1.5, step: 0.05, default: 0.75, section: 'motion' },
      diskTilt: { type: 'number', label: 'Accretion Plane Tilt', min: -1, max: 1, step: 0.02, default: 0.28, section: 'motion' },
      spiralArms: { type: 'select', label: 'Spiral Density Arms', options: [2, 3, 4, 5, 6], default: 3, section: 'geometry' },
      armContrast: { type: 'number', label: 'Arm Definition', min: 0, max: 1, step: 0.01, default: 0.65, section: 'motion' },
    },
  },
];
