export const DOMES_ENGINES = [
  {
    key: 'SCROLLDOME',
    id: 'scrolldome',
    name: 'Scroll Dome',
    badge: 'Ornate Scrollwork',
    description: 'Interlocking scroll curves inked over a rolling sphere — two sine grids warping each other into filigree.',
    defaultPreset: 'Gilded Scrollwork',
    file: 'scroll-dome-engine.js',
    factoryName: 'createScrollDomeEngine',
    params: {
      color1: { type: 'color', label: 'Ink Lines', default: '#ffd166', section: 'colors' },
      color2: { type: 'color', label: 'Body Depth', default: '#0b1026', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#fef3c7', section: 'colors', paletteRole: 'fixed' },
      gain: { type: 'number', label: 'Ink Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1.5, step: 0.01, default: 0.35, section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0.3, max: 2, step: 0.01, default: 0.9, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.15, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      patternScale: { type: 'number', label: 'Scroll Grain', min: 1, max: 8, step: 0.05, default: 5.2, section: 'motion' },
      patternZoom: { type: 'number', label: 'Curl Tightness', min: 0.5, max: 5, step: 0.05, default: 2.4, section: 'motion' },
      swirlAmp: { type: 'number', label: 'Swirl Depth', min: 0, max: 4, step: 0.05, default: 2.3, section: 'motion' },
      warpFreq: { type: 'number', label: 'Warp Frequency', min: 0.4, max: 4, step: 0.01, default: 2.1, section: 'motion' },
      lineClamp: { type: 'number', label: 'Line Weight', min: 0.03, max: 0.4, step: 0.005, default: 0.09, section: 'motion' },
      swell: { type: 'number', label: 'Swell Depth', min: 0, max: 0.15, step: 0.005, default: 0.05, section: 'motion' },
      swirlRate: { type: 'number', label: 'Roll Rate', min: -0.5, max: 0.5, step: 0.005, default: 0.16, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Roll', min: -0.5, max: 0.5, step: 0.005, default: -0.1, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.4, section: 'motion' },
    },
  },
  {
    key: 'NACRE',
    id: 'nacre',
    name: 'Nacre Bands',
    badge: 'Mother-of-Pearl',
    description: 'Pearlescent contour bands with a hue of their own per layer — an abalone curtain boiling gently over the sphere.',
    defaultPreset: 'Abalone Sheen',
    file: 'nacre-engine.js',
    factoryName: 'createNacreEngine',
    params: {
      colorDeep: { type: 'color', label: 'Shell Body', default: '#0d1430', section: 'colors' },
      colorLow: { type: 'color', label: 'Dim Layer', default: '#2fb8c6', section: 'colors' },
      colorCrest: { type: 'color', label: 'Bright Layer', default: '#fff1de', section: 'colors' },
      colorSheen: { type: 'color', label: 'Sheen Tint', default: '#bfe4ff', section: 'colors', paletteRole: 'fixed' },
      irid: { type: 'number', label: 'Iridescence', min: 0, max: 2, step: 0.01, default: 0.7, section: 'colors' },
      irisScale: { type: 'number', label: 'Iridescence Scale', min: 0, max: 2, step: 0.005, default: 0.32, section: 'colors' },
      split: { type: 'number', label: 'Chromatic Split', min: 0, max: 0.5, step: 0.005, default: 0.1, section: 'colors' },
      gain: { type: 'number', label: 'Band Radiance', min: 0.1, max: 3, step: 0.05, default: 1.1, section: 'colors' },
      contrast: { type: 'number', label: 'Band Contrast', min: 0.2, max: 3, step: 0.01, default: 1.15, section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0.1, max: 2, step: 0.01, default: 0.75, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1.5, step: 0.01, default: 0.5, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.0, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      octaves: { type: 'select', label: 'Detail Octaves', options: [3, 4, 5], default: 4, section: 'geometry' },
      bandScale: { type: 'number', label: 'Band Count', min: 2, max: 10, step: 0.1, default: 5.5, section: 'motion' },
      bandWidth: { type: 'number', label: 'Band Width', min: 0.02, max: 0.6, step: 0.005, default: 0.2, section: 'motion' },
      warpAmp: { type: 'number', label: 'Warp Depth', min: 0, max: 2.5, step: 0.05, default: 1.0, section: 'motion' },
      beat: { type: 'number', label: 'Warp Beat', min: 0, max: 1, step: 0.01, default: 0.0, section: 'motion' },
      viewShift: { type: 'number', label: 'Angle Shift', min: 0, max: 3, step: 0.01, default: 1.34, section: 'motion' },
      boilRate: { type: 'number', label: 'Boil Rate', min: 0, max: 1, step: 0.005, default: 0.25, section: 'motion' },
      flowRate: { type: 'number', label: 'Band Drift', min: 0, max: 1.5, step: 0.005, default: 0.3, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.05, section: 'motion' },
    },
  },
  {
    key: 'QUANTPLASMA',
    id: 'quantplasma',
    name: 'Quantized Plasma',
    badge: 'Pixel Plasma',
    description: 'A lit plasma dome quantized to chunky two-tone pixels — retro waves on a coarse screen.',
    defaultPreset: 'Poster Plasma',
    file: 'quant-plasma-engine.js',
    factoryName: 'createQuantPlasmaEngine',
    params: {
      colorInk: { type: 'color', label: 'Ink Tone', default: '#101426', section: 'colors' },
      colorPaper: { type: 'color', label: 'Paper Tone', default: '#cfe6ff', section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0.1, max: 2, step: 0.01, default: 0.9, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1.5, step: 0.01, default: 0.35, section: 'colors' },
      gain: { type: 'number', label: 'Plasma Radiance', min: 0.1, max: 3, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Plasma Contrast', min: 0.2, max: 3, step: 0.01, default: 1.1, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.0, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      cells: { type: 'select', label: 'Pixel Cells', options: [60, 90, 120, 140, 180, 240], default: 140, section: 'geometry' },
      levels: { type: 'select', label: 'Tone Levels', options: [2, 3, 4, 5, 6], default: 3, section: 'geometry' },
      patternScale: { type: 'number', label: 'Plasma Scale', min: 0.4, max: 4, step: 0.01, default: 1.5, section: 'motion' },
      plasmaAmp: { type: 'number', label: 'Plasma Depth', min: 0, max: 3, step: 0.01, default: 0.9, section: 'motion' },
      plasmaRate: { type: 'number', label: 'Plasma Rate', min: 0, max: 2, step: 0.005, default: 0.5, section: 'motion' },
      spinRate: { type: 'number', label: 'Spin Rate', min: -1, max: 1, step: 0.005, default: 0.15, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.05, section: 'motion' },
    },
  },
  {
    key: 'BEADS',
    id: 'beads',
    name: 'Bead Field',
    badge: 'Packing Beads',
    description: 'Beads swelling and shrinking in their cells, packed over the ball — each on its own detuned clock.',
    defaultPreset: 'Mercury Packing',
    file: 'bead-field-engine.js',
    factoryName: 'createBeadFieldEngine',
    params: {
      colorDot: { type: 'color', label: 'Bead Tint', default: '#ffffff', section: 'colors' },
      colorDotAccent: { type: 'color', label: 'Bead Accent', default: '#eef5ff', section: 'colors' },
      colorBody: { type: 'color', label: 'Body Depth', default: '#05070c', section: 'colors' },
      colorSheen: { type: 'color', label: 'Sheen Tint', default: '#9dbfe4', section: 'colors', paletteRole: 'fixed' },
      beadShade: { type: 'number', label: 'Bead Shading', min: 0, max: 1, step: 0.01, default: 0.55, section: 'colors' },
      floorLevel: { type: 'number', label: 'Body Fill', min: 0, max: 1, step: 0.01, default: 0.06, section: 'colors' },
      gain: { type: 'number', label: 'Bead Radiance', min: 0.1, max: 3, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Bead Contrast', min: 0.2, max: 3, step: 0.01, default: 1.0, section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0, max: 2, step: 0.01, default: 0.5, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1.5, step: 0.01, default: 0.35, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.0, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      packingScale: { type: 'number', label: 'Packing Density', min: 3, max: 20, step: 0.1, default: 10.0, section: 'motion' },
      grow: { type: 'number', label: 'Bead Size', min: 0, max: 0.45, step: 0.005, default: 0.185, section: 'motion' },
      vary: { type: 'number', label: 'Size Variation', min: 0, max: 0.4, step: 0.005, default: 0.13, section: 'motion' },
      skew: { type: 'number', label: 'Detune', min: 0, max: 2, step: 0.01, default: 0.62, section: 'motion' },
      jitter: { type: 'number', label: 'Wander', min: 0, max: 0.8, step: 0.005, default: 0.1, section: 'motion' },
      edgeHardness: { type: 'number', label: 'Rim Hardness', min: 2, max: 200, step: 1, default: 50, section: 'motion' },
      pulseRate: { type: 'number', label: 'Swell Rate', min: 0, max: 2, step: 0.005, default: 0.5, section: 'motion' },
      driftSpin: { type: 'number', label: 'Packing Drift', min: -1, max: 1, step: 0.005, default: 0.12, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Drift', min: -1, max: 1, step: 0.005, default: -0.08, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.05, section: 'motion' },
    },
  },
  {
    key: 'RADAR',
    id: 'radar',
    name: 'Radar Mosaic',
    badge: 'Weather Radar',
    description: 'Fronts of coloured pixels sweeping the ball — a living weather-radar mosaic with twinkling returns.',
    defaultPreset: 'Storm Watch',
    file: 'radar-mosaic-engine.js',
    factoryName: 'createRadarMosaicEngine',
    params: {
      colorPaper: { type: 'color', label: 'Clear Tone', default: '#efe9dc', section: 'colors' },
      colorQuiet: { type: 'color', label: 'Quiet Tone', default: '#a9a9a6', section: 'colors' },
      colorLow: { type: 'color', label: 'Rain Class', default: '#2e5df0', section: 'colors' },
      colorMid: { type: 'color', label: 'Storm Class', default: '#22c35c', section: 'colors' },
      colorHigh: { type: 'color', label: 'Heavy Class', default: '#e8322a', section: 'colors' },
      colorPeak: { type: 'color', label: 'Peak Class', default: '#f5d020', section: 'colors', paletteRole: 'fixed' },
      grain: { type: 'number', label: 'Grain', min: 0, max: 0.6, step: 0.005, default: 0.1, section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0, max: 1, step: 0.005, default: 0.18, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1, step: 0.005, default: 0.35, section: 'colors' },
      gain: { type: 'number', label: 'Mosaic Radiance', min: 0.1, max: 3, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Mosaic Contrast', min: 0.2, max: 3, step: 0.01, default: 1.0, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.0, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      cells: { type: 'select', label: 'Mosaic Cells', options: [16, 24, 34, 48, 68, 90], default: 34, section: 'geometry' },
      dotSize: { type: 'number', label: 'Cell Dot', min: 0.15, max: 0.48, step: 0.005, default: 0.36, section: 'motion' },
      vortex: { type: 'number', label: 'Vortex Curl', min: 0, max: 2, step: 0.01, default: 0.45, section: 'motion' },
      warpAmp: { type: 'number', label: 'Front Warp', min: 0, max: 2, step: 0.01, default: 0.3, section: 'motion' },
      loThresh: { type: 'number', label: 'Quiet Floor', min: 0, max: 0.5, step: 0.005, default: 0.12, section: 'motion' },
      hiThresh: { type: 'number', label: 'Peak Ceiling', min: 0.5, max: 1, step: 0.005, default: 0.82, section: 'motion' },
      curve: { type: 'number', label: 'Intensity Gamma', min: 0.5, max: 3, step: 0.01, default: 1.4, section: 'motion' },
      sparse: { type: 'number', label: 'Sparse Cells', min: 0, max: 0.8, step: 0.005, default: 0.16, section: 'motion' },
      sweepRate: { type: 'number', label: 'Sweep Rate', min: 0, max: 2, step: 0.005, default: 0.3, section: 'motion' },
      spinRate: { type: 'number', label: 'Spin Rate', min: -1, max: 1, step: 0.005, default: 0.15, section: 'motion' },
      twinkleRate: { type: 'number', label: 'Twinkle Rate', min: 0, max: 10, step: 0.1, default: 3.0, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.05, section: 'motion' },
    },
  },
];
