export const REFINED_ENGINES = [
  {
    key: 'CHLADNI',
    id: 'chladni',
    name: 'Chladni Plate',
    badge: 'Cymatic Resonance',
    description: 'Sand gathering on the nodal lines of a vibrating plate — Chladni figures morphing as the resonance sweeps.',
    defaultPreset: 'Sand Sequencing',
    file: 'chladni-engine.js',
    factoryName: 'createChladniEngine',
    params: {
      colorSand: { type: 'color', label: 'Sand Lines', default: '#ffe9b8', section: 'colors' },
      colorPlate: { type: 'color', label: 'Plate Depth', default: '#101b2e', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#dbe7ff', section: 'colors', paletteRole: 'fixed' },
      sandGlow: { type: 'number', label: 'Sand Radiance', min: 0.3, max: 3, step: 0.05, default: 1.3, section: 'colors' },
      plateLight: { type: 'number', label: 'Plate Light', min: 0.2, max: 2, step: 0.01, default: 0.7, section: 'colors' },
      gain: { type: 'number', label: 'Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.1, section: 'colors' },
      radius: { type: 'number', label: 'Plate Bounds', min: 1, max: 2.25, step: 0.05, default: 2.2, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.5, step: 0.01, default: 0.1, section: 'geometry' },
      plate: { type: 'select', label: 'Plate Shape', options: ['circle', 'square'], default: 'circle', section: 'geometry' },
      modeN: { type: 'select', label: 'Mode N', options: [2, 3, 4, 5, 6, 7], default: 4, section: 'geometry' },
      modeM: { type: 'select', label: 'Mode M', options: [1, 2, 3, 4, 5, 6], default: 2, section: 'geometry' },
      resonance: { type: 'number', label: 'Resonance', min: 0, max: 1, step: 0.01, default: 0.7, section: 'motion' },
      lineWeight: { type: 'number', label: 'Line Weight', min: 0.015, max: 0.2, step: 0.005, default: 0.05, section: 'motion' },
      morphRate: { type: 'number', label: 'Resonance Sweep Rate', min: 0, max: 1, step: 0.005, default: 0.24, section: 'motion' },
      spinRate: { type: 'number', label: 'Plate Spin', min: -0.5, max: 0.5, step: 0.005, default: 0.05, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.1, step: 0.005, default: 0.04, section: 'motion' },
    },
  },
  {
    key: 'PHYLLOTAXIS',
    id: 'phyllotaxis',
    name: 'Phyllotaxis',
    badge: 'Golden Spiral',
    description: 'The sunflower head — seeds packed by the golden angle, each swelling on its own slice of a rolling breath.',
    defaultPreset: 'Sunflower Canon',
    file: 'phyllotaxis-engine.js',
    factoryName: 'createPhyllotaxisEngine',
    params: {
      colorCore: { type: 'color', label: 'Core Seeds', default: '#ffd166', section: 'colors' },
      colorEdge: { type: 'color', label: 'Edge Seeds', default: '#e879f9', section: 'colors' },
      colorBg: { type: 'color', label: 'Head Depth', default: '#0c0a14', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#fefce8', section: 'colors', paletteRole: 'fixed' },
      glow: { type: 'number', label: 'Seed Glow', min: 0.2, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0.2, max: 2, step: 0.01, default: 0.9, section: 'colors' },
      gain: { type: 'number', label: 'Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.05, section: 'colors' },
      radius: { type: 'number', label: 'Head Bounds', min: 1, max: 2.25, step: 0.05, default: 2.2, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.5, step: 0.01, default: 0.1, section: 'geometry' },
      count: { type: 'select', label: 'Seed Count', options: [140, 180, 220, 280], default: 220, section: 'geometry' },
      dotScale: { type: 'number', label: 'Seed Size', min: 0.2, max: 1.2, step: 0.01, default: 0.55, section: 'motion' },
      angleDrift: { type: 'number', label: 'Angle Drift', min: -0.15, max: 0.15, step: 0.001, default: 0.0, section: 'motion' },
      dotBreath: { type: 'number', label: 'Seed Breath', min: 0, max: 1, step: 0.01, default: 0.55, section: 'motion' },
      spinRate: { type: 'number', label: 'Head Spin', min: -0.5, max: 0.5, step: 0.005, default: 0.08, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.4, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.1, step: 0.005, default: 0.05, section: 'motion' },
    },
  },
  {
    key: 'HARMONOGRAPH',
    id: 'harmonograph',
    name: 'Harmonograph',
    badge: 'Damped Pendulums',
    description: 'A Victorian harmonograph drawing damped Lissajous ink figures — the trace slowly redrawn as the pendulums drift.',
    defaultPreset: 'Ink on Vellum',
    file: 'harmonograph-engine.js',
    factoryName: 'createHarmonographEngine',
    params: {
      colorInk: { type: 'color', label: 'Ink', default: '#1d4ed8', section: 'colors' },
      colorPaper: { type: 'color', label: 'Paper', default: '#f8f5ec', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#dbeafe', section: 'colors', paletteRole: 'fixed' },
      inkGlow: { type: 'number', label: 'Ink Glow', min: 0.3, max: 3, step: 0.05, default: 1.2, section: 'colors' },
      gain: { type: 'number', label: 'Paper Light', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.0, section: 'colors' },
      radius: { type: 'number', label: 'Paper Bounds', min: 1, max: 2.25, step: 0.05, default: 2.2, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.5, step: 0.01, default: 0.1, section: 'geometry' },
      freqA: { type: 'number', label: 'Pendulum A Frequency', min: 1, max: 6, step: 0.01, default: 3.0, section: 'motion' },
      freqB: { type: 'number', label: 'Pendulum B Frequency', min: 1, max: 6, step: 0.01, default: 2.0, section: 'motion' },
      damping: { type: 'number', label: 'Damping', min: 0.03, max: 0.5, step: 0.005, default: 0.16, section: 'motion' },
      traceLength: { type: 'number', label: 'Trace Length', min: 5, max: 15, step: 0.1, default: 10.0, section: 'motion' },
      lineWeight: { type: 'number', label: 'Ink Weight', min: 0.6, max: 6, step: 0.05, default: 1.9, section: 'motion' },
      driftRate: { type: 'number', label: 'Pendulum Drift', min: 0, max: 0.6, step: 0.005, default: 0.18, section: 'motion' },
      spinRate: { type: 'number', label: 'Paper Spin', min: -0.3, max: 0.3, step: 0.005, default: 0.04, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.3, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.1, step: 0.005, default: 0.05, section: 'motion' },
    },
  },
  {
    key: 'ATTRACTOR',
    id: 'attractor',
    name: 'Clifford Attractor',
    badge: 'Strange Attractor',
    description: 'A strange attractor condensed from pure iteration — wisps of ink reforming as one coefficient slowly drifts.',
    defaultPreset: 'Ember Wisps',
    file: 'attractor-engine.js',
    factoryName: 'createAttractorEngine',
    params: {
      colorEmber: { type: 'color', label: 'Ember Core', default: '#fbbf24', section: 'colors' },
      colorWisp: { type: 'color', label: 'Wisp Body', default: '#6366f1', section: 'colors' },
      colorBg: { type: 'color', label: 'Void', default: '#07060e', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#eef2ff', section: 'colors', paletteRole: 'fixed' },
      densityGain: { type: 'number', label: 'Ink Density', min: 0.3, max: 3, step: 0.05, default: 1.2, section: 'colors' },
      gain: { type: 'number', label: 'Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.15, section: 'colors' },
      radius: { type: 'number', label: 'Medallion Bounds', min: 1, max: 2.25, step: 0.05, default: 2.2, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.5, step: 0.01, default: 0.1, section: 'geometry' },
      iterations: { type: 'select', label: 'Orbit Depth', options: [16, 24, 32, 40], default: 32, section: 'geometry' },
      coefA: { type: 'number', label: 'Coefficient a', min: 1.2, max: 2.2, step: 0.005, default: 1.7, section: 'motion' },
      coefB: { type: 'number', label: 'Coefficient b', min: 0.8, max: 2.2, step: 0.005, default: 1.7, section: 'motion' },
      coefC: { type: 'number', label: 'Coefficient c', min: 0.2, max: 1.5, step: 0.005, default: 0.6, section: 'motion' },
      coefD: { type: 'number', label: 'Coefficient d', min: 0.2, max: 1.8, step: 0.005, default: 1.2, section: 'motion' },
      morphAmp: { type: 'number', label: 'Drift Depth', min: 0, max: 0.3, step: 0.005, default: 0.18, section: 'motion' },
      spinRate: { type: 'number', label: 'Medallion Spin', min: -0.5, max: 0.5, step: 0.005, default: 0.05, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.1, step: 0.005, default: 0.04, section: 'motion' },
    },
  },
  {
    key: 'MAURER',
    id: 'maurer',
    name: 'Maurer Rose',
    badge: 'Chord Web',
    description: 'Peter Maurer\'s chord web through a rose curve — hundreds of straight lines whose envelope weaves the petals.',
    defaultPreset: 'Rose Web',
    file: 'maurer-rose-engine.js',
    factoryName: 'createMaurerRoseEngine',
    params: {
      colorWeb: { type: 'color', label: 'Chord Ink', default: '#f9a8d4', section: 'colors' },
      colorHeart: { type: 'color', label: 'Heart Depth', default: '#170b1e', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#fdf2f8', section: 'colors', paletteRole: 'fixed' },
      chordGlow: { type: 'number', label: 'Chord Radiance', min: 0.3, max: 3, step: 0.05, default: 1.25, section: 'colors' },
      coreBloom: { type: 'number', label: 'Heart Bloom', min: 0, max: 1, step: 0.01, default: 0.5, section: 'colors' },
      gain: { type: 'number', label: 'Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.05, section: 'colors' },
      radius: { type: 'number', label: 'Medallion Bounds', min: 1, max: 2.25, step: 0.05, default: 2.2, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.5, step: 0.01, default: 0.1, section: 'geometry' },
      petals: { type: 'select', label: 'Petal Count', options: [3, 4, 5, 6, 7, 8], default: 5, section: 'geometry' },
      step: { type: 'select', label: 'Chord Step (deg)', options: [29, 51, 71, 97, 129, 151], default: 71, section: 'geometry' },
      lineWeight: { type: 'number', label: 'Line Weight', min: 0.5, max: 4, step: 0.05, default: 1.4, section: 'motion' },
      spinRate: { type: 'number', label: 'Web Spin', min: -0.5, max: 0.5, step: 0.005, default: 0.06, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.1, step: 0.005, default: 0.04, section: 'motion' },
    },
  },
  {
    key: 'INKMARBLE',
    id: 'inkmarble',
    name: 'Ink Marbling',
    badge: 'Paper Marbling',
    description: 'Suminagashi striations — a striped bath sheared by six decaying stylus passes, sharp ink lines with a gold crease.',
    defaultPreset: 'Suminagashi',
    file: 'ink-marble-engine.js',
    factoryName: 'createInkMarbleEngine',
    params: {
      colorInk: { type: 'color', label: 'Ink', default: '#1e1b4b', section: 'colors' },
      colorPaper: { type: 'color', label: 'Paper Bath', default: '#fdf6e3', section: 'colors' },
      colorAccent: { type: 'color', label: 'Gold Crease', default: '#d97706', section: 'colors' },
      creaseGain: { type: 'number', label: 'Crease Glow', min: 0, max: 1.5, step: 0.01, default: 0.6, section: 'colors' },
      gain: { type: 'number', label: 'Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.15, section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0.2, max: 2, step: 0.01, default: 0.8, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1.5, step: 0.01, default: 0.3, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.18, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      stripeDensity: { type: 'number', label: 'Stripe Density', min: 3, max: 16, step: 0.1, default: 9.0, section: 'motion' },
      swirlDepth: { type: 'number', label: 'Stylus Depth', min: 0.3, max: 3.5, step: 0.01, default: 1.7, section: 'motion' },
      swirlFreq: { type: 'number', label: 'Stylus Grain', min: 0.5, max: 3.5, step: 0.01, default: 1.6, section: 'motion' },
      driftSpin: { type: 'number', label: 'Bath Drift', min: -1, max: 1, step: 0.005, default: 0.1, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Drift', min: -1, max: 1, step: 0.005, default: -0.07, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.06, section: 'motion' },
    },
  },
  {
    key: 'LAVALAMP',
    id: 'lavalamp',
    name: 'Lava Lamp',
    badge: 'Soft Metaballs',
    description: 'Blobs of gel drifting, kissing and parting — a classic metaball field with depth shading and a crest glint.',
    defaultPreset: 'Pink Goo',
    file: 'lava-lamp-engine.js',
    factoryName: 'createLavaLampEngine',
    params: {
      colorGel: { type: 'color', label: 'Gel Tint', default: '#fb7185', section: 'colors' },
      colorGelDeep: { type: 'color', label: 'Gel Depth', default: '#7c2d4e', section: 'colors' },
      colorSpec: { type: 'color', label: 'Crest Glint', default: '#ffe4e6', section: 'colors', paletteRole: 'fixed' },
      light: { type: 'number', label: 'Key Light', min: 0.1, max: 2, step: 0.01, default: 0.9, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1.5, step: 0.01, default: 0.3, section: 'colors' },
      gain: { type: 'number', label: 'Gel Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Gel Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.05, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.2, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      blobCount: { type: 'select', label: 'Blob Count', options: [3, 4, 5, 6, 7], default: 5, section: 'geometry' },
      blobSpread: { type: 'number', label: 'Orbit Spread', min: 0.2, max: 1.2, step: 0.01, default: 0.55, section: 'motion' },
      blobSize: { type: 'number', label: 'Blob Size', min: 0.2, max: 1.1, step: 0.01, default: 0.45, section: 'motion' },
      fieldSharp: { type: 'number', label: 'Goo Softness', min: 0.05, max: 0.4, step: 0.005, default: 0.08, section: 'motion' },
      gooRate: { type: 'number', label: 'Goo Rate', min: 0.05, max: 1.5, step: 0.005, default: 0.35, section: 'motion' },
      driftSpin: { type: 'number', label: 'Drift', min: -1, max: 1, step: 0.005, default: 0.08, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Drift', min: -1, max: 1, step: 0.005, default: -0.06, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.06, section: 'motion' },
    },
  },
  {
    key: 'TRUCHET',
    id: 'truchet',
    name: 'Truchet Weave',
    badge: 'Arc Weave',
    description: 'A Truchet tiling of glowing quarter-arcs, threaded with travelling pulses — cells quietly re-thread on a slot clock.',
    defaultPreset: 'Copper Circuit',
    file: 'truchet-weave-engine.js',
    factoryName: 'createTruchetWeaveEngine',
    params: {
      colorArc: { type: 'color', label: 'Arc Tint', default: '#5eead4', section: 'colors' },
      colorCell: { type: 'color', label: 'Cell Depth', default: '#0b1220', section: 'colors' },
      colorFlow: { type: 'color', label: 'Flow Crest', default: '#fde68a', section: 'colors' },
      arcGlow: { type: 'number', label: 'Arc Radiance', min: 0.3, max: 3, step: 0.05, default: 1.3, section: 'colors' },
      arcWidth: { type: 'number', label: 'Arc Width', min: 0.4, max: 2.5, step: 0.01, default: 1.1, section: 'colors' },
      gain: { type: 'number', label: 'Weave Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Weave Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.1, section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0.2, max: 2, step: 0.01, default: 0.75, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1.5, step: 0.01, default: 0.3, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.18, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      cellScale: { type: 'number', label: 'Tile Density', min: 3, max: 14, step: 0.05, default: 9.0, section: 'motion' },
      flipRate: { type: 'number', label: 'Re-thread Rate', min: 0, max: 1.5, step: 0.005, default: 0.22, section: 'motion' },
      flowRate: { type: 'number', label: 'Pulse Rate', min: 0, max: 2, step: 0.005, default: 0.8, section: 'motion' },
      driftSpin: { type: 'number', label: 'Weave Drift', min: -1, max: 1, step: 0.005, default: 0.1, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Drift', min: -1, max: 1, step: 0.005, default: -0.07, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.06, section: 'motion' },
    },
  },
  {
    key: 'CAUSTICS',
    id: 'caustics',
    name: 'Caustic Pool',
    badge: 'Water Light',
    description: 'Underwater caustics — three octaves of sharpened light ridges knotting into the classic net as the water flows.',
    defaultPreset: 'Shallow Water',
    file: 'caustic-pool-engine.js',
    factoryName: 'createCausticPoolEngine',
    params: {
      colorShallow: { type: 'color', label: 'Shallow Tint', default: '#67e8f9', section: 'colors' },
      colorDeep: { type: 'color', label: 'Deep Tint', default: '#0e3a5c', section: 'colors' },
      colorFilament: { type: 'color', label: 'Filament Light', default: '#f0fdfa', section: 'colors' },
      filamentSharp: { type: 'number', label: 'Filament Sharpness', min: 2, max: 16, step: 0.1, default: 9.0, section: 'colors' },
      gain: { type: 'number', label: 'Pool Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Pool Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.1, section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0.2, max: 2, step: 0.01, default: 0.85, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1.5, step: 0.01, default: 0.3, section: 'colors' },
      haloStrength: { type: 'number', label: 'Atmosphere Shell', min: 0, max: 1, step: 0.01, default: 0.2, section: 'colors' },
      radius: { type: 'number', label: 'Sphere Bounds', min: 1, max: 2.6, step: 0.05, default: 2.15, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.6, step: 0.01, default: 0.18, section: 'geometry' },
      waterScale: { type: 'number', label: 'Water Scale', min: 0.8, max: 5, step: 0.01, default: 2.2, section: 'motion' },
      warpAmp: { type: 'number', label: 'Refraction Wobble', min: 0, max: 2, step: 0.01, default: 0.6, section: 'motion' },
      flowRate: { type: 'number', label: 'Flow Rate', min: 0, max: 1.5, step: 0.005, default: 0.4, section: 'motion' },
      driftSpin: { type: 'number', label: 'Pool Drift', min: -1, max: 1, step: 0.005, default: 0.1, section: 'motion' },
      counterSpin: { type: 'number', label: 'Counter-Drift', min: -1, max: 1, step: 0.005, default: -0.07, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.12, step: 0.005, default: 0.06, section: 'motion' },
    },
  },
  {
    key: 'SUPERBLOOM',
    id: 'superbloom',
    name: 'Superbloom',
    badge: 'Superformula',
    description: 'Gielis\' superformula as a living bloom — petals morphing between symmetries, a glowing envelope breathing around them.',
    defaultPreset: 'Morphing Peony',
    file: 'superbloom-engine.js',
    factoryName: 'createSuperbloomEngine',
    params: {
      colorPetal: { type: 'color', label: 'Petal Tint', default: '#f472b6', section: 'colors' },
      colorHeart: { type: 'color', label: 'Heart Tint', default: '#fde68a', section: 'colors' },
      colorEdge: { type: 'color', label: 'Edge Tint', default: '#4c1d95', section: 'colors' },
      rimColor: { type: 'color', label: 'Rim Sheen', default: '#fdf2f8', section: 'colors', paletteRole: 'fixed' },
      edgeGlow: { type: 'number', label: 'Envelope Glow', min: 0.2, max: 3, step: 0.05, default: 1.2, section: 'colors' },
      fillGradient: { type: 'number', label: 'Edge Fill', min: 0, max: 1, step: 0.01, default: 0.65, section: 'colors' },
      gain: { type: 'number', label: 'Bloom Radiance', min: 0.3, max: 2.5, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Bloom Contrast', min: 0.4, max: 2.2, step: 0.01, default: 1.05, section: 'colors' },
      radius: { type: 'number', label: 'Bloom Bounds', min: 1, max: 2.25, step: 0.05, default: 2.2, section: 'geometry' },
      edgeFade: { type: 'number', label: 'Edge Softness', min: 0.05, max: 0.5, step: 0.01, default: 0.1, section: 'geometry' },
      symmetry: { type: 'select', label: 'Petal Symmetry', options: [3, 4, 5, 6, 7, 8, 9], default: 6, section: 'geometry' },
      pinch: { type: 'number', label: 'Petal Pinch', min: 0.2, max: 2, step: 0.005, default: 0.5, section: 'motion' },
      roundness: { type: 'number', label: 'Petal Roundness', min: 0.2, max: 3, step: 0.005, default: 1.3, section: 'motion' },
      morphRate: { type: 'number', label: 'Morph Rate', min: 0, max: 0.8, step: 0.005, default: 0.16, section: 'motion' },
      spinRate: { type: 'number', label: 'Bloom Spin', min: -0.5, max: 0.5, step: 0.005, default: 0.06, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.1, step: 0.005, default: 0.05, section: 'motion' },
    },
  },
];
