export const SHAPE_ENGINES = [
  {
    key: 'LEDBOX',
    id: 'ledbox',
    name: 'LED Box',
    badge: 'LED Tile Cube',
    description: 'An LED tile wall wrapped on a raymarched rounded cube — blobs of light churn across the tiles, confetti flickers at the edges.',
    defaultPreset: 'Signal Wall',
    file: 'led-box-engine.js',
    factoryName: 'createLedBoxEngine',
    params: {
      colorLit: { type: 'color', label: 'Lit Tile', default: '#fff2dd', section: 'colors' },
      colorWall: { type: 'color', label: 'Wall', default: '#161616', section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0, max: 2, step: 0.01, default: 0.6, section: 'colors' },
      gain: { type: 'number', label: 'Tile Radiance', min: 0.1, max: 3, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Tile Contrast', min: 0.2, max: 3, step: 0.01, default: 1.0, section: 'colors' },
      shape: { type: 'select', label: 'Solid Shape', options: ['box', 'octahedron', 'sphere'], default: 'box', section: 'geometry' },
      boxSize: { type: 'number', label: 'Box Bounds', min: 1.1, max: 1.9, step: 0.05, default: 1.5, section: 'geometry' },
      bevel: { type: 'number', label: 'Corner Round', min: 0.02, max: 0.3, step: 0.005, default: 0.12, section: 'geometry' },
      cells: { type: 'select', label: 'Tile Grid', options: [24, 32, 40, 48, 64, 80], default: 40, section: 'geometry' },
      blobScale: { type: 'number', label: 'Blob Scale', min: 0.4, max: 3, step: 0.01, default: 1.3, section: 'motion' },
      coverage: { type: 'number', label: 'Lit Coverage', min: 0.15, max: 0.9, step: 0.005, default: 0.62, section: 'motion' },
      confetti: { type: 'number', label: 'Confetti', min: 0, max: 1, step: 0.005, default: 0.22, section: 'motion' },
      churnRate: { type: 'number', label: 'Churn Rate', min: 0, max: 2, step: 0.005, default: 0.5, section: 'motion' },
      driftRate: { type: 'number', label: 'Drift Rate', min: 0, max: 2, step: 0.005, default: 0.45, section: 'motion' },
      twinkleRate: { type: 'number', label: 'Twinkle Rate', min: 0, max: 8, step: 0.1, default: 2.0, section: 'motion' },
      spinRate: { type: 'number', label: 'Spin Rate', min: -0.5, max: 0.5, step: 0.005, default: 0.1, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.1, step: 0.005, default: 0.03, section: 'motion' },
    },
  },
  {
    key: 'QUANTTORUS',
    id: 'quanttorus',
    name: 'Quantized Torus',
    badge: 'Plasma Ring',
    description: 'Chunky quantized plasma flowing around a raymarched torus — retro pixel waves chasing each other around the ring.',
    defaultPreset: 'Circuit Ring',
    file: 'quant-torus-engine.js',
    factoryName: 'createQuantTorusEngine',
    params: {
      colorInk: { type: 'color', label: 'Ink Tone', default: '#101426', section: 'colors' },
      colorPaper: { type: 'color', label: 'Paper Tone', default: '#cfe6ff', section: 'colors' },
      light: { type: 'number', label: 'Key Light', min: 0.1, max: 2, step: 0.01, default: 0.9, section: 'colors' },
      rim: { type: 'number', label: 'Rim Sheen', min: 0, max: 1.5, step: 0.01, default: 0.35, section: 'colors' },
      gain: { type: 'number', label: 'Plasma Radiance', min: 0.1, max: 3, step: 0.05, default: 1.0, section: 'colors' },
      contrast: { type: 'number', label: 'Plasma Contrast', min: 0.2, max: 3, step: 0.01, default: 1.3, section: 'colors' },
      ringR: { type: 'number', label: 'Ring Radius', min: 1.05, max: 1.6, step: 0.05, default: 1.35, section: 'geometry' },
      tubeR: { type: 'number', label: 'Tube Radius', min: 0.4, max: 1.0, step: 0.01, default: 0.65, section: 'geometry' },
      profile: { type: 'select', label: 'Tube Profile', options: ['round', 'square', 'hexagon'], default: 'round', section: 'geometry' },
      tilt: { type: 'number', label: 'Ring Tilt', min: 0, max: 1.57, step: 0.01, default: 1.2, section: 'motion' },
      cells: { type: 'select', label: 'Pixel Cells', options: [24, 32, 40, 56, 72], default: 40, section: 'geometry' },
      levels: { type: 'select', label: 'Tone Levels', options: [2, 3, 4, 5, 6], default: 3, section: 'geometry' },
      patternScale: { type: 'number', label: 'Plasma Scale', min: 0.6, max: 4, step: 0.01, default: 2.0, section: 'motion' },
      plasmaAmp: { type: 'number', label: 'Plasma Depth', min: 0, max: 2.5, step: 0.01, default: 1.0, section: 'motion' },
      plasmaRate: { type: 'number', label: 'Plasma Rate', min: 0, max: 2, step: 0.005, default: 0.5, section: 'motion' },
      spinRate: { type: 'number', label: 'Spin Rate', min: -1, max: 1, step: 0.005, default: 0.12, section: 'motion' },
      breatheRate: { type: 'number', label: 'Breath Rate', min: 0, max: 2, step: 0.05, default: 0.35, section: 'motion' },
      breatheAmp: { type: 'number', label: 'Breath Depth', min: 0, max: 0.1, step: 0.005, default: 0.04, section: 'motion' },
    },
  },
];
